### ISSUE TITLE
automate byteweight test

### ISSUE THREAD

**Issue by ivg** [BinaryAnalysisPlatform/bap#100]
`bap-byteweight` has all the needed stuff on the board, it can output `symbols` found in the symbol table with `bap-byteweight symbols file`, as well as output symbols found with byteweight `bap-byteweight find file`. Given this, we can build a test suite, that will check, that we have zero false negatives.

**Comment by nedwill** [comment]
I have function ID testing code that handles this for QIRA. There's a script that generates binaries with DWARF and another one that checks QIRA function ID (which we actually do with Byteweight now) against the DWARF info which gives us function names and starts.

**Comment by ivg** [comment]
Thanks, we actually has all this too. Only the last step is left, to automate this, and to come out with some metric. Because, we (on both sides, BAP and QIRA), usually only check for the absence of false negatives, but the problem is that false positives are also very costly, as they have negative impact on a function reconstruction  (one function can be split into parts). 

P.S. the simplest way to automate is just: `comm -12 <(bap-byteweight symbols $f | sort) <(bap-byteweight find $f | sort)`, this will output all missed symbols in file `$f` if one has dwarf in it.

**Comment by dbrumley** [comment]
Tiffany is working on this, and will have it done this week in a nice, automated fashion with a blog post to boot!

**Comment by nedwill** [comment]
Oh, great! I can stick to QIRA work over the break then. I look forward to the blog post.
