### ISSUE TITLE
Provide way to redirect logs to arbitrary handler

### ISSUE THREAD

**Issue by mjambon** [BinaryAnalysisPlatform/bap#1043]
We're running bap as a library. If bap decides to log something, it should be printed to our application's log as it happens so we can see the sequence of events. Would it be possible to provide a way to define our own printer? Perhaps something similar to this:

```ocaml
(** Replace the printer used by the logger. Each input string passed to the
    printer will consist of one or several whole lines (if the last line
    doesn't end with LF, it's fine to add one). *)
val set_printer : (string -> unit) -> unit

(** Reset the printer to its original value. *)
val reset_printer : unit -> unit
```

**Comment by ivg** [comment]
This feature is already [provided][1] in BAP 2.0., see `log`, `out`, and `err` parameters, that let you redirect any of these channels. They optionally accept a formatter, which you can [redirect][2] any way you like. 

[1]: http://binaryanalysisplatform.github.io/bap/api/master/bap-main/Bap_main/index.html#val-init
[2]: http://caml.inria.fr/pub/docs/manual-ocaml/libref/Format.html#meaning

**Comment by mjambon** [comment]
I was using the documentation for `Bap.Std.Log` because we're already using its `start` function. Is it deprecated? In any case, either a deprecation notice or a link to the documentation for `Bap_main.init ~log` would be useful.

**Comment by mjambon** [comment]
So, I tried passing a formatter to `Bap_main.init`. I tried both `Format.std_formatter` and my own formatter which takes care of formatting the logs in our own format. Neither seemed to have an effect, bap logs still end up in individual files in `~/.local/state/bap/`. I also tried removing our call to `Bap.Std.Log.start` which was happening before the call to `Bap_main.init`. This seems to have no effect (this is why I'm guessing `Bap.Std.Log.start` might be obsolete).

This is strange so I'm going to try simpler tests to confirm.

**Comment by mjambon** [comment]
Nevermind, the redirection works. Clarification on the status of `Bap.Std.Log.start` would be appreciated, though.

**Comment by mjambon** [comment]
For everyone's benefit, here's our code to create a formatter that wraps bap's output into our own log format (omitted):
```ocaml
let formatter =
  (* persistent, extensible buffer *)
  let buf = Buffer.create 5000 in
  let output data pos len =
    Buffer.add_substring buf data pos len
  in
  let flush () =
    let msg = Buffer.contents buf in
    Buffer.reset buf; (* will reclaim memory iff buffer was extended *)
    log_line msg
  in
  Format.make_formatter output flush
```
The `log_line` function above takes a newline-terminated string and does what we want with it.

**Comment by ivg** [comment]
You can just do 
```ocaml
let ppf = make_formatter (fun s p n -> log_line (String.sub s p n)) ignore
```

If you worry about the performance of the logging, then you can provide an efficient `sub` function, that won't copy a string if the range designates the whole string, e.g.,
```ocaml
let sub_sharing s p n = 
  if p = 0 && n = String.length s then s else String.sub s p n
```

You will still get most of the time, if not always, `0` and the length of the string, so it will just pass the string. 

For your information, you can use the lower-level interface of the logging system, via the [Event][1] module of the Bap.Std interface (which was always available, even before 2.0 and 1.0). The lower level interface let's you filter messages based on their importance and source, and gives you more options on formatting the output. 

```ocaml
open Bap_future.Std
open Bap.Std

let () = Stream.observe Event.stream @@ function
  | Event.Log.Message {level; section; message} -> log_line message 
  _ -> ()
```
[1]: http://binaryanalysisplatform.github.io/bap/api/odoc/bap/Bap/Std/Event/index.html


> Nevermind, the redirection works. Clarification on the status of Bap.Std.Log.start would be appreciated, though.

When you use it a big fat warning is issued:
```
The deprecated Bap.Std.Log.start function is used. This function does nothing. Use `Bap_main.init' instead.
```

**Comment by mjambon** [comment]
ok, so I did it wrong. The concern is that our `log_line` function must insert a prefix at the beginning of each line and not in the middle of a line. So, if it receives `"hello\nwo"`, it should print something like `"[DATE] hello\n" and buffer up the broken line `"wo"` until a newline character is received. Or something along these lines.

**Comment by ivg** [comment]
In general, we try to post small messages one line per message, but we do not enforce this, so if someone posts a long message with newlines it will go in the log with one prefix only.  It is easy to do though, e.g.,
```ocaml
let prefix ~pre str = 
  String.split_on_char '\n' str |> List.map (fun s -> pre ^ "> " ^ s) |> 
  String.concat "\n";;
```

Besides, if you don't like how your prefix combines with BAP prefixes, you can opt to the lower level interface and build the prefix from scratch.
