### ISSUE TITLE
add a doc builder

### ISSUE THREAD

**Issue by ivg** [BinaryAnalysisPlatform/bap#1068]
Our documentation site is always lagging behind as updating the docs is a non-trivial task that has to be automated. Setting up the Travis job for building wouldn't be trivial (we probably won't fit into the time constraints), but we can use GitHub actions and host a documentation builder on one of our servers. We shall update both bap documentation and Primus Lisp docs.

**Comment by XVilka** [comment]
Related: https://github.com/BinaryAnalysisPlatform/bap/issues/981

**Comment by ivg** [comment]
Yep, @gitoleg is on it also.

**Comment by gitoleg** [comment]
fixed in https://github.com/BinaryAnalysisPlatform/binaryanalysisplatform.github.io/pull/6
