### ISSUE TITLE
No Indirect Jump Edges?

### ISSUE THREAD

**Issue by bin2415** [BinaryAnalysisPlatform/bap#1072]
Hi, I use `rawcfg` plugin referenced [here](https://github.com/BinaryAnalysisPlatform/bap/issues/878) to extract cfg.

However, I didn't find edges of indirect jumps in the cfg output. So I am asking here to check if bap solves `indirect jumps` when disassembling? If so, how can I print their edges?

### environments
- bap-2.0
- ubuntu-18.04

The command that outputs cfg is ```bap [executable] -drcfg```

Thanks!

**Comment by ivg** [comment]
Hi @bin2415, an unresolved indirect jump doesn't have a known destination therefore we can't create an edge from it (as we obviously need two nodes to create an edge). You can find the unresolved edges in the IR output, they will look as calls (as when an edge is unresolved we can't assume that it is local), e.g.,

```pascal
00000d1a: 
00000d1f: R4 := R4 + 1
00000d27: R3 := mem[R5 + 4, el]:u32
00000d2a: R5 := R5 + 4
00000d31: R0 := R7
00000d38: R1 := R8
00000d3f: R2 := R9
00000d47: LR := 0x88D4
00000d4b: call R3 with return %00000d4d
```

To get the IR output use `-dbir` (or just `-d` as it is the default output).

**Comment by bin2415** [comment]
Great!

One more question, does bap solve these indirect jumps when disassembling?

**Comment by ivg** [comment]
The short answer is no. 

Long anwer. There is a [VSA plugin][1], so that you can enable this, and even a paper that compares angr's and bap's VSA implementations, which you might find useful. 

[1]: https://github.com/draperlaboratory/cbat_tools/tree/master/explicit_edge
[2]: http://tyconmismatch.com/papers/nfm2019_bap_angr.pdf

**Comment by bin2415** [comment]
Thanks!
