### ISSUE TITLE
ARMv8 (64bit) architecture support

### ISSUE THREAD

**Issue by XVilka** [BinaryAnalysisPlatform/bap#1087]
I know it will require the external contributor to step in, adding here just for the tracking purpose.

Along with [Thumb mode support](https://github.com/BinaryAnalysisPlatform/bap/issues/951) ARMv8 64bit uplifting is the crucial missing part for the modern embedded and mobile reverse engineering and program analysis.

Due to changed architecture of the BAP, it would require skipping the step of generating IL and producing the Core Theory facts about each instruction or a higher level construct for the Knowledge Base.

See also [BinCat](https://github.com/airbus-seclab/bincat/tree/master/ocaml/src/disassembly) implementation of this architecture (I know the principles are completely different but can be helpful as an introduction to this architecture uplifting)

**Comment by ivg** [comment]
See #1141
