### ISSUE TITLE
Enable support for windows pdb files

### ISSUE THREAD

**Issue by bin2415** [BinaryAnalysisPlatform/bap#1089]
Hi, I want to train bap-byteweight with some windows binaries. And I found that there is an option `bap-byteweight train` option to train `bap-byteweight` with new binaries. But I'm not sure how to pass ground truth files to `bap-byteweight`.

Thanks in advance!

**Comment by bin2415** [comment]
Yeah, But I have separate `pdb` files that contain debugging information.

**Comment by bin2415** [comment]
No. It does not output any symbol.

**Comment by ivg** [comment]
Gotcha, can you, please, upload an archive with the binary and pdb here, so that we can debug it here? I don't have msvs nearby :)

**Comment by bin2415** [comment]
The binary and pdb is attached.
[Archive.zip](https://github.com/BinaryAnalysisPlatform/bap/files/4429674/Archive.zip).

Is it because I compiled the binary in windows and ran bap in linux so the bap can't find the proper path of `pdb` file?

**Comment by ivg** [comment]
I believe it's because we've never tried the new bap-byteweight tool with pdb files before, so no surprises it didn't work out of the box. We will try to enable support for them, before the 2.1 release.

**Comment by bin2415** [comment]
Great! Looking forward to the new feature, thanks!
