### ISSUE TITLE
bap-mc show-size flag

### ISSUE THREAD

**Issue by icemonster** [BinaryAnalysisPlatform/bap#1091]
Shouldn't this:
`bap-mc "\x68\x00\x00\x00\x00\xe9\xe0\xff\xff\xff" --show-insn --show-size`

also print the size of the instructions?

I remember that this worked in previous versions but now it just prints:
 ```
PUSH64i32(0x0)
JMP_4(-0x20)
```

**Comment by ivg** [comment]
Hmm, works for me:
```
$ bap-mc "\x68\x00\x00\x00\x00\xe9\xe0\xff\xff\xff" --show-insn --show-size
0x5
PUSH64i32(0x0)
0x5
JMP_4(-0x20)
```
which version of bap are you using?

**Comment by icemonster** [comment]
```
$ bap-mc --version
2.0.0
```

**Comment by icemonster** [comment]
Tried to install the latest .deb release in a fresh machine and can confirm.

```
$ wget https://github.com/BinaryAnalysisPlatform/bap/releases/download/v2.0.0/bap_2.0.0.deb
$ sudo dpkg -i bap_2.0.0.deb 
[sudo] password for cleansys: 
Selecting previously unselected package bap.
(Reading database ... 112982 files and directories currently installed.)
Preparing to unpack bap_2.0.0.deb ...
Unpacking bap (2.0.0) ...
Setting up bap (2.0.0) ...
$ sudo apt-get install -f
Reading package lists... Done
Building dependency tree       
Reading state information... Done
0 upgraded, 0 newly installed, 0 to remove and 16 not upgraded.
$ bap-mc --version
2.0.0
$ bap-mc "\x68\x00\x00\x00\x00\xe9\xe0\xff\xff\xff" --show-insn --show-size
PUSH64i32(0x0)
JMP_4(-0x20)
```

**Comment by ivg** [comment]
Indeed, it was broken in 2.0.0, I forgot it, was fixed in #1026 
The suggestion is to update to the latest master version, if you're using opam then just add

```
opam repo add bap-testing git://github.com/BinaryAnalysisPlatform/opam-repository#testing
```

It is better to create a new opam switch for the 2.1.0~alpha BAP, though you would, probably, still need one, as we have switched to newer versions of the compiler.

**Comment by icemonster** [comment]
Ohh ok.
I'm not using opam but I guess I'll give it a try.

Thank you for your time

**Comment by ivg** [comment]
you can grab the latest build from DockerHub also:
```
docker push binaryanalysisplatform/bap:testing
```

**Comment by icemonster** [comment]
You mean `docker pull` right?

**Comment by ivg** [comment]
yep, fixed)

**Comment by ivg** [comment]
I think we can close this issue, feel free to ask questions (I believe that will still get notifications on a closed issue, if not then poke me in the gitter)
