### ISSUE TITLE
symbols in MACH-O binaries are not demangled

### ISSUE THREAD

**Issue by jinwenhui93** [BinaryAnalysisPlatform/bap#1117]
I am trying to use bap to analyze the vulnerability on mach-o binaries, but meet some problems 

I compile the sample code as follows and compile them on Linux and Mac separately. 
for ELF all it works well ~ but for mach-o, the IR shows not exactly ~   

> #include <stdio.h>
#include <string.h>
#include <stdlib.h>
int main()
{
    char *p1;
    p1 = (char *) malloc(sizeof(char)*10);
    memcpy(p1,"hello",10);
    printf("p1 addr:%x,%s\n",p1,p1);
    free(p1);
    char *p2;
    p2 = (char *)malloc(sizeof(char)*10);
    memcpy(p1,"world",10);
    printf("p2 addr:%x,%s\n",p2,p1);
    return 0;
}

For example the memcpy function on ELF :  
> 00000906: sub memcpy(memcpy_dst, memcpy_src, memcpy_n, memcpy_result)
0000092a: memcpy_dst :: in out u64 = RDI
0000092b: memcpy_src :: in out u64 = RSI
0000092c: memcpy_n :: in u64 = RDX
0000092d: memcpy_result :: out u64 = RAX
000000f4: 
000000fa: call mem[0x200FC8, el]:u64 with noreturn

But on mach-o it shows : 
> 0000024e: sub ___memcpy_chk(___memcpy_chk_result)
00000255: ___memcpy_chk_result :: out u32 = RAX
00000008: 
0000000e: call mem[0x100002000, el]:u64 with noreturn

Other functions are similar ~  
Because of these problems, it also affects the accuracy and stability of the primus machine, as a result it can not recognize the UAF vulnerability well ~~~ 

Are there any solutions? which part of code should I analyze? 

[test-file.zip](https://github.com/BinaryAnalysisPlatform/bap/files/4762853/test-file.zip)

**Comment by ivg** [comment]
The symbols are not demangled correctly and automatically. In house, we rely on IDA Pro to do this for us, so it wasn't really noticed. In fact, we don't have any custom support, right now, for the Macho-O binaries, which we should provide. 

Concerning the `__memcpy_chk` it is the hardened version of memcpy which we can safely model with just `memcpy`. We shall either also rely on a demangler to turn it back into `memcpy` or add it as an alias to `memcpy` stub.

As an immediate mitigation, before we will implement a proper Macho-O abi support, it is possible to implement [a custom demangler][1] and use the `bap ./exe --demangle-with=my-custom-demangler`. 


[1]: 
https://binaryanalysisplatform.github.io/bap/api/master/bap-demangle/Bap_demangle/Std/index.html

**Comment by XVilka** [comment]
@ivg you might be interested in this library by @trufae https://github.com/radareorg/ldmg

**Comment by ivg** [comment]
> @ivg you might be interested in this library by @trufae https://github.com/radareorg/ldmg

Yeah, but it's GPL :(

**Comment by trufae** [comment]
it's GPL because most of the demangler's code is taken from binutils

**Comment by ivg** [comment]
yep and we're specifically moving away from binutils (which were used in bap 0.8), since then we had to rewrite all the code.

**Comment by trufae** [comment]
i would like to make my lib under the MIT or BSD license, and also get rid
of the binutils code because o that. The idea is to have a separate library
just for demangling (and eventually mangling), for everyone to use. So if
you want to contribute it will be good for everyone!

**Comment by jinwenhui93** [comment]
> The symbols are not demangled correctly and automatically. In house, we rely on IDA Pro to do this for us, so it wasn't really noticed. In fact, we don't have any custom support, right now, for the Macho-O binaries, which we should provide.
> 
> Concerning the `__memcpy_chk` it is the hardened version of memcpy which we can safely model with just `memcpy`. We shall either also rely on a demangler to turn it back into `memcpy` or add it as an alias to `memcpy` stub.
> 
> As an immediate mitigation, before we will implement a proper Macho-O abi support, it is possible to implement [a custom demangler](https://binaryanalysisplatform.github.io/bap/api/master/bap-demangle/Bap_demangle/Std/index.html) and use the `bap ./exe --demangle-with=my-custom-demangler`.

Thank you ~ I will try ~~ 
And one more questions,  the differences are not only about the function names but also about the parameter numbers and types ~ this also the demangle problem right?

**Comment by ivg** [comment]
Looks like it was fixed long time ago (probably when we rewrote our symbolization facilities). Anyways, can't reproduce anymore, 
```
$ bap UAF-Linux-easy -d | grep sub
00000ebc: sub .plt(\.plt_result)
00000ebd: sub __cxa_finalize(__cxa_finalize_result)
00000ebe: sub __do_global_dtors_aux(__do_global_dtors_aux_result)
00000ec0: call @sub_701 with noreturn
00000ec1: sub __libc_csu_fini(__libc_csu_fini_result)
00000ec2: sub __libc_csu_init(__libc_csu_init_result)
00000ec6: sub _fini(_fini_result)
00000ec7: sub _init(_init_result)
00000ec9: sub _start(_start_result)
00000ecb: sub deregister_tm_clones(deregister_tm_clones_result)
00000ece: sub frame_dummy(frame_dummy_result)
00000ecf: sub free(free_ptr)
00000ed0: sub main(main_argc, main_argv, main_result)
00000ed1: sub malloc(malloc_size, malloc_result)
00000ed2: sub memcpy(memcpy_dst, memcpy_src, memcpy_n, memcpy_result)
00000ed3: sub printf(printf_format, printf_result)
00000ed4: sub register_tm_clones(register_tm_clones_result)
00000ed7: sub sub_701(sub_701_result)
00000ef1: sub_701_result :: out u32 = RAX
00000ce0: sub __cxa_finalize:external(__cxa_finalize:external_result)
0000038a: sub __libc_start_main(__libc_start_main_main, __libc_start_main_arg2, __libc_start_main_arg3, __libc_start_main_auxv, __libc_start_main_result)
0000038f: sub special:hlt(special:hlt_result)
00000d5c: sub free:external(free:external_result)
00000da7: sub malloc:external(malloc:external_result)
00000d8e: sub memcpy:external(memcpy:external_result)
00000d75: sub printf:external(printf:external_result)
```
also works with objdump and radare2 disabled, e.g., with `--no-{objdump,radare}`
