### ISSUE TITLE
failure on elf32-littlearm 

### ISSUE THREAD

**Issue by ivg** [BinaryAnalysisPlatform/bap#1133]
While this architecture is not supported by BAP it would be nice if we wouldn't fail on it. So far it looks like that we got confused by the semantics of the last instruction at the end of the block, which is a thumb instruction (in fact two thumb instructions) which have an interpretation in ARM also. We are currently investigating if we can make the disassembler more robust to random inputs (we should), but in general the full support will be provided by #1122 

See https://github.com/fkie-cad/cwe_checker/issues/61 for more details.

**Comment by frakman1** [comment]
I read in the [overview](https://github.com/BinaryAnalysisPlatform/bap#overview) that:

> BAP supports x86, x86-64, ARM, MIPS, PowerPC

Is this not true for ARM and what exactly is elf32-littlearm (vs ARM)? I am unsure of the distinction.
