### ISSUE TITLE
problems with conf-binutils on Mac OS X

### ISSUE THREAD

**Issue by ivg** [BinaryAnalysisPlatform/bap#1154]
As our nightly builds indicate, we [have problems][1] with binutils on MacOS, most likely it's relevant to Homebrew and paths. 
[1]: https://github.com/BinaryAnalysisPlatform/bap/runs/821210540?check_suite_focus=true#step:7:559

**Comment by gitoleg** [comment]
fixed by https://github.com/ocaml/opam-repository/pull/16834
