### ISSUE TITLE
add more docker images and build them weekly

### ISSUE THREAD

**Issue by ivg** [BinaryAnalysisPlatform/bap#1162]
GitHub Action runners are preloaded with [several tons of software][1] so we can't be really sure that we didn't miss a dependency or that our scripts are portable enough, see #1160 for example. To enable installability to a vast majority of operating systems we can leverage github actions running docker builds on various base images. We can run them weekly (one OS per weekday, except Sunday, which is already running our weekly regression test). Here is the suggested list of operating systems (discussion is welcome, feel free to add your favorite OS here):

- [ ] Alpine
- [ ] Ubuntu Bionic
- [ ] Debian Testing
- [ ] Archlinux
- [ ] Fedora
- [ ] OpenSUSE

[1]: https://github.com/actions/virtual-environments/blob/ubuntu18/20200625.0/images/linux/Ubuntu1804-README.md

**Comment by XVilka** [comment]
Another crazy idea would be to also test FreeBSD - why not?
See 'sr.ht' for this kind of CI.
