### ISSUE TITLE
radare2 hangs bap on older distributions

### ISSUE THREAD

**Issue by ivg** [BinaryAnalysisPlatform/bap#1163]
In particular radare on xenial stops bap from working, other distributions are probably also having bugy radare2. We don't want to drop support of xenial as it is quite popular and its EOL is 2024. Possible solutions

1) check the radare2 version and don't call it if it is too old (@XVilka, can you give us an estimate which version should work?)
2) remove radare2 plugin from the `bap` metapackage and let people install it if they are sure

I also believe that option 1 should be implemented on the ocaml-radare2 site, because as far as I understood it is a protocol error, so R2 shall bail out with an unsupported protocol. 

See #1112 for more information.

**Comment by XVilka** [comment]
I opened an issue in Ubuntu regarding this, but as usually for Debian-based distributions it's ignored https://bugs.launchpad.net/launchpad/+bug/1882889
I will add version check in ocaml-radare2 package.

**Comment by ivg** [comment]
I wouldn't hope that xenial will be ever updated with the newer versions of radare2. Even if they will fix the issue it will take weeks before it will reach the docker images and probably years before it will reach the users (especially those kinds of users that prefer using Xenial). 

So the plan is the following. Right now we have removed bap-radare2 from the list of default bap packages (from the bap meta-package). We will wait until you add the version check to ocaml-radare2. I can do it myself, but I need a version. I can confirm that at least on 2.3.0 it works perfectly (on xenial it 0.9.6!) 

Once we have ocaml-radare2 fixed, we will bless bap-radare2 again. We will not try to install the deb packages for old versions but will issue a warning message with advice to a user on where to obtain the latest radare2).

**Comment by XVilka** [comment]
We can use 2.3.0 lower boundary, yes.

**Comment by ivg** [comment]
OK, I then submit a PR to ocaml-radare2, see you there :)

**Comment by ivg** [comment]
@XVilka, do not forget this PR also https://github.com/fxfactorial/ocaml-radare2/pull/10

**Comment by XVilka** [comment]
radare2.0.0.6 was published with necessary changes: https://opam.ocaml.org/packages/radare2/

**Comment by XVilka** [comment]
Let me know if more action required from my side.

**Comment by ivg** [comment]
@gitoleg, you can re-enable bap-radare2 as the part of the main bap distribution, but make sure that you update the constraint to `{= 0.0.6}` (we need to use an explicit dependency since ocaml-radare2 is beta and every new release may break the interface.

**Comment by ivg** [comment]
OK, radare2 is [back][1] and shining, thanks to everyone for your work

[1]: https://github.com/BinaryAnalysisPlatform/opam-repository/pull/49
