### ISSUE TITLE
`mov pc, lr` is unlifted

### ISSUE THREAD

**Issue by ivg** [BinaryAnalysisPlatform/bap#117]
ARM lifter doesn't handle this 
```asm
0e f0 a0 e1    mov pc, lr          ; MOVPCLR(0xe,Nil)
```

There is nothing special in it, so it can be added fairly easily. Volunteers are welcome!

**Comment by jaybosamiya** [comment]
This issue can be closed now, right?

**Comment by ivg** [comment]
sure!
