### ISSUE TITLE
[r] Cannot open '-cisj' error 

### ISSUE THREAD

**Issue by FactionCube** [BinaryAnalysisPlatform/bap#1203]
bap --version:  2.2.0-alpha+c9980f4

r2 -version
radare2 4.5.0-git 25187 @ linux-x86-64 git.4.4.0-434-g0955b27c9
commit: 0955b27c9ea961897cc7ba899457500930834510 build: 2020-07-17__22:00:54

opam config var conf-bap-llvm:package-version
10.0.0

I just upgraded bap to the version above and ran `git pull` on `bap-toolkit` to get the latest build, ran `make clean`, `make build`, and `make install` within the bap-toolkit folder.  When I run `bap /bin/true --recipe=primus-checks` from the bap-toolkit folder, or when I run `bap /bin/true --recipe=recipe.scm` from within the bap-toolkit/primus-checks folder, I get the following error (which I didn't have prior to downloading the latest bap version; it was working with the previous bap version from #testing):
```
[r] Cannot open '-cisj'
Failed to build the project:
(("Yojson.Json_error(\"Blank input data\")")
  "Raised at file \"common.ml\", line 5, characters 19-39\
 \nCalled from file \"plugins/radare2/radare2_main.ml\", line 53, characters 19-49\
 \nCalled from file \"plugins/radare2/radare2_main.ml\", line 70, characters 12-34\
 \nCalled from file \"lib/bap_future/bap_future.ml\", line 229, characters 14-29\
 \nRe-raised at file \"lib/bap_future/bap_future.ml\", line 231, characters 12-21\
 \nCalled from file \"list.ml\", line 110, characters 12-15\
 \nCalled from file \"lib/bap_future/bap_future.ml\" (inlined), line 181, characters 31-37\
 \nCalled from file \"lib/bap/bap_project.ml\", line 359, characters 4-34\
 \n")
```
Let me know if you require more system info.
Running on Ubuntu 18.04.

I can run this in utop with no problem:
```
utop # #require "radare2";;
utop # let result = R2.with_command_j ~cmd:"/j COLUMNS" "/bin/ls";;
val result : Yojson.t =
  `List
    [`Assoc
       [("offset", `Int 97717); ("type", `String "string");
        ("data", `String "eQUOTING_STYLECOLUMNSTABSIZEinvalid")];
     `Assoc
       [("offset", `Int 106743); ("type", `String "string");
        ("data", `String "onment variable COLUMNS: %signori")]]
```

**Comment by ivg** [comment]
Thanks for the report. Looks like it is connected with #1195, we will try to fix it today.

**Comment by ivg** [comment]
@FactionCube, could you please upload your `/bin/true`? I can't really reproduce it on my machine.

**Comment by FactionCube** [comment]
Here is my `/bin/true` 
[true.gz](https://github.com/BinaryAnalysisPlatform/bap/files/5055802/true.gz)
