### ISSUE TITLE
Support for memory corruption in Saluki

### ISSUE THREAD

**Issue by bgz25** [BinaryAnalysisPlatform/bap#1213]
Hello,

In the paper in which the Saluki plugin was introduced, it says that Saluki did not support memory corruption vulnerabilities. I'm wondering if that is still the case and if so, how come? 

If it is not implemented and it would be worthwhile (I'm not sure if other tools have since overtaken Saluki) I would be willing to try to do this. I am currently in my last semester of a master's degree and I have to do a capstone so I thought that this would line up well if it is reasonable. I'm quite new to all of this so I'm not sure if this is a realistic addition or not, but the paper says it would be a future area of work. 

Thanks!
Brian Gzemski

**Comment by XVilka** [comment]
Probably should be moved here https://github.com/BinaryAnalysisPlatform/bap-plugins
