### ISSUE TITLE
Support for memory corruption in Saluki

### ISSUE THREAD

**Issue by bgz25** [BinaryAnalysisPlatform/bap#1214]
Hello,

In the paper in which the Saluki plugin was introduced, it says that Saluki did not support memory corruption vulnerabilities. I'm wondering if that is still the case and if so, how come?

If it is not implemented and it would be worthwhile (I'm not sure if other tools have since overtaken Saluki) I would be willing to try to do this. I am currently in my last semester of a master's degree and I have to do a capstone so I thought that this would line up well if it is reasonable. I'm quite new to all of this so I'm not sure if this is a realistic addition or not, but the paper says it would be a future area of work.

Thanks!
Brian Gzemski

**Comment by ivg** [comment]
In fact, it is better to keep it in this repo) We keep missing issues in the bap-plugins repository. @bgz25, Saluki is indeed superseded by the new project called Primus and we indeed have a lot of ideas there for implementing, including memory corruption. If you're interested to do a capstone with BAP I am happy to help you. I am not sure that the issue tracker is the best tool for communication though, so I would suggest you to join our [Gitter](https://gitter.im/BinaryAnalysisPlatform/bap) channel.  Does it work for you?

**Comment by bgz25** [comment]
yes that works for me I will join the Gitter channel. Thanks!
