### ISSUE TITLE
bap collate is not working

### ISSUE THREAD

**Issue by FactionCube** [BinaryAnalysisPlatform/bap#1215]
bap --version: 2.2.0-alpha+c93b5d8

When I run:
    `bap collate bap:callgraph /bin/true /bin/echo`

I get this response:
    `bap: too many arguments, don't know what to do with 'bap:callgraph', '/bin/true', '/bin/echo'`

which is different from your example in gitter, which works correctly.   Am I running it correctly?

Kind regards to all BAP devs.

**Comment by ivg** [comment]
It is `bap compare ... ` not `bap collate` :)

**Comment by FactionCube** [comment]
Thank you Ivan.
