### ISSUE TITLE
lifting x86 rep instructions

### ISSUE THREAD

**Issue by percontation** [BinaryAnalysisPlatform/bap#124]
Some rep-prefixed instructions like `"\xf3\xab"` are producing `Failure "big_int_of_mode failure"` exceptions. I put a quick fix in c58416c9c that seems to work, but I don't know that it won't break something else.

**Comment by ivg** [comment]
I'll take a look, on a first glance looks correct. Thanks.

**Comment by ivg** [comment]
@feseal, would you mind to take a look at this problem? 
@percontation, could you please provide an example of failure? Like the particular string that contains the failing instruction, or at least a binary file, so that we can reproduce it.

**Comment by percontation** [comment]
The string `"\xf3\xab"` was doing it for me. It's in my /bin/ls.

**Comment by gitoleg** [comment]
@percontation
could you please send me your /bin/ls ?

**Comment by percontation** [comment]
http://drive.clockish.net/ls

**Comment by gitoleg** [comment]
@percontation
So, I can't reproduce this error on my x8664.
Maybe it occures only on 32-bit systems or something else goes wrong. 
And you use i386, don't you? Could you please provide us with all output you see?

**Comment by percontation** [comment]
@gitoleg
Okay, looked into it more. The problem was that I was using a 64-bit memory when lifting with i386. The following reproduces what I was seeing:

```ocaml
#use "topfind"
#require "core_kernel"
#require "bap"
#require "bap.plugins"
open Core_kernel
open Core_kernel.Or_error
let () = Bap_plugins.Std.Plugins.load () ; Bap_types.Std.(
	Bap_disasm_basic.create ~backend:"llvm" (Arch.to_string `x86) >>= fun dis ->
	Bap_memory.create Bap_common.LittleEndian (Addr.of_int64 0L) (Bigstring.of_string "\xf3\xab") >>= fun mem ->
	Bap_disasm_basic.insn_of_mem dis mem >>= function
		| (_, None, _) -> error_string "No instruction."
		| (_, Some insn, _) -> Bap_disasm_x86_lifter.insn `x86 mem insn
) |> ( function
		| Result.Ok bil -> Bap_bil.sexp_of_bil bil |> Core_sexp.to_string
		| Result.Error e -> Error.to_string_hum e
) |> fun s -> print_string @@ s^"\n"
;;
```

So, perhaps the i386 disassembler and lifter should throw an error when someone tries to call them with a 64-bit wide Memory object?

**Comment by ivg** [comment]
Well, in general we can't raise an error here, since we must take whatever user provides as granted. We don't have any information about the binary data, and it is user's responsibility to give us correct architecture. What concerning the wideness of the provided address, we can indeed make a sanity check that the width of address is equal `Arch.addr_size arch`

**Comment by percontation** [comment]
Sure, I just meant that it'd be nicer for the lifter to say something earlier instead of `Failure "big_int_of_mode failure"` later :)

**Comment by percontation** [comment]
Also worth noting: it looks like bap_mc.ml makes the same mistake as I did in creating a 64-bit wide Memory regardless of architecture.

**Comment by ivg** [comment]
thanks, will fix it
