### ISSUE TITLE
x86 is missing dependency on Str library

### ISSUE THREAD

**Issue by grsnl** [BinaryAnalysisPlatform/bap#1284]
The x86 plugin uses the Str library

https://github.com/BinaryAnalysisPlatform/bap/blob/5cfc3e584ea32d6c0c33013e050fb1a1e8f260de/plugins/x86/x86_legacy_bil_ast.ml#L71-L80

but doesn't declare a dependency on the Str library which can cause Dynlink errors loading the plugin.

This mistake is hidden when the elf plugin is available since it depends on bitstring which in turn depends on str and seems to be loaded (always?) before the x86 plugin.

**Comment by ivg** [comment]
Ouch, thanks for catching this! And yes, plugins are loaded in the alphabetic order, so indeed x86 is loaded probably the last. The fix is already in CI.
