### ISSUE TITLE
bap-objdump --use-ida should save the symbols so it could reuse them later without --use-ida

### ISSUE THREAD

**Issue by dluchaup** [BinaryAnalysisPlatform/bap#132]
It would be useful if "bap-objdump exe -l..... --use-ida" had the option to save the IDA provided information, so that at subsequent calls --use-ida would not be required.

**Comment by ivg** [comment]
as a workaround, you can run the following script in the IDA python REPL:
```python
from idautils import *
with open('symbols.scm', 'w+') as out:
    for ea in Segments():
        fs = Functions(SegStart(ea), SegEnd(ea))
        for f in fs:
            out.write ('(%s 0x%x 0x%x)\n' % (
                GetFunctionName(f),
                GetFunctionAttr(f, FUNCATTR_START),
                GetFunctionAttr(f, FUNCATTR_END)))
```
and it will store symbols into `symbols.scm` file, that can be loaded into `bap-objdump` with `-s` flag.

**Comment by ivg** [comment]
@tiffanyb, that is in the continuation of the yesterday talk.

**Comment by ivg** [comment]
@tiffanyb, It looks like that with the latest improvements it will be easy to do, will you?

**Comment by tiffanyb** [comment]
copied that.
