### ISSUE TITLE
Feature request: upper bounds on BIL while loops

### ISSUE THREAD

**Issue by percontation** [BinaryAnalysisPlatform/bap#133]
When using a while loop to model the semantics of a processor instruction, it's always the case that there's an upper bound on the number of possible iterations on that while loop (because processors don't have unbounded loops, and things like `rep` instructions are modeled as a jump-back-to-self).

It would be nice if lifters could provide this integer upper bound, as a property BIL While statements they generate. (For example, a lifter using a while loop for  `ffs`, `clz`, and similar instructions would attach the register width to their while statements).

This would be valuable to symbolic execution and related analyses which will usually want to immediately unroll BIL while loops. Currently, an analysis can just unroll loops 64 or 65 times and assume that it's safe, but

    1. If vector instruction support gets implemented with while loops, 64 might stop being large enough.
    2. It'd be nice to unroll the minimum number of times necessary.

**Comment by ivg** [comment]
Well, I would be glad to remove this `while` loops at all, they (maybe) make easier to write lifters, but writing analysis is very hard. I've grepped the code base, there're two cases where it is used. One is (actually buggy, see #134) can be easily removed. Another, that is used to represent CLZ instruction,  is a little bit harder:

```ocaml
      Stmt.move shift (exp_of_op src);
      Stmt.move accum (int32 32);
      Stmt.While (var shift <> int32 0, [
          Stmt.move shift (var shift lsr int32 1);
          Stmt.move accum (var accum - int32 1);
        ]); 
     Stmt.move (Env.of_reg dest) (var accum);
```

or in  a pseudo code:

```python
   def clz(dst, src, cond):
      if cond:
        shift = src
        acc = 32
        while (shift != 0):
           shift = shift >> 1
           acc = acc  - 1
       dst = acc
```

If we can find out how to encode this instruction without the while loop, I will rise a question about removing the while loop at all.

**Comment by ivg** [comment]
actually this [SO thread](http://stackoverflow.com/questions/2589096/find-most-significant-bit-left-most-that-is-set-in-a-bit-array) gives us a plenty of solutions that doesn't involve loops

**Comment by ivg** [comment]
Looks like, that we have another significant usage of the `while` loops: `rep*` instruction in x86. Any ideas how to bound it?

In general I see bounding in a following way, we should disallow arbitrary expressions in `while` loop, but instead introduce several looping constructs, like `for bits in word` for example. But how to solve repn in this case, I have no idea. Something like `for bytes in mem`...

**Comment by percontation** [comment]
Well, the current x86 lifter models `rep` instructions as jumping back to themselves when `rcx > 0` or whatnot. This means that `rep`s become a 1 instruction basic block, which is nice because indeterminate loops are already handled at the basic-block level anyways. (Intel's stuff like PIN treats `rep` instructions like this too!)

**Comment by ivg** [comment]
Afaik, while loop was introduced in the BIL especially for this purpose, to substitute this one instruction BB with the while construct... It is just not updated yet, but if we will stick to the jump solution there is indeed. o reason to have whiles at all. @maurer, can we hear your opinion?

**Comment by maurer** [comment]
Sorry, I didn't see this until just now - in an ideal world, while should be used only to express looping within an instruction, and so it should be possible to put bounds on uses.

Rep* is a case where while explicitly should not be used, and trying to add bounds to while loops might be a good way to find cases like this where while was being abused.

The theory behind while is that it can be used to represent microcode-tier control flow. Each instruction in the CPU takes a bounded amount of time to run, and so each of these pieces of control flow should be bounded as well. The rep prefixes in this world are interpreted as they are in microcode - re-executing the instruction, so that the instruction has been executed many times, rather than doing more work to execute the one instruction.
