### ISSUE TITLE
bap-llvm broken on Arch llinux dockerfile

### ISSUE THREAD

**Issue by StarGazerM** [BinaryAnalysisPlatform/bap#1334]
as title . when I build  docker image using dockerfile under docker/arch folder, following error pops:
```
[ERROR] The compilation of conf-bap-llvm failed at "/home/bap/.opam/4.09.1/bin/ocaml unix.cma find-llvm.ml".

```

**Comment by larkwiot** [comment]
You probably need to point opam at your LLVM config manually--the wiki has a note about how to do so under the installation section.

**Comment by ivg** [comment]
Fixed in https://github.com/BinaryAnalysisPlatform/opam-repository/commit/451cbe419320a35392695571a864a57ea924eabb
