### ISSUE TITLE
Discrepancy between some llvm and ghidra output for armeb

### ISSUE THREAD

**Issue by FactionCube** [BinaryAnalysisPlatform/bap#1335]
I was happily creating assembler output using `bap` when I noticed that `mov` statements using `--arm-backend=llvm` did not match those I was seeing in `ghidra` or Ida Pro.  I can recreate the issue here now that you have nicely set up a backend for `ghidra`.   

I note that `add` instructions seem unaffected.    I haven't noticed any other instructions deviating between `llvm` and `ghidra`.

Some samples:

```
bap mc --show-insn=asm --show-bil --arch=armeb -- e63da0e3
mov r3, #14720
{
  R3 := 0xDE6
}

bap mc --show-insn=asm --show-bil --arch=armeb --arm-backend=ghidra -- e63da0e3
mov r3,#0x3980
{
  bap:label(%00000009)
  u11904 := 0
  bap:label(%0000000a)
  u12032 := 0
  bap:label(%0000000b)
  u12160 := extract:7:0[u12032] & extract:7:0[CY]
  bap:label(%0000000c)
  u12288 := 1
  bap:label(%0000000d)
  u12416 := u11904
  bap:label(%0000000e)
  u12544 := extract:7:0[u12288] & extract:7:0[u12416]
  bap:label(%0000000f)
  shift_carry := extract:7:0[u12160] | extract:7:0[u12544]
  bap:label(%00000010)
  R3 := 0x3980
  bap:label(%00000011)
  tmpNG := R3 <$ 0
  bap:label(%00000012)
  tmpZR := R3 = 0
  bap:label(%00000013)
  tmpCY := extract:7:0[shift_carry]
  bap:label(%00000014)
  tmpOV := extract:7:0[OV]
}
```

and for `add`, which I include just for comparison:

```
bap mc --show-insn=asm --show-bil --arch=armeb -- e60d80e2
add r0, r0, #14720
{
  R0 := R0 + 0x3980
}


bap mc --show-insn=asm --show-bil --arm-backend=ghidra --arch=armeb -- e60d80e2
add r0,r0,#0x3980
{
  bap:label(%00000009)
  u11904 := 0
  bap:label(%0000000a)
  u12032 := 0
  bap:label(%0000000b)
  u12160 := extract:7:0[u12032] & extract:7:0[CY]
  bap:label(%0000000c)
  u12288 := 1
  bap:label(%0000000d)
  u12416 := u11904
  bap:label(%0000000e)
  u12544 := extract:7:0[u12288] & extract:7:0[u12416]
  bap:label(%0000000f)
  shift_carry := extract:7:0[u12160] | extract:7:0[u12544]
  bap:label(%00000010)
  #4 := R0
  #6 := #4 + 0x3980
  tmpCY := extract:7:0[extract:31:31[#4] & ~extract:31:31[#6]]
  bap:label(%00000011)
  #1 := R0
  #3 := #1 + 0x3980
  tmpOV := extract:7:0[~extract:31:31[#1] & extract:31:31[#3]]
  bap:label(%00000012)
  R0 := R0 + 0x3980
  bap:label(%00000013)
  tmpNG := R0 <$ 0
  bap:label(%00000014)
  tmpZR := R0 = 0
}

```

All the best to Team BAP.

**Comment by ivg** [comment]
Thanks for the nice example that actually justifies why we are not yet using Ghidra as the default backend :) Before delving into details, let's state it clearly - both outputs are correct and semantically equivalent, so there are no bugs here. And to make the code generated by the Ghidra backend more readable, when you disassemble a file, it is recommended to use the `--optimization-level=3` command-line option. This will remove the dead-code and propagate constants. 

The code generated by Ghidra is much more verbose and less optimized, or not optimized at all. Ghidra itself handles this by applying a series of optimization passes during the decompilation. Unfortunately, there is no publically available interface that will operate on the p-code level and they are run during the decompilation on the subroutine level, which doesn't suit us and we have to rely on our own optimizations. Which is fine, I think. We might also improve our Primus Lisp optimizer which can leverage the fact that all those blocks came from the same instruction and perform simple code elimination in cases when there is no intra-instructional control flow. I will look into this, but to summarize, this is what we get :)

**Comment by FactionCube** [comment]
I realise that, by posting all the details from the `bap` output, I have inadvertently obscured the discrepancy I wanted to point out.   I was really thinking about the value of the immediate operand in the op-codes. 

For the `llvm` backend:

```
mov r3, #14720
{
  R3 := 0xDE6
}
```

versus  the `ghidra` backend:

```
mov r3,#0x3980
{
...
  R3 := 0x3980
...
}
```

I was concerned about the `0xde6` value differing from `#14720` (i.e. `0x3980`).   

I did try consulting the ARM Manual, dissembling the `add` op-code down to it's bit-wise constituents using some random ARM table I found, and I can get `0xde6` if I evaluate the bits within the op-code which lie to the right of the `r0 r0` bits in the op-code, but, being a neophyte at divining the meaning of ARM instruction encoding, I figure that I am overlooking something.

What do you think?

Thank you for the optimization tip, it's worth keeping in mind.

**Comment by ivg** [comment]
Ah, I see. I was focusing on the add example and didn't look carefully at the first. So indeed it looks like that the llvm armeb disassembler is much more broken than we used to think. Probably, we should switch to Ghidra as default for armeb as it is better to deal with extra noise rather than with incorrect semantics. And fixing llvm is definitely not in our scope.

**Comment by FactionCube** [comment]
Thank you, Ivan.  I will switch to the ghidra backend.
