### ISSUE TITLE
Monad Transformer Stack

### ISSUE THREAD

**Issue by addap** [BinaryAnalysisPlatform/bap#1354]
Hi,

I was wondering how to compose multiple monad transformers from your transformer library.
I'm using version 2.3.0 from opam.

The naive approach does not work
```
open Monads.Std
module R = Monad.Reader.Make(struct type t = string end)(Monad.Ident)
module SR = Monad.State.Make(struct type t = string end)(R)
```
because R is missing a definition for type t, so it does not conform to the Monad signature.

I saw in ogre.ml that you can hack around this by defining t in a new module 
https://github.com/BinaryAnalysisPlatform/bap/blob/51b4988a1ee154922a81e8a98acb8fc8661f54f1/lib/ogre/ogre.ml#L808-L813

But that is not mentioned in the docs as far as I can tell. So is that the recommended way to build a monad transformer stack using this library?

**Comment by ivg** [comment]
@addap, are you satisfied with an answer? Maybe you have any suggestions on how we can improve it? Starting from documentation and ending in implementing, `MakeT` for each monad that will make compositions easier? PRs are very welcome!
