### ISSUE TITLE
Can the tool perform dynamic taint analysis？

### ISSUE THREAD

**Issue by wjcif11** [BinaryAnalysisPlatform/bap#1368]

**Comment by ivg** [comment]
Yes, we have the dynamic (using micro-execution) taint analysis engine, you can run it on an executable `./exe` with
```
bap ./exe --run --run-system=taint-analyzer
```

The analyzer will run the binary using microexecution and propagate taint. You can define your own policies (aka analysis), using Primus Lisp. Some of the example policy specifications (for you to get the general idea) could be found [here][1] or [here][2]. You're welcome to join our [Gitter][3] channel for more in-depth and detailed discussion. 


[1]: https://github.com/BinaryAnalysisPlatform/bap/blob/master/plugins/primus_taint/lisp/taint-sources.lisp
[2]: https://github.com/BinaryAnalysisPlatform/bap-toolkit
[3]: https://gitter.im/BinaryAnalysisPlatform/bap

**Comment by lkpama** [comment]
I want to get the system call graph of the executable. Is this option available？I know -dcallgraph can get the call graph.

**Comment by ivg** [comment]
See also https://github.com/BinaryAnalysisPlatform/bap/wiki/Using-BAP-for-Taint-Analysis
