### ISSUE TITLE
windows

### ISSUE THREAD

**Issue by 1429178646** [BinaryAnalysisPlatform/bap#1383]

**Comment by 1429178646** [comment]
I am a rookie, and could I use it in pycharm for windows?Thank you

**Comment by ivg** [comment]
You can use it via WSL or docker containers. Or you can install a VM and use it from VM. Installation on windows should be possible but is not currently supported and #1254. See also https://github.com/BinaryAnalysisPlatform/bap/wiki/Running-Bap-from-WSL-with-IDA-Pro-on-Windows-10

And feel free to drop by our gitter channel if you got stuck https://gitter.im/BinaryAnalysisPlatform/bap
