### ISSUE TITLE
examples in the documentation

### ISSUE THREAD

**Issue by acidzomb** [BinaryAnalysisPlatform/bap#147]
Hi there, 
I have followed every step in the documentation and successfully installed bap-0.9.5.
But when I wanted to try the example using baptop or top-level, I kept getting
errors like
let d = disassemble_file "ls";;
val d : disasm Bap_memory.With_error.m = 
Core_kernel.Result.Error ("Unix.Unix_error(Unix.ENOENT, \"open\", \"ls\")")
or 
let d = disassemble_file "/bin/ls";;
val d : disasm Bap_memory.With_error.m = Core_kernel.Result.Ok <abstr> 

Could you guide me please?
Thank you~

**Comment by ivg** [comment]
The first error just says that there is not such file as "ls" in your current working folder. The second code snippet, doesn't contain any errors, look at big and shiny `Core_kernel.Result.Ok` 

`disassemble_file` returns result wrapped into `Or_error.t` variant. Look [here](https://realworldocaml.org/v1/en/html/error-handling.html) for more information about this. You may also use `disassemble_file_exn` that returns results of disassembling without wrapping.
