### ISSUE TITLE
Version 2.4 is missing at docker hub

### ISSUE THREAD

**Issue by Cryspia** [BinaryAnalysisPlatform/bap#1474]
The tags provided at [docker hub](https://hub.docker.com/r/binaryanalysisplatform/bap/tags) do not include version 2.4, which is the latest release. Could you upload the missing versions?

**Comment by ivg** [comment]
We don't have automation for this but I can do it manually.  Besides, you can use the `latest` tag to get the latest built version of BAP. Is there any specific reason why you're looking for 2.4.0?

**Comment by Cryspia** [comment]
The reasons that we need a release tag are:
1. When doing a research, we usually decide a date and pick the latest release before that date.
2. If we create another dockerfile inherited from your dockerfile for any purposes, we want a stable version tag instead of the `latest` to guarantee reproducibility.
