### ISSUE TITLE
interact with other disassembler

### ISSUE THREAD

**Issue by acidzomb** [BinaryAnalysisPlatform/bap#148]
Hi there,
Sorry to bother again~
Could you please tell me how to leverage bap to lift the output of other disassemler to bil.
Which api should I use please? 
Because normally we may use IDApro to disassembly large executables or windows PE files.
The input for bap is like "push ebp; mov ebp,esp".
I guess the binary input is better, like "0x55,0x8b,0xec"
I know I should look into the source code, but for now I am really not familiar with ocaml:(
Thank you so much~~

**Comment by ivg** [comment]
Well, first of all, BAP can't lift assemble code, only binary.  You can use `disassemble` function, that takes a memory and performs lifting and disassembly. Here is a function that can help you to create a memory from string:
```ocaml
  let mem_of_string s = Bigstring.of_string s |>
            Memory.create LittleEndian (Addr.of_int64 0L) |>
            ok_exn in
```

You can use it like this: 
```ocaml

  let mem = mem_of_string "\xc3"`
  let disasm = disassemble `x86_64 mem
  let bil = Seq.(Disasm.insns >>| snd >>| Insn.bil |> to_list) |> List.concat
```

**Comment by acidzomb** [comment]
Thank you for your help. Really appreciate it.
I typed them in baptop, but it complained
 "This expression has type disasm -> (mem * insn) t
   but an expression was expected of type 'a t   "

**Comment by ivg** [comment]
a second try 
```
  let mem = mem_of_string "\xc3"`
  let disasm = disassemble `x86_64 mem |> ok_exn
  let bil = Seq.(Disasm.insns disasm >>| snd >>| Insn.bil |> to_list) |> List.concat
```

**Comment by dbrumley** [comment]
May I also suggest you look at the plugin system, and use bap-objdump --use-ida (which accepts an optional path to ida).   My (very early) workflow is renaming functions in idaq (be careful if you have both 64-bit and 32-bit versions installed; bap will use one and you may be using another), and then using bap to do analysis. The analysis then uses the renamed functions from ida.

**Comment by acidzomb** [comment]
I have to remove " ` " from " let mem = mem_of_string "\xc3"` " to stop the complain
Parse error: [a_ident] expected after "`" (in [expr])  
And then remove " |> ok_exn " from "  let disasm = disassemble `x86_64 mem |> ok_ex " to solve 
"This expression has type 'a Core_kernel.Or_error.t -> 'a but an expression was expected of type disasm -> 'b" error.

Then I can use the function, but the output is like
val bil : stmt list = [] 

I know I must have done something really stupid..

And definitely I will try use bap-objdump --use-id.
Thank you~

**Comment by ivg** [comment]
Oh, this wasn't a function, this was just three top-level statements, that can be evaluated in top-level. 
Here, I finally ran it in my toplevel (everything before the `;;` is what I input, everything after is the reply from REPL):

```
#   let mem = mem_of_string "\xc3"
  let disasm = disassemble `x86_64 mem
  let bil = Seq.(Disasm.insns disasm >>| snd >>| Insn.bil |> to_list) |> List.concat;;
    val mem : Bap.Std.Memory.t = 0000000000000000: c3 
val disasm : Bap.Std.disasm = <abstr>
val bil : Bap_bil.stmt Core_kernel.Std.List.t =
  [ra_112 := mem64[RSP, el]:u64; RSP := RSP + 0x8:64; jmp ra_112]
```

But, you may have different example, like empty set of instructions. Then you need to update to the latest `bap` out of trunk. We didn't make release for a very long time, there're 50 commits on top of the latest release. You can install the latest bap from a github using this `opam` command 

Warning: the following requires `opam` 1.2 or later, do not try if you have earlier version:
```
opam pin add bap git://github.com/BinaryAnalysisPlatform/bap
```

For more information, look [here](https://github.com/BinaryAnalysisPlatform/bap/wiki/Build-tips-and-tricks)

**Comment by acidzomb** [comment]
Ça marche!!! LOL!!!
I tried to use "opam pin add bap git://github.com/BinaryAnalysisPlatform/bap"
to upgrade bap-0.9.5 to bap-master, but it didn't work.
It kept complaining
"# File "lib/bap_disasm/bap_program_visitor.mli", line 10, characters 12-16:
# Error: Unbound type constructor tags
# Command exited with code 2."
Then I downloaded the newest source code form github, and used "./configure make 
make install" explicitly and then everything worked:)

Thank you soooo much for your patient help!!!
