### ISSUE TITLE
MMX registers incorrectly aliased to YMM:63:0

### ISSUE THREAD

**Issue by percontation** [BinaryAnalysisPlatform/bap#149]
The current i386 lifter lifts MMX registers as if they were aliases for the lower 64 bits of the SSE registers. However, they are not: they're actually aliases for the lower 64 bits of the FPU data registers.

e.g. `0F EF C0    pxor mmx0, mmx0` gets lifted to `YMM0 := YMM0:255:64 :: (YMM0:63:0 ^ YMM0:63:0)`, when it actually doesn't affect YMM0 at all. The expected result would be to throw an exception or generate a nop, since FPU data regs are currently unmodeled.

(I realize this will probably wait until the i386 lifter rewrite to get addressed, but thought it was good to note.)

**Comment by ivg** [comment]
we will resolve this issue later, when we will consider lifting floating points
