### ISSUE TITLE
bap-byteweight for multi signatures

### ISSUE THREAD

**Issue by tiffanyb** [BinaryAnalysisPlatform/bap#150]
We recently come across some testing binaries with conflict function start prefix with known function start prefix. e.g.

```
8080c27c <do_i2c_probe>:
8080c27c:       e3520002        cmp     r2, #2
8080c280:       e92d40f8        push    {r3, r4, r5, r6, r7, lr}
8080c284:       13e06000        mvnne   r6, #0
8080c288:       1a000005        bne     8080c2a4 <do_i2c_probe+0x28>
8080c28c:       e5930004        ldr     r0, [r3, #4]
8080c290:       e3a01000        mov     r1, #0
8080c294:       e3a02010        mov     r2, #16
8080c298:       eb010f78        bl      80850080 <simple_strtol>
...
```

In this case, function `do_i2c_probe` is started by `cmp r2 #2`, instead of `push` registers command. To address this issue, @ivg proposed that we identify function starts by multiple signatures, and choose the one with _highest_ accuracy.

To justify the accuracy for testing binaries, we use the identified `call` instructions to check how many the targets of call instructions are included in the function starts corresponding to signatures. And we adopt the result with most match.

**Comment by dluchaup** [comment]
I am not very familiar with how byteweight works, but note that
"cmp     r2, #2" could not usually be the beginning of a "standard" preamble.
It is likely that the compiler optimizer chose to move that 'cmp' instruction before the push
perhaps to save 'push' time or space (or to obfuscate). 
In my opinion, such instructions are very much function dependent, 
and including them in training may add noise.
Perhaps the following observation could be useful in addressing the problem.
Instructions that get added (hoisted) before the preamble
(1) cannot modify saved registers (unless the compiler is super sure that they don;t need to be saved).
(2) must define a value, memory or a flag used after the push (if there is a push)
     (otherwise they are dead code, and declaring other instruction the entry point should be
      OK for analysis)
In this case the instruction "mvnne   r6, #0"  must use a flag defined somewhere, so 
"cmp     r2, #2" is likely part of the function.

**Comment by ivg** [comment]
@dluchaup, with `Os` flag set arm-linux-gnueabi` compiler emits a tremendous amount of such functions.  And many times there is more than one comparisons in a row. But your observation is correct, the indeed do not define registers, other than flags.

**Comment by ivg** [comment]
I think we can close it, as soon as new signatures are uploaded.
