### ISSUE TITLE
Python Bindings for x86, x86_64 to BIL support.

### ISSUE THREAD

**Issue by ViktorMKa** [BinaryAnalysisPlatform/bap#153]
Currently using `insn.bil` returns `NoneType` when disassembling x86 & x86_64 executables. Since i want to operate on BIL via Python for my project in Data Flow Analysis, it would be great if that was added. 

Thanks in advance.

**Comment by ivg** [comment]
It is already done, but not released into opam. I will make a release on a next week. If you don't want to wait, just use current master branch. You can install it via opam using `pin` command:
```
 opam pin add bap git://github.com/BinaryAnalysisPlatform/bap
```

Since,  BAP is under heavy development right now, and moves rapidly it is anyway a good idea to use master branch, as a reference.  See our [wiki](https://github.com/BinaryAnalysisPlatform/bap/wiki/Build-tips-and-tricks), for more info, how to use `opam pin` command

**Comment by ViktorMKa** [comment]
Oh, okay great.

I just tried to pin & install it in a variety of ways, only to encounter the following errror repeatedly:
```
# opam-version 1.2.0
# os           linux
# command      make doc
# path         /home/viktor/.opam/system/build/bap.master
# compiler     system (4.02.1)
# exit-code    2
# env-file     /home/viktor/.opam/system/build/bap.master/bap-6327-a00279.env
# stdout-file  /home/viktor/.opam/system/build/bap.master/bap-6327-a00279.out
# stderr-file  /home/viktor/.opam/system/build/bap.master/bap-6327-a00279.err
### stdout ###
# ...[truncated]
[many lines of instructions with options]
# File "lib/bap_disasm/bap_program_visitor.mli", line 10, characters 12-16:
# Error: Unbound type constructor tags
# Command exited with code 2.
### stderr ###
# make: *** [doc] Error 1
```
Would appreciate any pointers to fixing this.

**Comment by ivg** [comment]
mine god, what a weirdy bug! I've accidentally commited a dead file. It would be ok, but when `ocamldoc` tried to compile documentation it managed to find it, and it failed to compile of course. I will fix this, soon, but you will need to wait about an hour before the CI check passes. Keep in touch, and thanks for reporting!

**Comment by ViktorMKa** [comment]
Hey, sorry for getting back to you so late, but big thanks for the fix, it works now. I wanted to ask if the SSA transformation of BIL is already part of the python bindings? Is there some kind of API for the Python Bindings? I've been playing around a bit, and learned a lot already.

**Comment by ivg** [comment]
Nope, SSA is not in the Python bindings, because it is not yet a part of BAP. What concerning API, then ipython `?` operator is very helpful. But maybe we indeed should generate them.

**Comment by ViktorMKa** [comment]
Oh okay. Is BAP being rewritten from scratch? I wonder since the features like SSA transformation and CFG generation were described in the BAP handbook from the CMU website, and apparently were a part of BAP at some point.

**Comment by ivg** [comment]
yep, totally from scratch. So beware of reading BAP handbook. Even BIL now is different.
