### ISSUE TITLE
Can bap analyze text assembly file?

### ISSUE THREAD

**Issue by ya0guang** [BinaryAnalysisPlatform/bap#1534]
As title, can `bap` take `.s` file as the input and output `bil`? Working with text assembly direclty can avoid disassembling.

**Comment by ivg** [comment]
Nope, BAP is not able to assemble files or work with the assembly input. It wouldn't be hard to add, actually, but it was never in the scope. If you're interested in adding this functionality, we will be happy to help you and provide some guidance.

**Comment by ivg** [comment]
Feel free to reopen if you want to work on it.
