### ISSUE TITLE
Issue with Camlzip 1.12

### ISSUE THREAD

**Issue by xavierleroy** [BinaryAnalysisPlatform/bap#1607]
For reasons explained in https://github.com/ocaml/opam-repository/pull/26207#issuecomment-2216901921 , Camlzip version 1.12 removes the `extra` field from type `Zip.entry`.  This breaks `lib/bap_byteweight/bap_byteweight_signatures.ml`:
https://github.com/BinaryAnalysisPlatform/bap/blob/95e81738c440fbc928a627e4b5ab3cccfded66e2/lib/bap_byteweight/bap_byteweight_signatures.ml#L103-L114

I suggest not trying to copy the extra data at all.

**Comment by ivg** [comment]
Thanks @xavierleroy and @bmourad01, closing the issue as fixed in #1609
