### ISSUE TITLE
StopIteration in bap.py

### ISSUE THREAD

**Issue by nedwill** [BinaryAnalysisPlatform/bap#173]
The simple example from the bap docs for the Python API triggers this failure:
```
>>> import bap
>>> print '\n'.join(insn.asm for insn in bap.disasm("\x48\x83\xec\x08"))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/bap/bap.py", line 87, in disasm
    return run(load_chunk(obj, **kwargs))
  File "/usr/local/lib/python2.7/dist-packages/bap/bap.py", line 96, in load_chunk
    return get_instance(**kwargs).load_chunk(s, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/bap/bap.py", line 294, in load_chunk
    return self._load_resource({'load_memory_chunk' : kwargs})
  File "/usr/local/lib/python2.7/dist-packages/bap/bap.py", line 327, in _load_resource
    rep = self.call(res).next()
  File "/usr/local/lib/python2.7/dist-packages/bap/bap.py", line 336, in jsons
    obj,p = dec.scan_once(r.text,p)
StopIteration
```

The request `r` in the `jsons` function has return status 200, but `r.text` is empty.
@ivg I suspected this bug was introduced in the recent BIL refactoring, but strangely it seems to occur on the release version 0.9.5 as well. I'm still investigating but perhaps this bug is caused by an update to a third-party library like requests or any of the JSON libraries on the Python or OCaml side.

**Comment by nedwill** [comment]
I noticed that running bap 0.9.5 and the latest master under Mac OS X Yosemite has the correct behavior. Maybe it's an Ubuntu problem?

**Comment by nedwill** [comment]
I found the regression - updating cohttp from 0.15.2 to 0.16.0 introduced the bug under Mac OS for me.

**Comment by ivg** [comment]
great investigation! Target locked, I will look at it today. Meanwhile as a workaround one can downgrade to a working version of cohttp with `opam install cohttp.0.15.2`

Thanks!

**Comment by ivg** [comment]
Just a clarification update, [RFC7231](https://tools.ietf.org/html/rfc7231) says that if GET method has a body, then the result is undefined. 
> A payload within a HEAD request message has no defined semantics;
   sending a payload body on a HEAD request might cause some existing
   implementations to reject the request.

So, they switched to ignoring bodies in request that has HEAD, GET and DELETE method. So, our switch to use POST method is perfectly valid and correct. Not a workaround anymore.
