### ISSUE TITLE
cant find  any   conversion utilities

### ISSUE THREAD

**Issue by Icefroge** [BinaryAnalysisPlatform/bap#185]
Hi,i finished install  bap on ubuntu-i386-14.04, then  use it  successfully  translation  ELF file  to BIL. But 
I does't find  any conversion utilities(such as , codegen:LLVM-based code generation). I want  to use bil  file to generate llvm bitcode which  could  be  analysis  by  symbolic execution(such as,klee or cloud9)

**Comment by ivg** [comment]
BAP doesn't output LLVM bitcode.
