### ISSUE TITLE
Can't find external tools (iltrans, codegen)

### ISSUE THREAD

**Issue by sciencectn** [BinaryAnalysisPlatform/bap#196]
Hello,
In the bap user guide it mentions a few external tools like iltrans and codegen: http://bap.ece.cmu.edu/doc/bap.pdf

I can't seem to find these in the source. I'm specifically interested in codegen, which the user guide says can generate LLVM IL. Thanks.

**Comment by ivg** [comment]
Hi,

You're reading documentation for the old BAP. This one is a complete rewrite, that doesn't have transformation to LLVM IR at that moment.
