### ISSUE TITLE
OS X needs `cp -R`

### ISSUE THREAD

**Issue by percontation** [BinaryAnalysisPlatform/bap#204]
The `["cp" "-r" "doc" bap:doc]` in ./opam will cause the install to fail on OS X, since `cp -r` is only aliased to `cp -R` for GNU stuff.

**Comment by ivg** [comment]
I'm not sure that I understand you. `cp -r` works for me on mavericks without any issues. Can you elaborate?

**Comment by percontation** [comment]
Yeah, looks like that got added and is not in fact the reason why the install fails.

**Comment by percontation** [comment]
Possibly because I'm installing from a pinned folder, but it's failing with `[ERROR] The compilation of mybap failed at "cp -r doc".` (because there's only one path supplied to `cp`, nothing to do with -r/-R)

**Comment by percontation** [comment]
Okay, yeah, nevermind. "bap:doc" isn't going to resolve to anything when I've pinned it to the name "mybap".

**Comment by percontation** [comment]
(I will say that -R is the POSIX compliant cp option, and I'm pretty sure `-r` hasn't worked on OS X until recently)

**Comment by ivg** [comment]
Ok, I will fix it to `-R`, being posixly correct is a good way to stay out of troubles. 
Btw, in the version, released to official opam, I removed doc building, since it doesn't work on older versions of OCaml. So it want cause any troubles for wide masses :)
