### ISSUE TITLE
BAP plugins cannot be called twice

### ISSUE THREAD

**Issue by dbrumley** [BinaryAnalysisPlatform/bap#227]
Given a plugin like:
```ocaml
open Core_kernel.Std
open Bap.Std
    
let main p = 
  Printf.printf "Hello world!\n";
  p

let () = Project.register_pass' "hello" main
```

I use to be able to call such a plugin twice, but now it appears to fail:
```
$ bap -l simplehello -l simplehello exe
(Invalid_argument "hello is duplicated")
```

**Comment by ivg** [comment]
Yes, this is intentional. Since there is a discuss label, I'm not closing the issue :) Why do you think that we need this feature?

**Comment by dbrumley** [comment]
I've not looked into the code that checks for duplicates, so I don't know exactly what is allowed and not allowed.  Suppose we have a plugin called `countsyms` that prints out the number of symbols, and a plugin called `recoversyms` that recovers additional symbols.  It seems reasonable to run:
```
bap -lcountsyms -lrecoversyms -lcountsyms 
```
to see how things changed.

**Comment by ivg** [comment]
Yes, there is a tradeoff, either we can have an automatic dependency loading, and thus the ability to state explicitly the dependencies between plugins or having the option to load the same plugin twice. 

Dependencies doesn't work well if we will allow duplicates: (1) we can't guarantee that under the same name is registered the same function, and thus we can't guarantee that we satisfied dependency correctly. (2) when we load a plugin we need to build a transitive closure of dependencies, and if we have duplicates it is quite unsound.

**Comment by dbrumley** [comment]
I don't have any data to support one way or another, so I don't have any preference at this point.
