### ISSUE TITLE
Memmap.lookup returns something unexpected

### ISSUE THREAD

**Issue by rvantonder** [BinaryAnalysisPlatform/bap#231]
When I perform `Memmap.lookup (Project.memory project) addr` on an `addr`, whose value is `0xFE24:32`, I get two pieces of memory back (see below). Both of these contain `0xFE24:32`, but really I only want to tag memory at `0xFE24`, not this whole thing. I also don't understand why I'm getting two memories.

The way I'm dealing with this now is to use one of the memories and then perform `Memory.view ~from:addr mem ~words:4` to 'trim' it, and then tag only the part I'm interested in. So my question reduces down to: what exactly does `Memmap.lookup` do? Why does it return two large ranges of memory in this case?

Binary is coreutils_O1_cat.

```
Addr: 0xFE24:32
Length Mem 1. 33488 -> size
Length Mem 2. 3092 -> size
```
```
Mem 1:
00008000  7F 45 4C 46 01 01 01 00 00 00 00 00 00 00 00 00 |.ELF............|
00008010  02 00 28 00 01 00 00 00 D0 91 00 00 34 00 00 00 |..(.........4...|
00008020  30 84 02 00 02 00 00 05 34 00 20 00 08 00 28 00 |0.......4. ...(.|
00008030  26 00 23 00 01 00 00 70 C4 82 00 00 C4 02 01 00 |&.#....p........|
00008040  C4 02 01 00 08 00 00 00 08 00 00 00 04 00 00 00 |................|
00008050  04 00 00 00 06 00 00 00 34 00 00 00 34 80 00 00 |........4...4...|
00008060  34 80 00 00 00 01 00 00 00 01 00 00 05 00 00 00 |4...............|
00008070  04 00 00 00 03 00 00 00 34 01 00 00 34 81 00 00 |........4...4...|
00008080  34 81 00 00 13 00 00 00 13 00 00 00 04 00 00 00 |4...............|
00008090  01 00 00 00 01 00 00 00 00 00 00 00 00 80 00 00 |................|
000080A0  00 80 00 00 D0 82 00 00 D0 82 00 00 05 00 00 00 |................|
000080B0  00 80 00 00 01 00 00 00 D0 82 00 00 D0 82 01 00 |................|
000080C0  D0 82 01 00 80 02 00 00 F4 07 00 00 06 00 00 00 |................|
000080D0  00 80 00 00 02 00 00 00 DC 82 00 00 DC 82 01 00 |................|
000080E0  DC 82 01 00 E8 00 00 00 E8 00 00 00 06 00 00 00 |................|
000080F0  04 00 00 00 04 00 00 00 48 01 00 00 48 81 00 00 |........H...H...|
00008100  48 81 00 00 44 00 00 00 44 00 00 00 04 00 00 00 |H...D...D.......|
00008110  04 00 00 00 51 E5 74 64 00 00 00 00 00 00 00 00 |....Q.td........|
00008120  00 00 00 00 00 00 00 00 00 00 00 00 06 00 00 00 |................|
00008130  04 00 00 00 2F 6C 69 62 2F 6C 64 2D 6C 69 6E 75 |..../lib/ld-linu|
00008140  78 2E 73 6F 2E 33 00 00 04 00 00 00 10 00 00 00 |x.so.3..........|
00008150  01 00 00 00 47 4E 55 00 00 00 00 00 02 00 00 00 |....GNU.........|
00008160  06 00 00 00 10 00 00 00 04 00 00 00 14 00 00 00 |................|
00008170  03 00 00 00 47 4E 55 00 07 3D 69 C9 88 48 AA 57 |....GNU..=i..H.W|
00008180  46 D3 43 2E A3 4A E1 53 8A 0F BE 7D 43 00 00 00 |F.C..J.S...}C...|
00008190  02 00 00 00 10 00 00 00 09 00 00 00 B2 C9 E2 80 |................|
000081A0  84 60 19 9A 00 28 82 CC 02 10 00 00 8A 00 43 5D |.`...(........C]|
...
00010290  00 00 00 00 00 00 00 00 00 00 00 00 6D 62 75 69 |............mbui|
000102A0  74 65 72 5F 6D 75 6C 74 69 5F 6E 65 78 74 00 00 |ter_multi_next..|
000102B0  6D 62 75 69 74 65 72 5F 6D 75 6C 74 69 5F 6E 65 |mbuiter_multi_ne|
000102C0  78 74 00 00 0C 8F FF 7F 01 00 00 00 00 00 00 00 |xt..............|
```

```
Mem 2:
0000F6B0  01 00 02 00 F8 FC 00 00 00 00 00 00 00 00 00 00 |................|
0000F6C0  62 00 00 00 08 FD 00 00 00 00 00 00 00 00 00 00 |b...............|
0000F6D0  6E 00 00 00 10 FD 00 00 00 00 00 00 00 00 00 00 |n...............|
0000F6E0  73 00 00 00 20 FD 00 00 00 00 00 00 00 00 00 00 |s... ...........|
0000F6F0  76 00 00 00 34 FD 00 00 00 00 00 00 00 00 00 00 |v...4...........|
0000F700  45 00 00 00 40 FD 00 00 00 00 00 00 00 00 00 00 |E...@...........|
0000F710  54 00 00 00 4C FD 00 00 00 00 00 00 00 00 00 00 |T...L...........|
0000F720  41 00 00 00 58 FD 00 00 00 00 00 00 00 00 00 00 |A...X...........|
0000F730  FE FF FF FF 60 FD 00 00 00 00 00 00 00 00 00 00 |....`...........|
0000F740  FD FF FF FF 00 00 00 00 00 00 00 00 00 00 00 00 |................|
0000F750  00 00 00 00 54 72 79 20 27 25 73 20 2D 2D 68 65 |....Try '%s --he|
0000F760  6C 70 27 20 66 6F 72 20 6D 6F 72 65 20 69 6E 66 |lp' for more inf|
0000F770  6F 72 6D 61 74 69 6F 6E 2E 0A 00 00 55 73 61 67 |ormation....Usag|
0000F780  65 3A 20 25 73 20 5B 4F 50 54 49 4F 4E 5D 2E 2E |e: %s [OPTION]..|
0000F790  2E 20 5B 46 49 4C 45 5D 2E 2E 2E 0A 00 00 00 00 |. [FILE]........|
0000F7A0  43 6F 6E 63 61 74 65 6E 61 74 65 20 46 49 4C 45 |Concatenate FILE|
...
00010270  25 35 30 73 20 25 35 30 73 00 00 00 00 1A 00 00 |%50s %50s.......|
00010280  EF FF FF FF FE FF FF FF FE FF FF 7F 00 00 00 00 |................|
00010290  00 00 00 00 00 00 00 00 00 00 00 00 6D 62 75 69 |............mbui|
000102A0  74 65 72 5F 6D 75 6C 74 69 5F 6E 65 78 74 00 00 |ter_multi_next..|
000102B0  6D 62 75 69 74 65 72 5F 6D 75 6C 74 69 5F 6E 65 |mbuiter_multi_ne|
000102C0  78 74 00 00                                     |xt..            |
```

**Comment by ivg** [comment]
So, first of all, I would like to clarify terminology. According to a bap parlance, memory (or `mem` for short) is just a piece of data. You may think of it as an array, that is indexed by virtual addresses. But unlike real arrays, memory is just an opaque view. So other way of thinking is to treat `mem` as an interval (and actually this is how it is implemented). 

Memory map (or `memmap`) is an associative data structure (also known as interval trees or interval map or segment tree) that associates this intervals with  some data. Intervals can overlap, dominate each other or even be equal. The following figure will give some idea, on how it looks like.

```
+----------------------------------------------------------------+
|+--------------------------------+    +-------------------+     |
|| +------------------+           |    |                   |  S  |
|| |                  |           |    |                   |  E  |
|| |          +-------+---------+ |    |                   |  G  |
|| |          |                 | |    |                   |  M  |
|| | SYMBOL 1 |    SYMBOL 2     | |    |     SECTION 2     |  E  |
|| |          |                 | |    |                   |  N  |
|| |          +-------+---------+ |    |                   |  T  |
|| |                  | SECTION 1 |    |                   |     |
|| +------------------+           |    |                   |  1  |
|+--------------------------------+    +-------------------+     |
+----------------------------------------------------------------+
0   1    2    3    4    5    6   7   8   9   A   B   C   D   E   F
```

It is simplified example, of course. Here we have the big chunk of memory marked as `segment 1` (i.e., with this memory region we associate a semantic information that it is a segment). We also have some subset of the segment marked as belonging to two different sections, namely `section 1` and `section 2`. Inside `section 1` we also have some portions of data split between to symbols, and some data is shared between to symbols. 

With a given example, address `4` belongs to 4 memory regions: it is a part of a `segment 1` and `section 1` and belongs to two symbols: `symbol 1` and `symbol 2`. On the other hand, address `8` 
 Belongs only to the `segment 1` , `B` belongs to 2 regions: the segment and and `section 2`.

In your particular case, you have to "memories", because this address is mapped to the section `.rodata` and second segment.  

You can always see the layout of the memory, by printing it:

```ocaml
let print_memory p =
  Project.memory p |> Memmap.to_sequence |> Seq.iter ~f:(fun (mem,x) ->
      printf "%s(%a)@.%a@." (Value.tagname x) Value.pp x Memory.pp mem)
```

**Comment by ivg** [comment]
And one more thing... Just taking one memory wouldn't be quite correct. Sine you're trying to find an interval that can accommodate your 4 bytes of memory, but you know only the address of this 4 bytes, then you must use `Seq.find_map` to find a first memory region, that is large enough to create a 4 bytes memory view on it.

**Comment by rvantonder** [comment]
I think I follow you. In this specific case, `Memmap.lookup` returns two ranges of `mem`s for my address `0xFE24`. The first corresponds to segment 03 of `readelf --segments`:

```
 Section to Segment mapping:
  Segment Sections...
   00     .ARM.exidx 
   01     
   02     .interp 
   03     .interp .note.ABI-tag .note.gnu.build-id .gnu.hash .dynsym .dynstr .gnu.version .gnu.version_r .rel.dyn .rel.plt .init .plt .text .fini .rodata .ARM.exidx .eh_frame 
   04     .init_array .fini_array .jcr .dynamic .got .data .bss 
   05     .dynamic 
   06     .note.ABI-tag .note.gnu.build-id 
   07  
```

Indeed, the range of the `.interp` section to `.rodata` is `00008000` to `000102C0`.

The second `mem` corresponds to the `.rodata` section alone, which we can see with `readelf --sections`:

```
Section Headers:
  [Nr] Name              Type            Addr     Off    Size   ES Flg Lk Inf Al
  [ 0]                   NULL            00000000 000000 000000 00      0   0  0
  [ 1] .interp           PROGBITS        00008134 000134 000013 00   A  0   0  1
  [ 2] .note.ABI-tag     NOTE            00008148 000148 000020 00   A  0   0  4
  [ 3] .note.gnu.build-i NOTE            00008168 000168 000024 00   A  0   0  4
  [ 4] .gnu.hash         GNU_HASH        0000818c 00018c 000280 04   A  5   0  4
  [ 5] .dynsym           DYNSYM          0000840c 00040c 0004b0 10   A  6   1  4
  [ 6] .dynstr           STRTAB          000088bc 0008bc 0002d0 00   A  0   0  1
  [ 7] .gnu.version      VERSYM          00008b8c 000b8c 000096 02   A  5   0  2
  [ 8] .gnu.version_r    VERNEED         00008c24 000c24 000020 00   A  6   1  4
  [ 9] .rel.dyn          REL             00008c44 000c44 000030 08   A  5   0  4
  [10] .rel.plt          REL             00008c74 000c74 000218 08   A  5  12  4
  [11] .init             PROGBITS        00008e8c 000e8c 00000c 00  AX  0   0  4
  [12] .plt              PROGBITS        00008e98 000e98 000338 04  AX  0   0  4
  [13] .text             PROGBITS        000091d0 0011d0 0064d8 00  AX  0   0  4
  [14] .fini             PROGBITS        0000f6a8 0076a8 000008 00  AX  0   0  4
  [15] .rodata           PROGBITS        0000f6b0 0076b0 000c14 00   A  0   0  4          <---
...
```

Indeed, the range here is `0000F6B0` to `000102C0`, which corresponds to what I got back for the second `mem`.

I understand (for the most part) the benefits behind representing memory in this way, and we should definitely be making these distinctions. As your diagram points out, sections never overlap (in ELF), but of course that can change for other formats.

In this instance, though, I'm very much confused that I get back two memory regions (because there's no way to know that this is what it does): one with my address contained in the ELF segment, and the other with the ELF section. How can I figure out what these memory regions correspond to? How do I know which is which?

From your explanation, it also seems that if I provide an address that is part of a symbol, then I'm going to potentially get back 3 memory regions: one for the segment, one for the .text section, and another corresponding to the symbol range. Again, how will I know what I'm getting (and how many regions)? It would be great if we could somehow expose that information when returning a `mem` (without having to test each thing individually).

**Comment by ivg** [comment]
> In this instance, though, I'm very much confused that I get back two memory regions (because there's no way to know that this is what it does): one with my address contained in the ELF segment, and the other with the ELF section. How can I figure out what these memory regions correspond to? 

`Memmap.lookup` has type `'a memmap -> addr -> (mem * 'a) seq`, for `Project.memory` `'a` is instantiated to `value` type. That means, that if you want to know to which segment a given address belongs, you can use the following code:

```ocaml
let segment_of_addr memory addr  =
  Memmap.lookup memory addr |> Seq.find_map ~f:(fun (mem,x) ->
      Value.get Image.segment x |> Option.map ~f:(fun x -> (mem,x)))
```

That will lookup for a segment, that contains this address. But there is an opportunity for abstraction here. We can abstract the particular kind of region, and define function `region_of_addr` of type `'a tag -> value memmap -> word -> (mem * 'a) option`:

```ocaml
let region_of_addr tag memory addr  =
  Memmap.lookup memory addr |> Seq.find_map ~f:(fun (m,x) ->
      Value.get tag x |> Option.map ~f:(fun x -> (m,x)))
```

And then we can easily define specific finders, e.g., `segment_of_addr : value memmap -> word -> (mem * Image.segment) option` and `section_of_addr : value memmap -> word -> (mem * string) option`:

```ocaml
let segment_of_addr = region_of_addr Image.segment
let section_of_addr = region_of_addr Image.section
```

> How do I know which is which? 
But it is not always the case, that you really need to know which is which. If you're only interested in data itself, you just take the same. Again, memory just defines particular region, of the process memory. This is not two memories are just two different views on the same underlying data. Just one of the views is more narrow. 

> From your explanation, it also seems that if I provide an address that is part of a symbol, then I'm going to potentially get back 3 memory regions: one for the segment, one for the .text section, and another corresponding to the symbol range. 

Well at least 3. There can be many more predicates associated with this particular address. For example, it can be marked as flawed, if some error has occurred on it. It can be marked by other plugins. It may belongs to several symbols. In general, map is a delimited union of sets, where each set is tagged with some value. And `lookup` answers to a question: "To which sets this address belongs?".
