### ISSUE TITLE
TIE availability/non-availability

### ISSUE THREAD

**Issue by pfalcon** [BinaryAnalysisPlatform/bap#232]
Can you please disclose TIE availability or non-availability under OpenSource license. Thanks.

**Comment by dbrumley** [comment]
TIE is not part of BAP.  TIE is not public at this time.

**Comment by ZhangZhuoSJTU** [comment]
Hi, I know this is an out-of-date issue. But I am curious about whether TIE is available right now? As there is nearly 5-years-old issue. 

Thanks.

**Comment by ivg** [comment]
@ZhangZhuoSJTU, TIE is not available and there are no plans on making tie a part of bap, you are welcome to contact the paper authors and ask them if they are willing to share the source code and under which premises.
