### ISSUE TITLE
bap installation problem on Mac

### ISSUE THREAD

**Issue by jordychen** [BinaryAnalysisPlatform/bap#236]
Hi, I'm a beginner of BAP and I have been trying to install BAP on my mac instructed by README. However, in the step "opam install bap", it shows the following install error:
```
=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫 
[ERROR] The compilation of bap failed at "./configure
        --prefix=/Users/jordy/.opam/4.01.0 --with-cxx=`which clang++`
        --mandir=/Users/jordy/.opam/4.01.0/man".
Processing  1/1: [bap: rm]
#=== ERROR while installing bap.0.9.8 =========================================#
# opam-version 1.2.1
# os           darwin
# command      ./configure --prefix=/Users/jordy/.opam/4.01.0 --with-cxx=`which clang++` --mandir=/Users/jordy/.opam/4.01.0/man
# path         /Users/jordy/.opam/4.01.0/build/bap.0.9.8
# compiler     4.01.0
# exit-code    1
# env-file     /Users/jordy/.opam/4.01.0/build/bap.0.9.8/bap-61894-1872ec.env
# stdout-file  /Users/jordy/.opam/4.01.0/build/bap.0.9.8/bap-61894-1872ec.out
# stderr-file  /Users/jordy/.opam/4.01.0/build/bap.0.9.8/bap-61894-1872ec.err
### stdout ###
# [...]
# pkg_lwt_log: ......................................... /Users/jordy/.opam/4.01.0/lib/lwt
# pkg_ezjsonm: ......................................... /Users/jordy/.opam/4.01.0/lib/ezjsonm
# pkg_uri: ............................................. /Users/jordy/.opam/4.01.0/lib/uri
# pkg_cohttp_lwt: ...................................... /Users/jordy/.opam/4.01.0/lib/cohttp
# pkg_re: .............................................. /Users/jordy/.opam/4.01.0/lib/re
# pkg_cmdliner: ........................................ /Users/jordy/.opam/4.01.0/lib/cmdliner
# pkg_re_posix: ........................................ /Users/jordy/.opam/4.01.0/lib/re
# pkg_curl: ............................................ /Users/jordy/.opam/4.01.0/lib/curl
# pkg_ocamlbuild: ...................................... /Users/jordy/.opam/4.01.0/lib/ocaml/ocamlbuild
# 
### stderr ###
# E:   Failed to find llvm library, consider using --with-llvm-version
#      or --with-llvm-config command line options, to point me on a
#      correct version of LLVM. 


=-=- Error report -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫 
The following actions failed
  ∗  install bap 0.9.8
```
Can anybody help me with it? Thank you so much.

**Comment by KennethAdamMiller** [comment]
It's telling you that you don't have llvm installed. Did you catch that
much?

**Comment by ivg** [comment]
Have you installed `llvm` at all? And if yes, then did you install it via `macports` or `brew`?

**Comment by jordychen** [comment]
Yes? I think I have installed it, "$ brew install llvm" gives: [Warning]: llvm-3.5.1 already installed.

**Comment by ivg** [comment]
ok, basically, we do not support `brew`, but we can still try. The main problem, is that we support only `llvm-3.4` family. So you need to install older version.

**Comment by jordychen** [comment]
Hi, thanks so much for your help. I turned to Unbuntu and installed bap successfully. However, the example in README using from top-level: 

"utop # let d = disassemble_file "/bin/ls";; " 
gives:
"disasm Memory.With_error.m = Core_kernel.Result.Ok <abstr> "

And "utop # let insn = Disasm.insn_at_addr d (Addr.of_int32 0xa9dbl);;"
gives:
"Error: This expression has type                                                          
    disasm Memory.With_error.m = (disasm, Core_kernel.Error.t) Core_kernel.Std_kernel._result         
       but an expression was expected of type disasm"

It seems that they are not expected results as in the README. What is wrong? Did I missed something in installation?

**Comment by ivg** [comment]
the example in Readme is amlittle bit outdated, I will fix it. Use [disassemble_file_exn](http://binaryanalysisplatform.github.io/bap/api/master/Bap.Std.html#VALdisassemble_file_exn) instead of `disassemble_file`.

**Comment by jordychen** [comment]
Thank you so much! My BAP finally starts to work!

**Comment by ivg** [comment]
Have a good hack! Feel free to ask questions (you can also use gitter, look at the badge on the main page)
