### ISSUE TITLE
Block.to_graph misleading for recursive functions.

### ISSUE THREAD

**Issue by dluchaup** [BinaryAnalysisPlatform/bap#237]
For direct-recursive functions, the current behavior of Block.to_graph is to add extra edges back to the entry node for each recursive call.
Example:
```ocaml
int inc(int n) { if (n <= 1) return n+1; else return 1 + inc(n-1); }
int main(void) { return inc(9); }
```
And the CFG for inc is:
```
digraph G {
  "840c" -> "8428";
  "840c" -> "8434";
  "8428" -> "844c";
  "8434" -> "840c";
  "8434" -> "8444";
  "8444" -> "844c";
  }
```
A potential fix would be to not add edges (src,dst) where src is a call and dst falls in the current function. To make such a decision, the Block.to_graph needs access to instruction at src. 
An alternative solution is to try to use the ~bound argument. However, this faces a potential interface problem because the ~bound argument/function in Block.to_graph doesn't have access to enough information to filter out such false back edges caused by recursive calls (at least not in the case when the entry node may be the target of a legitimate back edge).

**Comment by ivg** [comment]
I suggest you to use IR. It will properly resolve this is a call. I will remove this ocamlgraph functions soon, anyway.

**Comment by ivg** [comment]
> A potential fix would be to not add edges (src,dst) where src is a call and dst falls in the current function. To make such a decision, the Block.to_graph needs access to instruction at src. 

Another option is not to add jumps to entry block, as far as I understand, any jump to an entry can be considered as a self-recursive call. 

> To make such a decision, the Block.to_graph needs access to instruction at src. 
It has. `Block.terminator` returns the last instruction.

**Comment by ivg** [comment]
basically, your proposal can be implemented as follows:
```diff
              | `Block (dst,_)
-                when not (bounded bound (Block.addr dst)) -> gr
+                when not (bounded bound (Block.addr dst)) ||
+                    Insn.is_call (Block.terminator src) -> gr
```

**Comment by ivg** [comment]
Actually, both solutions proved to be incorrect. 
1. Function can jmp to entry (if it is leaf and compiled with `-fomit-framepointer`
2. Proposed solution will break, fallthrough edges.

**Comment by ivg** [comment]
This, solution is a more correct version
```diff
-              | `Block (dst,_)
-                when not (bounded bound (Block.addr dst)) -> gr
+              | `Block (dst,(`Cond|`Jump))
+                when not (bounded bound (Block.addr dst))
+                     || Insn.is_call (Block.terminator src) -> gr
```
will merge it in a next PR.
