### ISSUE TITLE
bapbuild doesn't compile standalone executables

### ISSUE THREAD

**Issue by ivg** [BinaryAnalysisPlatform/bap#240]
`bapbuild ssa.native` fails with `Error: No implementations provided for the following modules...` error

**Comment by ronnychevalier** [comment]
Hi,

For me there is Camlp4 and Pa_type_conv which are not provided. By adding camlp4.lib in the list of the packages, ocamlbuild will find it, so I think it could be added in bapbuild.ml.
But for Pa_type_conv even if type_conv is provided, ocamlbuild is still not able to find it.

**Comment by ivg** [comment]
yes, the same for me, will fix it soon, the following workaround should work for you, instead of 
```sh
bapbuild yourprog.native
``` 
use 
```
ocamlbuild -pkg bap yourprog.native
```

This will work unless you need to use preprocessor, in that case you can use the following script:

```
#!/bin/sh

ocamlbuild \
    -use-ocamlfind \
    -classic-display \
    -syntax camlp4o \
    -pkg bap \
    -pkg bap.plugins \
    -pkg core_kernel \
    -pkg sexplib.syntax,comparelib.syntax,fieldslib.syntax,variantslib.syntax \
    -pkg bin_prot.syntax \
    -tag thread \
    -tag debug \
    -tag annot \
    -tag bin_annot \
    -tag short_paths \
    -tag linkall \
    -cflags "-w A-4-33-40-41-42-43-34-44" \
    -cflags -strict-sequence \
    "$@"
```

**Comment by ronnychevalier** [comment]
On Tue, Jun 16, 2015 at 3:46 PM, Ivan Gotovchits
<notifications@github.com> wrote:
>
> yes, the same for me, will fix it soon, the following workaround should work for you, instead of
>

Ok thanks!
