### ISSUE TITLE
split phoenix into parts

### ISSUE THREAD

**Issue by ivg** [BinaryAnalysisPlatform/bap#241]
the `--phoenix` option in `bap` is not properly named at all, and very misleading. Moreover, it would be a good idea at least to rename it. Maybe, we can split it into several sub-options.

**Comment by rvantonder** [comment]
I'm all for renaming, but I'm not sure splitting it into sub-options is necessary. Given that bap has already has many options for tailoring output, it's nice to have something that just dumps everything in a directory, like the `--phoenix` option currently does.

**Comment by ivg** [comment]
yeah, and we also hit into 26 options cap :)
Instead of renaming, we can provide just an alias name. Any ideas about the name?
