### ISSUE TITLE
bap with --use-ida sometimes produces bap function CFG

### ISSUE THREAD

**Issue by dluchaup** [BinaryAnalysisPlatform/bap#246]
In some of my tests with  "bap ... --use-ida ..." sometimes the function CFG is corrupted.
I noticed the following:
(1) data mislabeled as function.
(2) the code for two functions placed next to each other [f1;data;f2] is treated as the body of a single function, f1. Sometimes there is an additional symbol for f2, therefore, there are overlapping functions.

Note: I caught this bug by asserting that no function entry has a predecessor inside its own CFG. In the case that I report where [f1;f2] are merged, the assertion failed because f2 was calling f1.

Please email me for specific binaries and functions.

**Comment by ivg** [comment]
This is not a bug. Separating data from code is undecidable in general. The algorithm can be of course better, but there're always trade-offs.

**Comment by dluchaup** [comment]
I know. I was hopping that out of the 40 examples that I have, some would provide more insight into this undecidable problem that we are trying to solve anyway.

**Comment by ivg** [comment]
Yep, can you send the examples to my mail. And are you using the latest BAP? Since, the reconstruction algorithm was rewritten in 0.9.8, and should be more accurate, than in previous versions.

**Comment by dluchaup** [comment]
I'm using BAP version 78de1b4199acc43a6f36b0fbc09c8e13bafbc94c.
I'll email the tests.

**Comment by KennethAdamMiller** [comment]
Ivan,

If you want a pointer on discerning data from code with high accuracy,
there was some excellent research that I was close to that too place at the
university of my MS (U.T. Dallas). In it, Richard Wartell and Dr. Kevin
Hamlen disclose a method by which to identify the undecidable path. While
that's not 100% accuracy, it's about 99%, good enough to recompile binaries
without source.

**Comment by ivg** [comment]
@KennethAdamMiller, are you talking about "Differentiating Code from Data in x86 Binaries" paper?
I know about this, we have close approach, but we cannot have a luxury of ad-hoc architecture specific solutions. So our algorithm should work for any ISA and any compiler.

**Comment by dluchaup** [comment]
At least in some of the cases, it appears that certain functions end with a call to some big_error_and_exit function.
This suggests the usefulness of specifying alternative return sequences to BAP. 
That is a call to big_error_and_exit function should be considered as ending the caller.

**Comment by ivg** [comment]
yes, that is handled in IR, that has a specific notion for a call that doesn't return. I think, that existing algorithm is quite sufficient for a first approximation, as its main purpose is not to miss any code, it can be a little bit more conservative and "eat" more data than needed. Next step, would be to create a pass, that will fix subroutines on IR level.
