### ISSUE TITLE
Error instaling depext

### ISSUE THREAD

**Issue by riyadparvez** [BinaryAnalysisPlatform/bap#247]
I am following the installation steps in BAP and this is the error I'm getting when installing `depext`

> $ opam install depext
> [ERROR] depext is not a valid versioned package name
> 'opam install depext' failed.

I'm using Linux Mint 17.

**Comment by ivg** [comment]
what version of `opam` are you using?

$ opam --version

**Comment by riyadparvez** [comment]
> $ opam --version
> 1.1.1

**Comment by ivg** [comment]
I suggest you to install the latest version of opam. If ppa works for Mint, then the following will do the work:

```sh
sudo add-apt-repository --yes ppa:avsm/ppa
sudo apt-get update
sudo apt-get --yes install opam
```

If you don't want to install newer opam, you can still proceed. But you need to install system packages manually, via `apt-get`. Currently we have the following set of system dependencies:
```
        "libgmp-dev"
        "libzip-dev"
        "libcurl4-gnutls-dev"
        "llvm-3.4-dev"
        "time"
        "clang"
        "llvm"
        "m4"
```

Basically, installing them with opam will work fine. But opam 1.2.2 is still recommended solution.

**Comment by riyadparvez** [comment]
Worked. Thanks!
