### ISSUE TITLE
README: "bapbuild hello_world.plugin" reports error 

### ISSUE THREAD

**Issue by computereasy** [BinaryAnalysisPlatform/bap#250]
Hello, 

I am a newbie to BAP and I am trying to play with the example in the README.md.

I installed `bap` through `opam`, which is the version 0.9.5.

I then tried to run first example in the README.md. And I got this error:

    File "hello.ml", line 4, characters 9-31:
    Error: Unbound module Project
    Command exited with code 2.
    Hint: Recursive traversal of subdirectories was not enabled for this build,
     as the working directory does not look like an ocamlbuild project (no
     '_tags' or 'myocamlbuild.ml' file). If you have modules in subdirectories,
     you should add the option "-r" or create an empty '_tags' file.
  
     To enable recursive traversal for some subdirectories only, you can use the
     following '_tags' file:
  
        true: -traverse
        <dir1> or <dir2>: traverse

It seems that `Project` module cannot be found.. Could anyone give me some help on this issue?

Also, does `bap` 0.9.5 has any difference with the newest version (`0.9.8`) in terms of the BAP IR?

**Comment by ivg** [comment]
Your opam is outdated. The latest BAP is of version 0.9.8.  It will be sufficient to issue
```sh
$ opam update
$ opam upgrade -y
```

**Comment by computereasy** [comment]
Thank you @ivg , I remembered I tried to use `opam pip` to install the newest version, but something still went wrong. Anyway, I will try to use `opam` with the newest version to take another shoot.

**Comment by ivg** [comment]
I suspect, that you're speaking of `opam pin`. Even you pinned bap, then `opam upgrade` will still work fine. It will just update you to the latest version from master branch, not to the latest released. That is perfectly fine.

**Comment by computereasy** [comment]
Thank you @ivg , it works perfectly fine. BTW: is there any example showing how to print out the disassembled program in terms BAP IR?

**Comment by ivg** [comment]
You can just use option `-dbir` or a long version `--dump=bir`. `man bap` (or `bap --help`) will expose more options. Programmatically, i.e., in plugin, you can print with:
```
Format.printf "Here is mine program:\n%a\n" Program.pp prog
```
where `prog` is obtained from `project` with `Project.program` function.

**Comment by computereasy** [comment]
@ivg , awesome! Thank you a lot  :+1:
