### ISSUE TITLE
Random string in dumped output of BIL

### ISSUE THREAD

**Issue by computereasy** [BinaryAnalysisPlatform/bap#254]
Hello, I am using some code to dump `BIL` in `json` format. And here is the code I use:

     open Bap.Std
    open Bil_piqi
    open Core.Std

    let () =
    let fn = Sys.argv.(1) in
    let proj = ok_exn (Project.from_file fn) in
    let _ = Project.disasm proj |> Disasm.insns
          |> Seq.map ~f:snd |> Seq.map ~f:Insn.bil |> Seq.to_list
          |> List.map ~f:Bil_piqi.json_of_stmts
          |> List.map ~f:print_string in
   () 

In the output, I observed some random string appeared. For example, for a given BIL like this:

    $ bap -dbil a.out > r
    $ cat r
    ....
    ESP := ESP + 0x4:32
    ....

The corresponding `json` format `BIL` is like this:

     {
    "move": {
      "lvar": { "name": "ESP", "id": 34, "typ": { "imm": 32 } },
      "rexp": {
        "binop": {
          "op": "plus",
          "lexp": {
            "var": { "name": "ESP", "id": 34, "typ": { "imm": 32 } }
          },
          "rexp": { "inte": { "int": "MHg0OjMy" } }
        }
      }
    }
  },

The `MHg0OjMy` looks meaningless to me..

I tried to dump the BIL in `xml` format, but the random string issue still exist. Could anyone give me some help on this? Thanks a lot.

**Comment by ivg** [comment]
yep, it doesn't look like an integer. Can you, please, upload your `a.out` file?

**Comment by sjcappella** [comment]
I've also had this issue when using bap-mc and outputting the result in JSON. Haven't had enough time to put together a detailed enough bug report, but the BIL and protobuf strings don't seem to have the same issue. I haven't found an instruction where the JSON output doesn't print out the random string instead of the 'int' value.

**Comment by ivg** [comment]
yep, I confirm the bug. It is reproducible. @computereasy, there is no need for `a.out`. I can reproduce it on a simple test cases.

**Comment by computereasy** [comment]
OK, @ivg  thank you for your time:)

**Comment by ivg** [comment]
So, this was not really a bug. But it made format somewhat unusable for those who doesn't use piqi or protobuf. @KennethAdamMiller, take a notice on change #255, it may affect your code, you may need to recompile your parsers.

**Comment by KennethAdamMiller** [comment]
I'm fine, I use protobuf, whenever you change, I will auto-regenerate my
code and other stuff. Do your thing man :)

**Comment by ivg** [comment]
@computereasy, the new format of the representation is the following (in EBNF):

```
      {[
        repr  = [sign], base, digit, {digit}, ":", size | true | false;
        sign  = "+" | "-";
        base  = "0x" | "0b" | "0o";
        size  = dec, {dec};
        digit = dec | oct | hex;
        dec   = ?decimal digit?;
        oct   = ?octal digit?;
        hex   = ?hexadecimal digit?;
      ]}
```

Examples: `0xDE:64`, `0x1:16`, `true`, `false`.

`true` and `false` are specials for `0x1:1` and `0x0:1` correspondingly. Make sure that your parser take care of this. The emitted data will not use bases other than `0x` so you can hardcode it, if you wish. Btw, if you're reading this in python, then you can use `ADT` format. To which we have python bindings (see `python` folder).

**Comment by computereasy** [comment]
@ivg , Hi, ivg, I `pin` the master branch through `opam`, and reinstalled `bap`. I then use the same code to dump the bil in `json` format. However, it seems that the "random" string is still there.. Am I missed something..?

**Comment by ivg** [comment]
After you pinned, did you made `opam upgrade bap`?

**Comment by computereasy** [comment]
I only did this:
    opam pin add bap git://github.com/BinaryAnalysisPlatform/bap
    
And I installed the master branch.

I tried `opam upgrade bap`, and it says:

    Already up-to-date.

**Comment by computereasy** [comment]
Oh, sorry, I should recompile the code.. Sorry for the trouble I made..
