### ISSUE TITLE
Translate `program`  to `stmt list` 

### ISSUE THREAD

**Issue by computereasy** [BinaryAnalysisPlatform/bap#257]
Hello, 

Is there any way to translate a `program` instance to a list of `stmt` instance? 

Basically after the `ssa` translation, I can get a `program` instance. However, it seems that all the `json` format translation is on `stmt` type. So I am thinking is there any way to translate a `program` instance into a corresponding `stmt list`? In which case I can easily generate `json` format code from the `stmt list`.. 

I really appreciate if any one can give me some help on it. Thanks a lot.

**Comment by ivg** [comment]
No, there is no way back. If you need json serialization for IR, please create an issue. We will try to add this. From which language are you trying to read IR, btw?

**Comment by computereasy** [comment]
Oh.. I see.. @ivg  I am using OCaml. `atdgen` + `yojson` is pretty neat to use when parsing `json` format data.

**Comment by ivg** [comment]
If you're using OCaml why do you need transformation to json? IR supports two robust serialization format, `bin_prot` and `sexp`. Why don't you use them?

**Comment by computereasy** [comment]
@ivg  I don't know it.. I am familiar with `json` and I happened to know `bap` can dump `json`, so that's why I was trapped in this..

**Comment by ivg** [comment]
If you need to serialize data (for IPC or persistance), it is better to use `bin_prot` protocol. The usage is quite simple. For example, serializing to and from bin_prot can be done as simple as:
```
let string_of_program = Binable.to_string (module Program)
let program_of_string = Binable.of_string (module Program)
```
 
Second serialization protocol is called `s-exp`, it is similar to json, and it is text based. Use `sexp_of_program` and `program_of_sexp` functions to transform program to/of `s-exp`. Use `Sexp.to_string` function to transform it to string.

**Comment by computereasy** [comment]
perfect. @ivg  thank you and let me have a try!

**Comment by computereasy** [comment]
@ivg  Sorry for the trouble but basically how can I translate an instance of  `program term` type to `program` type? The `sexp_of_program` only takes `program` type input..

**Comment by ivg** [comment]
Oh, indeed. Use `Program.sexp_of_t` and `Program.t_of_sexp`

```ocaml
$ baptop
# open Core_kernel.Std;;
# open Bap.Std;;
# let p = Program.create ();;
val p : Program.t = 00000001: program                                                                                                                                                                                                                                                                                                                                                                 
# Program.sexp_of_t p;;
- : Core_kernel.Core_sexp.t = ((tid 1) (self ((subs ()) (paths ()))) (dict ()))                                                   
# Binable.to_string (module Program) p;;
- : bytes = "\001\000\000\000"

**Comment by computereasy** [comment]
thank you a lot! :+1:
