### ISSUE TITLE
BAP not compatible with core_kernel.112.35.00

### ISSUE THREAD

**Issue by alpire** [BinaryAnalysisPlatform/bap#260]
Hey,

I think the latest core_kernel update broke the bap build. More specifically, they "renamed `Monad.ignore` as `Monad.ignore_m`" in 112.35.00.

My build breaks at https://github.com/BinaryAnalysisPlatform/bap/blob/master/lwt/core_lwt_container.ml#L88, as Pervasives.ignore is now called instead of Monad.ignore.

To fix the build, consider renaming the uses of Mondad.ignore, or pinning core_kernel to 112.24.00.

Thanks,
Alex

**Comment by ivg** [comment]
oh, Janestreet so janestreet :(

Thanks for pinpointing!
