### ISSUE TITLE
BAP installion is giving error 

### ISSUE THREAD

**Issue by prashast94** [BinaryAnalysisPlatform/bap#286]
![screenshot from 2015-08-14 17 23 15](https://cloud.githubusercontent.com/assets/13796871/9273312/35fbdc10-42a9-11e5-9455-c06edca3445f.png)
When I try to opam install bap this is the error which I get as seen in the screen shot. piqlib 0.6.6 is failing to be built. I even tried installing piqlib separately but that also failed.
I have installed everything as mention in the installation procedures. Kindly let me know what is needed to be done.

**Comment by ivg** [comment]
very strange... Can you please provide as much information as possible about your setup, so that I can build a virtual machine to reproduce the error? 

Meanwhile, as a suggested workaround, you can try to force opam to install different version of piqi. Use `opam show piqi` to get a list of available versions. To install a specific version just append it to a name of a package, e.g., `opam install piqi.1.2.3`

**Comment by KennethAdamMiller** [comment]
piqi and piqi-ocaml (which correspond to the piqilib and piqi opam packages
respectively) have been seeing some traffic on the git repo, but I don't
think the changes have been shipped to the opam repositories at all.

If you could please do an opam update to make sure that you are working
with the latest, and try pinning your piqi and piqilib opam packages to the
github repositories piqi-ocaml and piqi if after doing an update and
reattempted install it doesn't succeed.

**Comment by prashast94** [comment]
@ivg I had installed the trunk branch of the Ocaml github repo after which I had installed opam through their github repo as well. Once that was done I've followed the installation instructions listed on your bap page and have been getting that same error of piqi not being able to be made. I even tried your workaround to installl other versions of piqi but all of them are giving me the same problem

@KennethAdamMiller I did update my opam to the latest version but to no avail and regarding pinning my packages to the piqi-ocaml and piqi, kindly let me know how it is to be done as I'm kinda new to this. I did opam pin add piqi 0.7.4 --dev-repo. Is that correct?

**Comment by KennethAdamMiller** [comment]
I wouldn't know if that specific command would succeed. The way that I do
it, is I do a git clone of the respective respositories and then opam pin
add piqi /path/to/piqi-ocaml, same for piqilib; that's always worked. Also,
two more small things: if  you get another error, please gist the .err and
other two files that opam metions (with the funny numbers on them), and
secondly if you don't want to deal with any of this there's a new
dockerfile that should get you fully built easily.

Possibly what is happening is you have some apt managed package conflicting
with what should be an opam managed dependency. So, when opam goes to
install it, it sees what it installed or is already there as a dependency
but the ocaml compiler is seeing things in your local folders from aptitude
and preferencing them over the opam folders.

**Comment by ivg** [comment]
> I had installed the trunk branch of the Ocaml github repo after which I had installed opam through their github repo as well. 

That's quite unusual way of installing opam. I have a guess. Have you run 

    eval `opam config env` 

(notice the backticks). Just after you installed opam and before you started to install anything else via opam?

**Comment by maverickwoo** [comment]
The error message suggests that somehow the constraint solver is missing `optcomp`. Please run `opam install optcomp` and try again.

**Comment by KennethAdamMiller** [comment]
Ok, please let me know if that fixes it, and I will add optcomp to the
dependency set of the piqi opam package on the next pull request.

**Comment by prashast94** [comment]
@maverickwoo That fix worked like a charm. Thanks a ton! @KennethAdamMiller It worked.

But it's only half a battle won for me. I am originally trying to install ropc which uses bap. Their archival version of bap 0.4 isn't compiling hence I came here. Still showing some kinks. I guess I'll create a new issue there. :P

**Comment by KennethAdamMiller** [comment]
If you're using bap .4 there are going to be significant differences
between the apis and semantics. I would be shocked if it even still
compiled. But refactoring the gadget identifier using the new disassembler
callback and possibly using an approach like that of a shingled
disassembler would probably be very straightforward. There's already a
shingled disassembler example that you can tailor for your purposes.
