### ISSUE TITLE
Codes for converting .elf to BIL

### ISSUE THREAD

**Issue by jordychen** [BinaryAnalysisPlatform/bap#293]
Execuse me, I have a question about converting .elf to BIL. 

I know that in Vine, you used BFD(libbfd) and GNU libopcodes lifting binary file to VEX, or Interfaced with IDA Pro. Read from the BitBlaze paper.

My questions are: 
In BAP, How did you exactly disassemble(use linear-sweep algorithm and parse) the .elf?
How did you then convert the assembly code(parsed .elf) into BIL? 

Can you please show me the code part? I just don't know which part of the code in github works on it. Or this part is finished by interfacing with IDA Pro and the real work is finished by IDA Pro?

I traced the function calls from example "Project.from_file filename", it goes to function "Image.create, then to function "readfile", to "mapfile", finally reached "fd= Unix.(openfile path [O_RDONLY] 0o400)".  But still confused about how a binary file is converted to BIL.

Thanks so much for your always-being-patiently replying.

**Comment by ivg** [comment]
BAP has a plugin architecture, that allows to dynamically extend it. We have three kinds of plugins (points of extensions) currently:

- loader - to parse and load binary containers, e.g., COFF, ELF, MACH-O
- disassembler - to transform bytes to machine instructions
- program analysis - for adding analysis passes

So far we ship BAP with two loader plugins and one disassembler. One of the loaders is a native implementation in OCaml, that supports only ELF. Another loader is a binding to LLVM Binary library. 
There is only one disassembler currently, that uses LLVM MC library. 

So let's see how a chunk of bytes becomes an IR term.

1. The chunk can be either a raw binary, or a binary packed into some container, like ELF, for example. 
Module `Image` abstracts all possible containers, and represents program image as it is viewed by an operating system. `Image.create` will map a file and lookup for registered plugins. Currently, to loaders are statically plugged in: one is in `bap_image/bap_native_loader.ml` another is in `bap_image/bap_llvm_loader.ml`. Native loader uses our [Elf](http://binaryanalysisplatform.github.io/bap/api/master/Bap.Std.Elf.html) and [Dwarf](http://binaryanalysisplatform.github.io/bap/api/master/Bap.Std.Dwarf.html) libraries to extract all needed information. LLVM loader will use LLVM library for that, and most of the code is in C++. 

2. Once data is loaded and represented as [memory](http://binaryanalysisplatform.github.io/bap/api/master/Bap.Std.Memory.html) object it can be disassembled. The disassembler backend API is defined in C language, and is exposed into OCaml with [`Disasm_expert.Basic`](http://binaryanalysisplatform.github.io/bap/api/master/Bap.Std.Disasm_expert.Basic.html) disassembler.
 On top of basic disassembler a [recursive descent disassembler](http://binaryanalysisplatform.github.io/bap/api/master/Bap.Std.Disasm_expert.Recursive.html) is built. The implementation is in `bap_disasm/bap_disasm_basic.ml` and `bap_disasm/bap_disasm_rec.ml` correspondingly. 

3. Once we have machine basic blocks filled with machine instructions, we can perform lifting this to a semantics level, i.e., to give this some machine understandable meaning. First, we use lifters, that produces for each machine instruction a piece of BIL (Bap Instruction Language) code. This is a primitive fortran-like language, that we use as a lingua franca to represent different assemblers. As a result, we have a source code of a program in BIL. Next, we can act like we're doing source based program analysis - we lift the AST into IR, and now we can write analysis, like SSA, Sparse constant propagation, dataflow and so on.

**Comment by jordychen** [comment]
It's really helpful, thanks a lot. I've had a better understanding about BAP.
