### ISSUE TITLE
x86-64 Binary to BAP IR, understanding BAP IR

### ISSUE THREAD

**Issue by Shadiasd** [BinaryAnalysisPlatform/bap#300]
Hi everyone,

I am very new to BAP, so I apologize in advance for the basic questions. Here is two quick questions I have:

1. I know by using bap-mc and --show-bir I can lift raw bytes to BAP IR. I was looking for a similar way to generate BAP IR out of binary files.

2. Also I was wondering if you have a documentation that helps understanding BAP IR. By looking at BAP IR I can generally understand what is going on but not all of the detail :(

Thank you :)

**Comment by ivg** [comment]
1. There is a `bap` utility (actually a main utility in a bap toolkit, `bap-mc` is auxiliary). It works on binary files. It has lots of options, that cover its functionality. Basically, `bap -dbil exe` will dump IR of the whole the IR of a whole program. 
2. Yes, it is [documented][1].

[1]: http://binaryanalysisplatform.github.io/bap/api/master/Bap.Std.html#sema
