### ISSUE TITLE
Node.update broken for  Graphlib.Labeled

### ISSUE THREAD

**Issue by dluchaup** [BinaryAnalysisPlatform/bap#302]
Node.update promises to update the label of a node, but it seems that this update is partial, the edges in/out of that node seem unchanged.
Example:
```ocaml

module GINTS = Graphlib.Labeled(Int)(String)(Unit) ;;
let uq_inode2string n = (sprintf "{%s:%s}" (Int.to_string (GINTS.Node.label n).node) (GINTS.Node.label n).node_label);;
let uq_iedge2string e = sprintf "(%s -> %s)" (GINTS.Edge.src e |> uq_inode2string) (GINTS.Edge.dst e |> uq_inode2string);;
let show_graph g = 
  (GINTS.nodes g |> Seq.to_list |> List.to_string ~f:uq_inode2string |> (sprintf "Nodes=%s") |> print_endline;
   GINTS.edges g |> Seq.to_list |> List.to_string ~f:uq_iedge2string |> (sprintf "Edges=%s") |> print_endline);;

let n1 = GINTS.Node.create {node=1; node_label = "unu"};;
let n2 = GINTS.Node.create {node=2; node_label = "doi"};;
let e12 = GINTS.Edge.create n1 n2 ();;

let g =   GINTS.Node.insert n1 GINTS.empty
       |> GINTS.Node.insert n2
       |> GINTS.Edge.insert e12;;

let n1en = GINTS.Node.create {node=1; node_label = "one"};;
let n2en = GINTS.Node.create {node=2; node_label = "two"};;
let n3en = GINTS.Node.create {node=3; node_label = "three"};;
let n4en = GINTS.Node.create {node=4; node_label = "four"};;

let g1 = GINTS.Node.update n1 n1en g;;
let g2 = GINTS.Node.update n2 n2en g;;
let g3 = GINTS.Node.update n1 n3en g;;
let g4 = GINTS.Node.update n3en n4en g;;

(*
utop # show_graph g;;
Nodes=({1:unu} {2:doi})
Edges=("({1:unu} -> {2:doi})")

utop # show_graph g1;;
Nodes=({1:one} {2:doi})
Edges=("({1:one} -> {2:doi})")

utop # show_graph g2;;
Nodes=({1:unu} {2:two})
Edges=("({1:unu} -> {2:doi})")

utop # show_graph g3;;
Nodes=({1:unu} {2:doi} {3:three})
Edges=("({1:unu} -> {2:doi})""({3:three} -> {2:doi})")

utop # show_graph g4;;
Nodes=({1:unu} {2:doi})
Edges=("({1:unu} -> {2:doi})")
*)

(* alternatively, look at the dot files generated by: *)
let inode2string n = uq_inode2string |> sprintf "%S";;
let gints2dot fn g =  Graphlib.to_dot(module GINTS) ~filename:fn ~string_of_node:inode2string g;;
gints2dot "g" g;;
gints2dot "g1" g1;;
gints2dot "g2" g2;;
gints2dot "g3" g3;;
gints2dot "g4" g4;;
```

**Comment by dluchaup** [comment]
Note that the updates resulting in g3 and g4 don't make much sense, but were shown as examples to clarify the behavior ...

**Comment by ivg** [comment]
I'm sorry, but I don't see any problem,

```
utop # show_graph g;;
Nodes=({1:unu} {2:doi})
Edges=("({1:unu} -> {2:doi})")

utop # show_graph g1;;
Nodes=({1:one} {2:doi})
Edges=("({1:one} -> {2:doi})")
```

in graph `g1` the label is changed from `unu` to `one` in nodes and edges. Where is the issue?

**Comment by dluchaup** [comment]
I should have been more precise. The problem is in g2. Look at the nodes (which are fine) and the edges (which are not) for g2. The label for '2' is not changed. It looks like only the source nodes of edges are updated. Try:
-----
let n3 = GINTS.Node.create {node=3; node_label = "trei"};;
let e23 = GINTS.Edge.create n2 n3 ();;
let g_3 = GINTS.Node.insert n3 g |> GINTS.Edge.insert e23;;
let g_32 = GINTS.Node.update n2 n2en g_3;;
show_graph g_3;;
show_graph g_32;;
-----
Also the following update should probably fail, but it works with surprising results:
-----
let g_junk = GINTS.Node.update n2 n3en g_3;;
show_graph g_junk;;
Nodes=({1:unu} {2:doi} {3:three})                                                                                                                                                                                                                                                  Edges=("({1:unu} -> {2:doi})""({2:doi} -> {3:trei})""({3:three} -> {3:trei})")
