### ISSUE TITLE
Unbound value error when creating call graph with baptop

### ISSUE THREAD

**Issue by jgarci40** [BinaryAnalysisPlatform/bap#304]
I am trying the example under the "Using from top-level" section in the Readme.md file. In baptop, I can follow the instructions up until the following command:

utop # let cg = Program.to_graph prog;;
Error: Unbound value Program.to_graph

I'm not sure why Program.to_graph is unbound. I also get the following error when I start baptop:

Cannot find file /home/joshua/.opam/4.02.1/lib/bitstring/unix.cma.

I am using Ocaml 4.02.1 and bap 0.9.8 on Linux Mint 17.2.

**Comment by ivg** [comment]
I suspect, that your version of bap is too old. Install `bap.0.9.9`

**Comment by jgarci40** [comment]
That worked. Thank you for the quick response!
