### ISSUE TITLE
Sub.to_graph empty for single block functions

### ISSUE THREAD

**Issue by dluchaup** [BinaryAnalysisPlatform/bap#305]
If a subroutine sub has a single block, then 
Sub.to_graph sub
returns an empty graph.
Example: compile this on ARM and use 'main' as sub:
int main(int argc, char* argv[]) { return 1;}

**Comment by ivg** [comment]
yep, actually only edges were added. That means, that all unreachable node are also not added. Will push a fix in a few minutes. Good catch!
