### ISSUE TITLE
bap installation on ubuntu14.04

### ISSUE THREAD

**Issue by nemare** [BinaryAnalysisPlatform/bap#314]
The error is about ncurses-dev package .I have installed libncurses5-dev package on my Ubuntu14.04 .But when I used "opam install bap" to install bap ,it told me to install ncurses-dev package.Could you tell me how to solve this problem?
![img_1324](https://cloud.githubusercontent.com/assets/6057260/11206280/f43cafe4-8d48-11e5-9adb-6b88948d0d42.JPG)
![img_1323](https://cloud.githubusercontent.com/assets/6057260/11206360/8c8b11f0-8d49-11e5-9341-595f16692050.JPG)

**Comment by ivg** [comment]
I don't see any error messages there. It is just an info message, where opam is telling you what he is doing with your system. Here it just told you, that it installed ncurses-dev package. There is no need to install it manually. Just continue the installation.

P.S. and don't use root account fir your everyday work ;)

**Comment by nemare** [comment]
![384121eee4aa57c07601a030f5837f13](https://cloud.githubusercontent.com/assets/6057260/11216732/c29eb254-8d87-11e5-9af6-4624d7550a08.jpg)
Thank you for answering my question.Here is error message ..I continued bap installation.I have tried several times. I think the missing dependency is ncurses-dev ,because after using "opam depext bap",it told me to install ncurses-dev package.

**Comment by ivg** [comment]
The error message is `Fatal error: out of memory`. Just add more memory on your VM. I think 2Gb is ok.

**Comment by nemare** [comment]
thank u! ivg it works

**Comment by ivg** [comment]
you're welcome!
