### ISSUE TITLE
Compiling on OS X

### ISSUE THREAD

**Issue by fxfactorial** [BinaryAnalysisPlatform/bap#315]
This is currently not compiling on latest of OS X and OCaml 4.02.3. 

It craps out on 

```shell
#=== ERROR while installing bap.0.9.9 =========================================#
# opam-version 1.2.2
# os           darwin
# command      ./configure --prefix=/Users/Edgar/.opam/bap --with-cxx=`which clang++` --mandir=/Users/Edgar/.opam/bap/man
# path         /Users/Edgar/.opam/bap/build/bap.0.9.9
# compiler     4.02.3
# exit-code    1
# env-file     /Users/Edgar/.opam/bap/build/bap.0.9.9/bap-20020-bda212.env
# stdout-file  /Users/Edgar/.opam/bap/build/bap.0.9.9/bap-20020-bda212.out
# stderr-file  /Users/Edgar/.opam/bap/build/bap.0.9.9/bap-20020-bda212.err
### stdout ###
# [...]
# pkg_lwt_log: ......................................... /Users/Edgar/.opam/bap/lib/lwt
# pkg_ezjsonm: ......................................... /Users/Edgar/.opam/bap/lib/ezjsonm
# pkg_uri: ............................................. /Users/Edgar/.opam/bap/lib/uri
# pkg_cohttp_lwt: ...................................... /Users/Edgar/.opam/bap/lib/cohttp
# pkg_re: .............................................. /Users/Edgar/.opam/bap/lib/re
# pkg_cmdliner: ........................................ /Users/Edgar/.opam/bap/lib/cmdliner
# pkg_re_posix: ........................................ /Users/Edgar/.opam/bap/lib/re
# pkg_curl: ............................................ /Users/Edgar/.opam/bap/lib/curl
# pkg_ocamlbuild: ...................................... /Users/Edgar/.opam/bap/lib/ocaml/ocamlbuild
# 
### stderr ###
# E:   Failed to find llvm library, consider using --with-llvm-version
#      or --with-llvm-config command line options, to point me on a
#      correct version of LLVM. 
```

Makes senses, it couldn't find it. Although I do have it installed via `brew` which leads me to my next point.

Can you change the default or at least add brew to the depext's opam file? 

so 

1) doesn't build on OSX from opam
2) Why not brew over macports for opam depexts file.

**Comment by ivg** [comment]
Well, first of all we're not supporting `brew` mostly because none of us use it. We prefer `macports`. But if you're willing to contribute , then we will be happy to accept the PR. I heard rumors that people managed to install bap with brew, but they never shared their success stories with us. 

> Can you change the default or at least add brew to the depext's opam file?

I can add `brew` entry to opam, as soon as I will know names and versions of packages in brew's vernacular.

> 1) doesn't build on OSX from opam

It does build. But only for macports. Many of us are using macs as our work horses.

> 2) Why not brew over macports for opam depexts file.

Because we like `macports` ;)

**Comment by fxfactorial** [comment]
Okay, I'll maybe try to add brew support later.
