### ISSUE TITLE
building byte code executable

### ISSUE THREAD

**Issue by jgarci40** [BinaryAnalysisPlatform/bap#318]
I am trying to create a byte code executable using bapbuild, as shown here:
```
$ bapbuild hello_world.byte
+ ocamlfind ocamlc -linkpkg -g -thread -syntax camlp4o -package re.posix -package fileutils -package cmdliner -package ezjsonm -package ocamlgraph -package variantslib.syntax -package fieldslib.syntax -package comparelib.syntax -package sexplib.syntax -package core_kernel -package bap.plugins -package bap hello_world.cmo -o hello_world.byte
File "_none_", line 1:
Error: Error on dynamically loaded library: /home/joshua/.opam/4.02.3/lib/stublibs/dllllvm_stubs.so: /home/joshua/.opam/4.02.3/lib/stublibs/dllllvm_stubs.so: undefined symbol: del_curterm
Command exited with code 2.
```
Apparently, dlllvm_stubs.so is not linked with the Terminfo library. How can I resolve this issue? My ultimate goal here is to use bap with the ocaml debugger, which seems to require a byte code executable.

**Comment by ivg** [comment]
Yep, this is a known issue. Unfortunately I don't know the resolution so far.

**Comment by jgarci40** [comment]
Thank you for letting me know. How do you use a debugger when writing bap-based code (e.g., plugins)? For example, do bap plugins work well with the OCaml debugger?

**Comment by ivg** [comment]
Nope, they don't, for the same reason. I personally, don't use debuggers. Maybe only gdb, for debugging c-bindings segfaults.

**Comment by jgarci40** [comment]
Got it. Thanks again, Ivan.

**Comment by ivg** [comment]
Just got a minute to tackle with this issue. The solution is quite simple, shame on me, that it didn't pop up at the time you did ask. You need to set `custom` mode, when compiling bap in a bytecode mode. 
```
bapbuild -custom hello_world.byte
```
I will fix `bapbuild` so that it can infer this option automatically.

**Comment by jgarci40** [comment]
Thanks, Ivan. I will try this again at some future date.
