### ISSUE TITLE
Possible error

### ISSUE THREAD

**Issue by abarbaro** [BinaryAnalysisPlatform/bap#334]
Hi,
I'm using BAP and I encountered this instruction:

Insn("TEST8i8", 0x00000041, 2, "	testb	$0x2, %al", [], [Imm(0x2)])

Can someone tell me why no registers are considered as operands?

Thanks,
Alberto

**Comment by ivg** [comment]
This is how LLVM developers decided to encode it. The reason, I think, was that `test` instruction works only with register `A`. And in the assembly the register name is used for overloading between test on different sizes. Since in LLVM backend all instruction are explicitly size qualified and there is no overloading, the really don't need the register argument.

**Comment by ivg** [comment]
Just checked, the lifter outputs a correct code, that mentions the register:
```ocaml
$ echo "\xa8\x02" | bap-mc --arch=x86-64 --show-bil --show-insn
TEST8i8(0x2)
{
  v1 := (low:8[low:32[RAX]]) & 0x2:8
  OF := false
  CF := false
  AF := unknown[AF is undefined after and]:u1
  PF := ~(low:1[let v2 = (v1 >> 0x4:8) ^ v1 in
    let v2 = (v2 >> 0x2:8) ^ v2 in
    (v2 >> 0x1:8) ^ v2])
  SF := high:1[v1]
  ZF := 0x0:8 = v1
}
```

**Comment by abarbaro** [comment]
I just tried with other instructions:

Insn("TEST8ri", 0x0000000b, 3, "	testb	$0x8, %dl", [], [Reg("DL"), Imm(0x8)]),
Insn("TEST8i8", 0x0000000e, 2, "	testb	$0x1, %al", [], [Imm(0x1)])

Maybe I'm still missing something but is it possible that you add also Reg("AL") in the next release? It would be easier to understand...

Thanks

**Comment by ivg** [comment]
Oh, we can't add it, you can ask the upstream, the LLVM team (although I doubt that they will add something). 

An LLVM machine code is different from an target assembly. You may think of it as some sort of very low level intermediate representation. And it doesn't match to the assembly one to one. For example:
`testb $0x1 %al` maps to an MC instruction `TEST8i8`, and `testb $0x1 %bl` maps to MC instruction `TEST8ri` that is more general and can include arbitrary registers. Looks like that they decided to add a shortcut for `test _ %al` for some reason, that are beyond of comprehension of mere mortals :)

We're working on BIL level, that abstracts all this backend issues. And we print this instructions only for the purpose of debugging. And I suggest you to do the same. If there're some issues with this approach feel free to poke me.

**Comment by abarbaro** [comment]
Gotcha :)

I'll consider it as a corner case and add a workaround in my code.

Thanks a lot for your help!
