### ISSUE TITLE
BAP installation issue (Ubuntu)

### ISSUE THREAD

**Issue by Dinatrix** [BinaryAnalysisPlatform/bap#335]
Hi!

I followed the procedures outlined in https://github.com/BinaryAnalysisPlatform/bap/ to download both opam and bap in a Ubuntu 14.04.03 VM (after not having luck with 15) as well as dependencies as I saw they were necessary. Everything I thought was needed installed except for bap itself? Below was my process when installing, including some screenshots. Additionally, I have a google drive link to the actual virtual machine I was using to try and install BAP on (if that helps). Maybe there is a dependency I may have missed somewhere along the line?:

wget https://raw.github.com/ocaml/opam/master/shell/opam_installer.sh -O - | sh -s /usr/local/bin

![bap1](https://cloud.githubusercontent.com/assets/10760263/12553530/1020ecb0-c346-11e5-9eff-82609ae66f3e.PNG)

sudo apt-get update
sudo apt-get install git
//it couldn’t find hg though?
sudo apt-get install darcs (popup)
sudo apt-get install aspcud
sudo apt-get install m4
opam init --comp=4.02.1
do you want opam to modify profile and ocamlinit? y
eval `opam config env`
opam install depext
opam depext bap
opam install bap

![bap2](https://cloud.githubusercontent.com/assets/10760263/12553554/2ddfe292-c346-11e5-8567-9766c5fb1191.PNG)

![bap3](https://cloud.githubusercontent.com/assets/10760263/12553573/42f14f40-c346-11e5-8a32-cba8e0f5807b.PNG)

![bap4](https://cloud.githubusercontent.com/assets/10760263/12553583/51094dc6-c346-11e5-9a55-1786b80a17ea.PNG)

![bap5](https://cloud.githubusercontent.com/assets/10760263/12553587/5b43fcf0-c346-11e5-952a-2a9dde67b6f6.PNG)

OS packages installation successful
opam install bap
sudo apt-get install mercurial
which hg (it was installed)
opam install bap

![bap6](https://cloud.githubusercontent.com/assets/10760263/12553598/6ed716b2-c346-11e5-8e94-aaa4a1b9024c.PNG)

**Comment by ivg** [comment]
For some reason `opam` decided to install a very old version of `bap`. It looks like, that dependency constraints of the old version become rotten, as some upstream packages made incompatible changes. 

A workaround solution would be to force opam, to install a more recent version:

```
opam install bap.0.9.9
```

**Comment by ivg** [comment]
ah, it is not an opam fault, for some reason you made it yourself, you requested a specific version by saying `opam depext bap.0.9.4`. Did you find this instructions somewhere on the web?

**Comment by Dinatrix** [comment]
When just doing 'opam install bap', it wants to install bap.0.9.4 automatically. Will try again by forcing 0.9.9
![bap7](https://cloud.githubusercontent.com/assets/10760263/12554051/b9af1fb6-c348-11e5-9458-2e83341a21d8.PNG)

**Comment by Dinatrix** [comment]
bap.0.9.9 installed! Thanks again

**Comment by ivg** [comment]
You're welcome. I will remove older versions from a repository, to prevent such issues to occur in the future.
