### ISSUE TITLE
Error information for `Signatures.load`

### ISSUE THREAD

**Issue by maurer** [BinaryAnalysisPlatform/bap#342]
[`Signatures.load`](http://binaryanalysisplatform.github.io/bap/api/master/Bap.Std.Signatures.html) returns a `string option` rather than `(string, ?) Result.t`.

This means that when a signature fails to load, I don't know if:

* BAP can't find the signature file
* The signature file is corrupt
* The mode/arch combination I passed is not present in the signature file

It would be nice to actually get error information to ease in debugging when the signature does not load.

**Comment by ivg** [comment]
agree

**Comment by ivg** [comment]
Would you like to fix it? Otherwise I will grab the issue.

**Comment by ivg** [comment]
I accept your silence as a refusal to fix it yourself :) The issue is grabbed.
