### ISSUE TITLE
Support kernel modules

### ISSUE THREAD

**Issue by ivg** [BinaryAnalysisPlatform/bap#345]
Currently both loaders are unable to load a kernel module. 

The llvm loader fails disgracefully deep in the LLVM:

```
Program received signal SIGFPE, Arithmetic exception.
0x00007ffff0be402d in operator- (this=<optimized out>, this=<optimized out>, Other=...) at /usr/lib/llvm-3.4/include/llvm/Object/ELF.h:111
111           return (Current - Other.Current) / EntitySize;
(gdb) bt
```

This looks like a problem on the LLVM side, that can't be fixed on our side, but further investigation should be done.

The native elf-loader still fails, as it is unable to find at least one valid segment in the file. And this is true, as kernel modules indeed doesn't contain segments, only sections.  Indeed, a kernel module is a very different beast.

**Comment by KennethAdamMiller** [comment]
It's also notable that kernel assembler is a different dialect entirely. There are additional hardware and capabilities to kernel level, as well as restrictions (floating point computation). Upgrades to the lifter and disassembler should be made in pair with such a closing this ticket.
