### ISSUE TITLE
Tid.from_string_exn prefix operator (!) clash

### ISSUE THREAD

**Issue by rvantonder** [BinaryAnalysisPlatform/bap#354]
In baptop:

`let t = Tid.(!"@main");;`

Type is
`val t : ('a, 'b, 'c, 'd, 'd, 'a) format6 =`

Should be type `tid` or exception, since `!` should be a shortcut for `from_string_exn`:

`let r = Tid.from_string_exn "@main";;`

Presumably this is a ppx issue, not a BAP issue.

**Comment by ivg** [comment]
Suggestion to use `!!` or `!@` or something else. It is not hard to fix, just a naming issue, and we should resolve this before the release. Everyone is welcome to suggest better prefix operator.
