### ISSUE TITLE
issues when plugin name contains underscore

### ISSUE THREAD

**Issue by dluchaup** [BinaryAnalysisPlatform/bap#369]
Consider the plugin stored in a file myplugin.ml
`open Core_kernel.Std
open Bap.Std
open Format

include Self()

let () =   print_endline "Register my plugin."

let main proj =  print_endline "Call my plugin."

let () = Project.register_pass' main
`

Compiled as:
_ bapbuild -package bap-arm -package cmdliner myplugin.plugin
_
And run as:
_dan@xubuntu2:~/learn/bap/abi-refactor-xptr$ bap /home/dan/learn/bap/abi-refactor-xptr/tmp/sub_fix_test_1.arm-O1.x  -lmyplugin --myplugin
Register my plugin.
Call my plugin.
_

Now, change the name from myplugin.ml to my_plugin.ml and compile. 
When trying to run, we get:
_dan@xubuntu2:~/learn/bap/abi-refactor-xptr$ bap /home/dan/learn/bap/abi-refactor-xptr/tmp/sub_fix_test_1.arm-O1.x  -lmy_plugin --my_plugin
Register my plugin.
bap: unknown option `--my_plugin'.
Usage: bap [OPTION]... FILE
Try `bap --help' for more information.
_

**Comment by ivg** [comment]
https://help.github.com/categories/writing-on-github/

**Comment by ivg** [comment]
All underscores a substituted with dashes. If you plugin is named `your_plugin` then the name would be `your-plugin`. 
And please, learn, how to format code in github. It is really painful to read your issues.
