### ISSUE TITLE
Plugin name clash error when re-building multiple plugins

### ISSUE THREAD

**Issue by rvantonder** [BinaryAnalysisPlatform/bap#370]
With two plugins in the same directory.

Example code from #369:

`one.ml`
```ocaml
open Core_kernel.Std
open Bap.Std
open Format
include Self()

let () = Project.register_pass' (fun _ -> print_endline "Register 1")
```

`two.ml`
```ocaml
open Core_kernel.Std
open Bap.Std
open Format
include Self()

let () = Project.register_pass' (fun _ -> print_endline "Register 2")
```
Reproduce:
`$ bapbuild one.plugin; bapbuild two.plugin`
`$ bap -lone --one -ltwo --two /bin/ls` # works fine

Bapbuild again (with cache), and run, and it breaks:
```
$ bapbuild one.plugin; bapbuild two.plugin
Finished, 8 targets (6 cached) in 00:00:00.
Finished, 8 targets (6 cached) in 00:00:00.
```

```
bap -lone --one -ltwo --two /bin/ls
Failed with an unexpected exception: "failed to load plugin two: a name two clashes with a plugin one"
Backtrace:
Raised at file "src/error.ml", line 7, characters 20-30
Called from file "list.ml", line 73, characters 12-15
Called from file "src/core_list0.ml", line 405, characters 16-30
Called from file "src/bap_main.ml", line 222, characters 20-65
Called from file "src/bap_main.ml", line 238, characters 11-21
```

Other potential problem: specifying three or more plugins in the same directory crashes immediately, but there doesn't seem to be a name clash. Add a third plugin called `three.ml`, then:

```
$ bap -lone --one -ltwo --two -lthree --three /bin/ls
Register 2
Failed with an unexpected exception: "failed to load plugin three: a name one clashes with a plugin two"
Backtrace:
Raised at file "src/error.ml", line 7, characters 20-30
Called from file "list.ml", line 73, characters 12-15
Called from file "src/core_list0.ml", line 405, characters 16-30
Called from file "src/bap_main.ml", line 222, characters 20-65
Called from file "src/bap_main.ml", line 238, characters 11-21
```

**Comment by ivg** [comment]
Each plugin should be built in its own repository. Otherwise it is not easy (possible) to track its dependencies.

**Comment by rvantonder** [comment]
Fair enough, but we should make this explicit or error on these cases, because this is unpredictable behavior from the user point of view. They will see it worked the first time, but not afterwards.

**Comment by ivg** [comment]
Do you have any ideas how to catch this?

**Comment by rvantonder** [comment]
I double-checked that this error doesn't happen when every plugin is in its own directory, and it looks like this behavior is safe (for multiple plugins):

`make -C test1; make -C test2; make -C test3`
`bap -ltest1/one --one -ltest2/two --two -ltest3/three --three /bin/ls` #works
