### ISSUE TITLE
Tests failing from issues in disassembly

### ISSUE THREAD

**Issue by rvantonder** [BinaryAnalysisPlatform/bap#372]
I previously tested against the following code before the 0.9.9 PR:

`test1.c`
```c
#include<stdio.h>

int main() {
  int arr[100];
  int y = 1;
  arr[y] = 1;
}
```
Compile:
`arm-linux-gnueabi-gcc test1.c -O0 -o test1`

## Older bap (5e2a738d69b6 - Nov 16 2015)
```
bap -dbir test/test1 | wc -l
246
```
With ida:
```
bap --use-ida=idal --no-byteweight -dbir test/test1 | wc -l
546
```

## New bap (commit bb8a36e - Mar 14 2016)
With internal (since `bap -dbir` does nothing by default without byteweight symbols)
```
bap --symbols=internal --rooter=internal -dbir test/test1 | wc -l
163
```
With ida:
```
bap --symbols=ida --rooter=ida --no-byteweight -dbir test/test1 | wc -l
385
```

I don't really know what's going on. All I know is, I don't see the `main` function with newer bap, no matter what settings I use, but with old bap it saw it with and without Ida. I can include the IR output if it helps.

**Comment by ivg** [comment]
Ok, it looks like a bug in the recursive descent disassembler. It's kind of interesting how it slipped though all test cases, maybe it would be a good idea to add this as a test case for our test suite (and use test-expect for this). In any case, reproducible bug is a nearly fixed bug, stay in touch!

**Comment by rvantonder** [comment]
After fix, `main` is there (and other missing functions). There are still differences between this and the older disassembler from #5e2a738 (but it may be because new disassembler is more accurate). Will look into it.

After fix:
```
bap --symbols=internal --rooter=internal -dbir test/test1 | wc -l
211
bap --symbols=ida --rooter=ida --no-byteweight -dbir test/test1 | wc -l
427
```

**Comment by ivg** [comment]
There should be a difference, the disassembly level is severely rewritten. 

Also, `--symbols=X` is the same as `--symbolizer=X --rooter=X`, so there is no need to say `--symbols=X --rooter=X`. 

And `--rooter=internal` will disable byteweight, and will use only symbols available in symbol table (.symtab and .dyntab). To compare with `--no-ida
