### ISSUE TITLE
Remove plugins from bap without specifying `.plugin` extension

### ISSUE THREAD

**Issue by rvantonder** [BinaryAnalysisPlatform/bap#381]
When we list plugins with `--list-plugins`, there's no extension on the plugin names. But to remove a plugin currently, we always have to add the `.plugin` extension to the name. If we can match `<plugin-name>.plugin` and `<plugin-name>` without the extension, that would be helpful for users.

**Comment by ivg** [comment]
Then for the symmetry we should do the same for the `bapbuild install` command.
