### ISSUE TITLE
pshufd semantics bug

### ISSUE THREAD

**Issue by percontation** [BinaryAnalysisPlatform/bap#391]
There's a typo affecting the semantics of the pshufd instruction, e.g. `pshufd 0x1, %xmm0, %xmm1`.

The `lsl` should be a `lsr` on https://github.com/BinaryAnalysisPlatform/bap/blob/93ee72c0768a9a3692e48e599f1a72431d129e58/plugins/x86/x86_utils.ml#L39

**Comment by ivg** [comment]
@feseal, can you please also take a look on this issue?

**Comment by ivg** [comment]
fixed in #592.
