### ISSUE TITLE
Load .o files

### ISSUE THREAD

**Issue by maurer** [BinaryAnalysisPlatform/bap#402]
It is frequently useful to be able to analyze code without the large overhead of  the C runtime or other compiler generated template code.

To this end, I'd like to see loading of '.o' files added.

If this is going to take a while, I'd at least suggest replacing the SIGFPE generated when loading a .o with a clearer error message (e.g. "no segments found, perhaps you have passed in a non-located binary? (.o, .ko)")

**Comment by ivg** [comment]
You can load binary blobs, that doesn't have any structural information (e.g., no ELF or anything else), e.g.,
```
bap file --source-type=arm-code 
```

What concerning reading `.o` files, do you have any reference to a description of ELF `.o` files, what they really contain?

> If this is going to take a while, I'd at least suggest replacing the SIGFPE generated when loading a .o with a clearer error message (e.g. "no segments found, perhaps you have passed in a non-located binary? (.o, .ko)")

This happens deep in the LLVM backend. We can only check, that the file is ELF executable before we try to read it.

**Comment by uxmal** [comment]
ELF relocatable files (".o files ") are quite similar to ELF executables. Same data structures, for the most part. The big difference is that sections don't have addresses and there are no program segments. You need to "play linker" and allocate address ranges and decide which sections can be placed into the same segment.

Alas, I'm no Ocaml programmer, but you can look at the reko decompiler C# code for inspiration for how to deal with object code: https://github.com/uxmal/reko/blob/master/src/ImageLoaders/Elf/ElfObjectLinker.cs

**Comment by ivg** [comment]
@uxmal, thanks for the link!

**Comment by maurer** [comment]
The address space assignment is likely similar to the work you'll need to do for coming weeks w/regards to '.so' files anyways, so there may be some overlap here.
