### ISSUE TITLE
Weird order dependency in argument parsing by `bap` command line tool

### ISSUE THREAD

**Issue by maurer** [BinaryAnalysisPlatform/bap#403]
If you pass the filename after `--no-ida`, the command line arguments will not be accepted, but the help message will tell you to put the file in that position. Either the help message should change (instructing you to put file first) or the argument parsing code should tolerate the file argument in the last position.
```
maurer@pride:~/tmp$ bap triple --no-ida
maurer@pride:~/tmp$ bap --no-ida triple                                                           
bap: required argument FILE is missing
Usage: bap [OPTION]... FILE
Try `bap --help' for more information.
maurer@pride:~/tmp$
```

**Comment by ivg** [comment]
Sorry, this is a shortcomming of an argument parsing. It is highlighted in the `bap --help`. I can't change the usage message.
