### ISSUE TITLE
toil command not found anymore.

### ISSUE THREAD

**Issue by ririhedou** [BinaryAnalysisPlatform/bap#413]
Hi,

I have bap version 1.0.0-alpha. The bap and bapbuild runs correctly.
However, the toil command does not found any more.

what should i do to achieve the similar funtionality?
e.g.,
gcc -c basic.S -o basic.o
obdjump -d basic.o | less
toil -bin basic.o -o basic.il

**Comment by ririhedou** [comment]
One more question.
What should I do to achieve the trace functionality (section 5.4 in the handbook[1]) in bap?
[1]http://www.utdallas.edu/~kXh060100/cs6301fa15/bap.pdf

**Comment by ivg** [comment]
Hi,

To get IL output, use
```
bap basic -dbil
```
One caveat, is that we do not work with object files, only with real executables and libraries. See
```
bap --help
```
for more information about command line interface.

In general the new BAP has a pluggable architecture. We have a library and lots of plugins. And each new analysis or piece of functionality is added as a separate plugin. To get an idea what is available use:
```
bap --list-plugins
```
For example, we have a `trace` plugin, that can load and dump traces. You can use our [qemu](https://github.com/BinaryAnalysisPlatform/qemu) branch to record traces from `x86`, `x86-64` and `arm` binaries, or you can use the [pintool](https://github.com/BinaryAnalysisPlatform/bap-pintraces). For reading traces in the format, used by these tools, you need to install `bap-frames` plugin, with `opam install bap-frames`.

**Comment by ririhedou** [comment]
Hi,
Thanks for your help, I have a very simple c++ program:

`#include <iostream>
int main() 
{
    std::cout << "Hello\n";
} `

and then get hello executable:
`g++ hello.c -o hello`

I get the following output by running:
`bap hello -dbil > out.il`

{<
Disassembly of section .init

0000000000400600: <sub_400600>
0000000000400600:
0000000000400600: subq $0x8, %rsp
{
  v25 := RSP
  RSP := RSP - 0x8:64
  CF := v25 < 0x8:64
  OF := high:1[(v25 ^ 0x8:64) & (v25 ^ RSP)]
  AF := 0x10:64 = (0x10:64 & ((RSP ^ v25) ^ 0x8:64))
  PF := ~(low:1[let v26 = (RSP >> 0x4:64) ^ RSP in
    let v26 = (v26 >> 0x2:64) ^ v26 in
    (v26 >> 0x1:64) ^ v26])
  SF := high:1[RSP]
  ZF := 0x0:64 = RSP
}
0000000000400604: movq 0x2009ed(%rip), %rax
{
  RAX := mem64[(0x2009ED:64 + 0x40060B:64) + 0x0:64, el]:u64
}
000000000040060b: testq %rax, %rax
{
  v27 := RAX & RAX
  OF := false
  CF := false
  AF := unknown[AF is undefined after and]:u1
  PF := ~(low:1[let v28 = (v27 >> 0x4:64) ^ v27 in
    let v28 = (v28 >> 0x2:64) ^ v28 in
    (v28 >> 0x1:64) ^ v28])
  SF := high:1[v27]
  ZF := 0x0:64 = v27
}
000000000040060e: je 0x5
{
  if (ZF) {
    jmp 0x400615:64
  }
}
0000000000400610:
0000000000400610: callq 0x1b
{
  RSP := RSP - 0x8:64
  mem64 := mem64 with [RSP, el]:u64 <- 0x400615:64
  jmp 0x400630:64
}
0000000000400615:
0000000000400615: addq $0x8, %rsp
{
  v36 := RSP
  v37 := 0x8:64
  RSP := RSP + v37
  CF := RSP < v36
  OF := ((high:1[v36]) = (high:1[v37])) & ((high:1[v36]) ^ (high:1[RSP]))
  AF := 0x10:64 = (0x10:64 & ((RSP ^ v36) ^ v37))
  PF := ~(low:1[let v38 = (RSP >> 0x4:64) ^ RSP in
    let v38 = (v38 >> 0x2:64) ^ v38 in
    (v38 >> 0x1:64) ^ v38])
  SF := high:1[RSP]
  ZF := 0x0:64 = RSP
}
0000000000400619: ret
{
  v39 := mem64[RSP, el]:u64
  RSP := RSP + 0x8:64
  jmp v39
}

Disassembly of section .plt

0000000000400630: <sub_400630>
0000000000400630:
0000000000400630: jmpq *0x2009e2(%rip)
{
  jmp (mem64[(0x2009E2:64 + 0x400636:64) + 0x0:64, el]:u64)
}

0000000000400640: <sub_400640>
0000000000400640:
0000000000400640: jmpq *0x2009da(%rip)
{
  jmp (mem64[(0x2009DA:64 + 0x400646:64) + 0x0:64, el]:u64)
}

0000000000400660: <sub_400660>
0000000000400660:
0000000000400660: jmpq *0x2009ca(%rip)
{
  jmp (mem64[(0x2009CA:64 + 0x400666:64) + 0x0:64, el]:u64)
}

0000000000400680: <sub_400680>
0000000000400680:
0000000000400680: jmpq *0x2009ba(%rip)
{
  jmp (mem64[(0x2009BA:64 + 0x400686:64) + 0x0:64, el]:u64)
}

Disassembly of section .text

00000000004007d4: <_GLOBAL__sub_I_main>
00000000004007d4:
00000000004007d4: pushq %rbp
{
  v40 := RBP
  RSP := RSP - 0x8:64
  mem64 := mem64 with [RSP, el]:u64 <- v40
}
00000000004007d5: movq %rsp, %rbp
{
  RBP := RSP
}
00000000004007d8: movl $0xffff, %esi
{
  RSI := pad:64[0xFFFF:32]
}
00000000004007dd: movl $0x1, %edi
{
  RDI := pad:64[0x1:32]
}
00000000004007e2: callq -0x50
{
  RSP := RSP - 0x8:64
  mem64 := mem64 with [RSP, el]:u64 <- 0x4007E7:64
  jmp 0x400797:64
}
00000000004007e7:
00000000004007e7: popq %rbp
{
  RBP := mem64[RSP, el]:u64
  RSP := RSP + 0x8:64
}
00000000004007e8: ret
{
  v33 := mem64[RSP, el]:u64
  RSP := RSP + 0x8:64
  jmp v33
}

0000000000400797: <_Z41__static_initialization_and_destruction_0ii>
0000000000400797:
0000000000400797: pushq %rbp
{
  v20 := RBP
  RSP := RSP - 0x8:64
  mem64 := mem64 with [RSP, el]:u64 <- v20
}
0000000000400798: movq %rsp, %rbp
{
  RBP := RSP
}
000000000040079b: subq $0x10, %rsp
{
  v21 := RSP
  RSP := RSP - 0x10:64
  CF := v21 < 0x10:64
  OF := high:1[(v21 ^ 0x10:64) & (v21 ^ RSP)]
  AF := 0x10:64 = (0x10:64 & ((RSP ^ v21) ^ 0x10:64))
  PF := ~(low:1[let v22 = (RSP >> 0x4:64) ^ RSP in
    let v22 = (v22 >> 0x2:64) ^ v22 in
    (v22 >> 0x1:64) ^ v22])
  SF := high:1[RSP]
  ZF := 0x0:64 = RSP
}
000000000040079f: movl %edi, -0x4(%rbp)
{
  mem64 := mem64 with [RBP + 0xFFFFFFFFFFFFFFFC:64, el]:u32 <- low:32[RDI]
}
00000000004007a2: movl %esi, -0x8(%rbp)
{
  mem64 := mem64 with [RBP + 0xFFFFFFFFFFFFFFF8:64, el]:u32 <- low:32[RSI]
}
00000000004007a5: cmpl $0x1, -0x4(%rbp)
{
  v23 := (mem64[RBP + 0xFFFFFFFFFFFFFFFC:64, el]:u32) - 0x1:32
  CF := (mem64[RBP + 0xFFFFFFFFFFFFFFFC:64, el]:u32) < 0x1:32
  OF := high:1[((mem64[RBP + 0xFFFFFFFFFFFFFFFC:64, el]:u32) ^ 0x1:32) & ((mem64[RBP + 0xFFFFFFFFFFFFFFFC:64, el]:u32) ^ v23)]
  AF := 0x10:32 = (0x10:32 & ((v23 ^ (mem64[RBP + 0xFFFFFFFFFFFFFFFC:64, el]:u32)) ^ 0x1:32))
  PF := ~(low:1[let v24 = (v23 >> 0x4:32) ^ v23 in
    let v24 = (v24 >> 0x2:32) ^ v24 in
    (v24 >> 0x1:32) ^ v24])
  SF := high:1[v23]
  ZF := 0x0:32 = v23
}
00000000004007a9: jne 0x27
{
  if (~ZF) {
    jmp 0x4007D2:64
  }
}
00000000004007ab:
00000000004007ab: cmpl $0xffff, -0x8(%rbp)
{
  v29 := (mem64[RBP + 0xFFFFFFFFFFFFFFF8:64, el]:u32) - 0xFFFF:32
  CF := (mem64[RBP + 0xFFFFFFFFFFFFFFF8:64, el]:u32) < 0xFFFF:32
  OF := high:1[((mem64[RBP + 0xFFFFFFFFFFFFFFF8:64, el]:u32) ^ 0xFFFF:32) & ((mem64[RBP + 0xFFFFFFFFFFFFFFF8:64, el]:u32) ^ v29)]
  AF := 0x10:32 = (0x10:32 & ((v29 ^ (mem64[RBP + 0xFFFFFFFFFFFFFFF8:64, el]:u32)) ^ 0xFFFF:32))
  PF := ~(low:1[let v30 = (v29 >> 0x4:32) ^ v29 in
    let v30 = (v30 >> 0x2:32) ^ v30 in
    (v30 >> 0x1:32) ^ v30])
  SF := high:1[v29]
  ZF := 0x0:32 = v29
}
00000000004007b2: jne 0x1e
{
  if (~ZF) {
    jmp 0x4007D2:64
  }
}
00000000004007b4:
00000000004007b4: movl $0x601171, %edi
{
  RDI := pad:64[0x601171:32]
}
00000000004007b9: callq -0x17e
{
  RSP := RSP - 0x8:64
  mem64 := mem64 with [RSP, el]:u64 <- 0x4007BE:64
  jmp 0x400640:64
}
00000000004007be:
00000000004007be: movl $0x601050, %edx
{
  RDX := pad:64[0x601050:32]
}
00000000004007c3: movl $0x601171, %esi
{
  RSI := pad:64[0x601171:32]
}
00000000004007c8: movl $0x400670, %edi
{
  RDI := pad:64[0x400670:32]
}
00000000004007cd: callq -0x172
{
  RSP := RSP - 0x8:64
  mem64 := mem64 with [RSP, el]:u64 <- 0x4007D2:64
  jmp 0x400660:64
}
00000000004007d2:
00000000004007d2: leave
{
  RSP := RBP
  RBP := mem64[RSP, el]:u64
  RSP := RSP + 0x8:64
}
00000000004007d3: ret
{
  v32 := mem64[RSP, el]:u64
  RSP := RSP + 0x8:64
  jmp v32
}

000000000040077d: <main>
000000000040077d:
000000000040077d: pushq %rbp
{
  v31 := RBP
  RSP := RSP - 0x8:64
  mem64 := mem64 with [RSP, el]:u64 <- v31
}
000000000040077e: movq %rsp, %rbp
{
  RBP := RSP
}
0000000000400781: movl $0x400874, %esi
{
  RSI := pad:64[0x400874:32]
}
0000000000400786: movl $0x601060, %edi
{
  RDI := pad:64[0x601060:32]
}
000000000040078b: callq -0x110
{
  RSP := RSP - 0x8:64
  mem64 := mem64 with [RSP, el]:u64 <- 0x400790:64
  jmp 0x400680:64
}
0000000000400790:
0000000000400790: movl $0x0, %eax
{
  RAX := pad:64[0x0:32]
}
0000000000400795: popq %rbp
{
  RBP := mem64[RSP, el]:u64
  RSP := RSP + 0x8:64
}
0000000000400796: ret
{
  v18 := mem64[RSP, el]:u64
  RSP := RSP + 0x8:64
  jmp v18
}

000000000040081a: <sub_40081a>
000000000040081a:
000000000040081a: subq $0x8, %rsp
{
  v12 := RSP
  RSP := RSP - 0x8:64
  CF := v12 < 0x8:64
  OF := high:1[(v12 ^ 0x8:64) & (v12 ^ RSP)]
  AF := 0x10:64 = (0x10:64 & ((RSP ^ v12) ^ 0x8:64))
  PF := ~(low:1[let v13 = (RSP >> 0x4:64) ^ RSP in
    let v13 = (v13 >> 0x2:64) ^ v13 in
    (v13 >> 0x1:64) ^ v13])
  SF := high:1[RSP]
  ZF := 0x0:64 = RSP
}
000000000040081e: callq -0x223
{
  RSP := RSP - 0x8:64
  mem64 := mem64 with [RSP, el]:u64 <- 0x400823:64
  jmp 0x400600:64
}
0000000000400823:
0000000000400823: testq %rbp, %rbp
{
  v34 := RBP & RBP
  OF := false
  CF := false
  AF := unknown[AF is undefined after and]:u1
  PF := ~(low:1[let v35 = (v34 >> 0x4:64) ^ v34 in
    let v35 = (v35 >> 0x2:64) ^ v35 in
    (v35 >> 0x1:64) ^ v35])
  SF := high:1[v34]
  ZF := 0x0:64 = v34
}
0000000000400826: je 0x1e
{
  if (ZF) {
    jmp 0x400846:64
  }
}
0000000000400828:
0000000000400828: nopl (%rax,%rax)
{
  
}
0000000000400830:
0000000000400830: movq %r13, %rdx
{
  RDX := R13
}
0000000000400833: movq %r14, %rsi
{
  RSI := R14
}
0000000000400836: movl %r15d, %edi
{
  RDI := pad:64[low:32[R15]]
}
0000000000400839: callq *(%r12,%rbx,8)
{
  v19 := mem64[R12 + (RBX << 0x3:64), el]:u64
  RSP := RSP - 0x8:64
  mem64 := mem64 with [RSP, el]:u64 <- 0x40083D:64
  jmp v19
}
000000000040083d:
000000000040083d: addq $0x1, %rbx
{
  v7 := RBX
  v8 := 0x1:64
  RBX := RBX + v8
  CF := RBX < v7
  OF := ((high:1[v7]) = (high:1[v8])) & ((high:1[v7]) ^ (high:1[RBX]))
  AF := 0x10:64 = (0x10:64 & ((RBX ^ v7) ^ v8))
  PF := ~(low:1[let v9 = (RBX >> 0x4:64) ^ RBX in
    let v9 = (v9 >> 0x2:64) ^ v9 in
    (v9 >> 0x1:64) ^ v9])
  SF := high:1[RBX]
  ZF := 0x0:64 = RBX
}
0000000000400841: cmpq %rbp, %rbx
{
  v10 := RBX - RBP
  CF := RBX < RBP
  OF := high:1[(RBX ^ RBP) & (RBX ^ v10)]
  AF := 0x10:64 = (0x10:64 & ((v10 ^ RBX) ^ RBP))
  PF := ~(low:1[let v11 = (v10 >> 0x4:64) ^ v10 in
    let v11 = (v11 >> 0x2:64) ^ v11 in
    (v11 >> 0x1:64) ^ v11])
  SF := high:1[v10]
  ZF := 0x0:64 = v10
}
0000000000400844: jne -0x16
{
  if (~ZF) {
    jmp 0x400830:64
  }
}
0000000000400846:
0000000000400846: addq $0x8, %rsp
{
  v14 := RSP
  v15 := 0x8:64
  RSP := RSP + v15
  CF := RSP < v14
  OF := ((high:1[v14]) = (high:1[v15])) & ((high:1[v14]) ^ (high:1[RSP]))
  AF := 0x10:64 = (0x10:64 & ((RSP ^ v14) ^ v15))
  PF := ~(low:1[let v16 = (RSP >> 0x4:64) ^ RSP in
    let v16 = (v16 >> 0x2:64) ^ v16 in
    (v16 >> 0x1:64) ^ v16])
  SF := high:1[RSP]
  ZF := 0x0:64 = RSP
}
000000000040084a: popq %rbx
{
  RBX := mem64[RSP, el]:u64
  RSP := RSP + 0x8:64
}
000000000040084b: popq %rbp
{
  RBP := mem64[RSP, el]:u64
  RSP := RSP + 0x8:64
}
000000000040084c: popq %r12
{
  R12 := mem64[RSP, el]:u64
  RSP := RSP + 0x8:64
}
000000000040084e: popq %r13
{
  R13 := mem64[RSP, el]:u64
  RSP := RSP + 0x8:64
}
0000000000400850: popq %r14
{
  R14 := mem64[RSP, el]:u64
  RSP := RSP + 0x8:64
}
0000000000400852: popq %r15
{
  R15 := mem64[RSP, el]:u64
  RSP := RSP + 0x8:64
}
0000000000400854: ret
{
  v17 := mem64[RSP, el]:u64
  RSP := RSP + 0x8:64
  jmp v17

> }

**Comment by ivg** [comment]
If the answer is not sufficient, then feel free to reopen.
