### ISSUE TITLE
recompile when the ida path changes

### ISSUE THREAD

**Issue by dbrumley** [BinaryAnalysisPlatform/bap#428]
Currently the ida plugin uses `conf-ida`, which compiles in the path to ida. This has benefits, but has several costs.  
 - If compile picked up `idaq64`, but you are given an `idb`, that's a recompile because `idaq64` doesn't read 32-bit `idb` files. 
 - If you move ida, that's a recompile.
 - If you upgrade ida, which is by default a new path, you would silently keep using the old IDA with no option to change.  (Also, it's not clear how you would print out which one you were using to debug, but that may be a lack of understanding on my part.)
 - If you want to test out ida-6.8 and 6.9, that's a recompile every time you switch.

It seems like having an environment variable checked first --- or a configuration file hidden somewhere under `.opam` --- would allow for autoconfiguration on install, but still give flexibility. It would also mimic the concept supported by ida that you can have multiple versions installed.

@ivg is very much against this, and he can comment on why it's compiled in by default. However, I want a discussion item here to keep track if it bites other people.

**Comment by ivg** [comment]
I'm for adding support for multiple installation of IDA pro, and an ability to select at runtime a particular version of IDA or even particular bitness (but the latter is better to left for the library to decide). Something like, `--ida-version=6.9` and `--ida-bits=64` should be sufficient. 

I don't see any problems in reinstall `conf-ida` if you upgraded IDA, it takes a couple of seconds, and is not really often.

**Comment by rvantonder** [comment]
Sort of related: I just did a fresh install of bap from opam, without any ida. Then I installed ida. Then I installed ida-conf. If `sudo updatedb` hasn't been run, you'll (perhaps predictably) get:
```
[ERROR] The compilation of conf-ida failed at "sh -x find-ida.sh linux".

#=== ERROR while installing conf-ida.0.1 ======================================#
# opam-version 1.2.2
# os           linux
# command      sh -x find-ida.sh linux
# path         /home/vagrant/.opam/bap-switch/build/conf-ida.0.1
# compiler     4.02.3
# exit-code    1
# env-file     /home/vagrant/.opam/bap-switch/build/conf-ida.0.1/conf-ida-13691-7afd23.env
# stdout-file  /home/vagrant/.opam/bap-switch/build/conf-ida.0.1/conf-ida-13691-7afd23.out
# stderr-file  /home/vagrant/.opam/bap-switch/build/conf-ida.0.1/conf-ida-13691-7afd23.err
### stdout ###
# failed to locate IDA Pro
### stderr ###
# [...]
# + [ ]
# + locate_linux
# + locate -w -r idaq64$
# locate: can not stat () `/var/lib/mlocate/mlocate.db': No such file or directory
# + results=
# + [ -z ]
# + HEADLESS=true
# + [ -z ]
# + echo failed to locate IDA Pro
# + exit 1
```
Maybe we can just put a more informative message "Please run `sudo updatedb` first" or something like that.

**Comment by ivg** [comment]
Fixed with the new configuration infrastructure
