### ISSUE TITLE
`./configure --help` issue

### ISSUE THREAD

**Issue by jaybosamiya** [BinaryAnalysisPlatform/bap#438]
When trying something out, I decided to check the `./configure --help` but that doesn't work. On the other hand, doing a `./configure -help` (notice single hyphen there) does, which has this in the output:

```
[..snipped unnecessary options..]
  -help                      Display this list of options
  --help                     Display this list of options
```

Low priority issue, but it is there to be fixed nonetheless

**Comment by ivg** [comment]
I works and always worked, maybe you accidentally copied a string from a slack message sent someone on mac, as mac substitutes hyphens with a big dash, that is a different character. 

```
$ ./configure --help
configure options:
  --override var+val             Override any configuration variable.
  --enable-tests                 Compile tests executable and library and run them [default: disabled]
  --disable-tests                Compile tests executable and library and run them [default: disabled]
  --enable-docs                  Create documentations [default: enabled]
...
```

Please, confirm, that it works on your system too, so that we can close it.

**Comment by jaybosamiya** [comment]
Hmm... I was manually typing it in, and it still doesn't work on the repo that I was using. However, when I `git clone`d it again, then it started working. Weird, but seems like it is an issue on my end. Sorry for the noise.
