### ISSUE TITLE
how to use bap-byteweight?

### ISSUE THREAD

**Issue by fastbins** [BinaryAnalysisPlatform/bap#444]
I'm going to test bap-byteweight for my sample program and libc.

On my system, 
libc .so location : `/lib/x86_64-linux-gnu/libc-2.19.so`
libc .so debug symbol location : `/usr/lib/debug/lib/x86_64-linux-gnu/libc-2.19.so`

When I run `file /lib/x86_64-linux-gnu/libc-2.19.so` it shows
```
/lib/x86_64-linux-gnu/libc-2.19.so: ELF 64-bit LSB  shared object, x86-64, version 1 (SYSV), dynamically linked (uses shared libs), BuildID[sha1]=30c94dc66a1fe95180c3d68d2b89e576d5ae213c, for GNU/Linux 2.6.24, stripped
```
and run `file /usr/lib/debug/lib/x86_64-linux-gnu/libc-2.19.so`
```
/usr/lib/debug/lib/x86_64-linux-gnu/libc-2.19.so: ELF 64-bit LSB  shared object, x86-64, version 1 (SYSV), dynamically linked (uses shared libs), BuildID[sha1]=30c94dc66a1fe95180c3d68d2b89e576d5ae213c, for GNU/Linux 2.6.24, not stripped
```

but, when I run `bap-byteweight symbols file`, none of them shows the correct symbols.
`bap-byteweight symbols /lib/x86_64-linux-gnu/libc-2.19.so`
```
0x21C10:64 
0x21DD0:64 
0x21FB0:64 
0x21FC0:64 
0x223E0:64 
0x226E0:64 
0x22700:64 
0x22A70:64 
0x22C10:64 
0x23750:64 
...
```
`bap-byteweight symbols /usr/lib/debug/lib/x86_64-linux-gnu/libc-2.19.so`
```
0x0:64 
Outputted 1 symbols
```

And, I made a code-debug symbol file using eu-unstrip.
`eu-unstrip libc-2.19-stripped.so libc-2.19-dbgsym.so`
and when I run `bap-byteweight symbols libc-2.19-dbgsym.so` (non-stripped full libc .so file generate by eu-unstrip), It also doesn't show the correct symbols.

**Comment by ivg** [comment]
What makes you think that those symbols are incorrect? Just to clarify, byteweight ti an algorithm for finding functions entry points.

**Comment by fastbins** [comment]
I thought Byteweight could do recognize function names like IDA FLIRT. I misunderstood byteweight. Sorry.
