### ISSUE TITLE
Rooter issues

### ISSUE THREAD

**Issue by jaybosamiya** [BinaryAnalysisPlatform/bap#490]
Without `--rooter=ida`, due to internal rooter on a `.ko` file, we get

```
Failed to create a project: expected structural binary, got raw
```
when we run `bap --loader=ida --symbolizer=ida usbcore.ko -d`

**Comment by ivg** [comment]
So, it is easier to fix it by just ignoring (instead of raising an error) on one hand, on another hand, the fix would be inappropriate. If we are called with an explicit option to use `internal` symbolizer, an it fails, then this shouldn't be ignored.
