### ISSUE TITLE
--symbols option does not work as expected

### ISSUE THREAD

**Issue by rvantonder** [BinaryAnalysisPlatform/bap#496]
`bap --help`:

```
       --symbols=NAME
           Use NAME as rooter and symbolizer. This is a shortcut for
           --rooter=NAME --symbolizer=NAME.
```

`bap /bin/ls --rooter=ida --symbolizer=ida -d > foo`
`bap /bin/ls --symbols=ida -d > bar`
`diff foo bar`
Diff has a lot of differences. Looks like `--symbols` might only be using internal.

This is with byteweight signatures installed, and a separate issue from #495

**Comment by ivg** [comment]
yep, I will remove this option.
