### ISSUE TITLE
Symbols for debug binaries without IDA don't work

### ISSUE THREAD

**Issue by rvantonder** [BinaryAnalysisPlatform/bap#497]
This is a known issue we discussed internally. Previously, if bap was called with a debug binary, it would populate the correct symbols (`main`,...). The workaround suggested was to use `--symbolizer=internal`. Unfortunately, the workaround `--symbolizer=internal` does not seem to work.

**Comment by ivg** [comment]
It was fixed in #478, but it looks like that #492 breaks it somehow. Will see what happened. At least I can reproduce it.
