### ISSUE TITLE
"Error: Error during linking" with ubuntu_15.10_x64 & VMware

### ISSUE THREAD

**Issue by kiritoc8** [BinaryAnalysisPlatform/bap#515]
I have no idea about this question...But I really spend much time on installing bap...
=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
∗  installed result.1.2
∗  installed io-page.1.6.1
∗  installed topkg.0.7.6
∗  installed mirage-types.2.6.0
∗  installed mirage-types-lwt.2.6.0
∗  installed logs.0.6.1
∗  installed mirage-clock-unix.1.0.0
∗  installed mirage-profile.0.7.0
∗  installed channel.1.1.0
∗  installed shared-memory-ring.1.3.0
∗  installed mirage-unix.2.6.0
∗  installed mirage-console.2.1.3
∗  installed tcpip.2.7.0
∗  installed conduit.0.10.0
∗  installed cohttp.0.19.3
[ERROR] The compilation of bap failed at "make".
Processing 16/16: [bap: rm]
#=== ERROR while installing bap.0.9.9 =========================================#
 opam-version 1.2.2
 os           linux
 command      make
 path         /home/bap/.opam/4.02.1/build/bap.0.9.9
 compiler     4.02.1
 exit-code    2
 env-file     /home/bap/.opam/4.02.1/build/bap.0.9.9/bap-40699-27656f.env
 stdout-file  /home/bap/.opam/4.02.1/build/bap.0.9.9/bap-40699-27656f.out
 stderr-file  /home/bap/.opam/4.02.1/build/bap.0.9.9/bap-40699-27656f.err
 stdout ###
 [...]
 /home/bap/.opam/4.02.1/bin/ocamlfind ocamlopt -c -g -annot -bin-annot -short-paths -I lib/bap -I lib/bap_types -I lib/bap_image -I lib/bap_elf -I lib/bap_image -I lib/bap_dwarf -I lib/bap_image -I lib/bap_disasm -I lib/bap_disasm -I lib/bap_sema -I lib/bap -I lwt -syntax camlp4o -package bin_prot.syntax -package bitstring -syntax camlp4o -package bitstring.syntax -package camlp4 -package camlzip -package cohttp.lwt -syntax camlp4o -package comparelib.syntax -package core_kernel -package dynlink -syntax camlp4o -package enumerate.syntax -package ezjsonm -syntax camlp4o -package faillib.syntax -syntax camlp4o -package fieldslib.syntax -package fileutils -package findlib -syntax camlp4o -package herelib.syntax -package lwt -package lwt.log -package lwt.unix -package ocamlgraph -syntax camlp4o -package pa_ounit.syntax -package re -syntax camlp4o -package sexplib.syntax -package uri -package uuidm -syntax camlp4o -package variantslib.syntax -package zarith -I src/server -I lib/bap -I lwt -o src/server/start_server.cmx src/server/start_server.ml
 /home/bap/.opam/4.02.1/bin/ocamlfind ocamlopt -g -I lib/bap_image/ -I lib/bap_disasm -I lib/bap_disasm -linkpkg -package bin_prot.syntax -package bitstring -package bitstring.syntax -package camlp4 -package camlzip -package cohttp.lwt -package comparelib.syntax -package core_kernel -package dynlink -package enumerate.syntax -package ezjsonm -package faillib.syntax -package fieldslib.syntax -package fileutils -package findlib -package herelib.syntax -package lwt -package lwt.log -package lwt.unix -package ocamlgraph -package pa_ounit.syntax -package re -package sexplib.syntax -package uri -package uuidm -package variantslib.syntax -package zarith lib/bap_types/types.cmxa lib/bap/plugins.cmxa lib/bap_image/bap_image.cmxa lib/bap_disasm/disasm.cmxa lib/bap_disasm/llvm.cmxa lib/bap_dwarf/dwarf.cmxa lib/bap_elf/elf.cmxa lib/bap_image/elf_backend.cmxa lib/bap_image/llvm_loader.cmxa lib/bap_sema/sema.cmxa lib/bap/bap.cmxa lwt/core_lwt.cmxa src/server/adt.cmx src/server/list1.cmx src/server/transport.cmx src/server/file_fetcher.cmx src/server/http_service.cmx src/server/manager.cmx src/server/mmap_client.cmx src/server/mmap_server.cmx src/server/rpc.cmx src/server/server.cmx src/server/start_server.cmx -o src/server/start_server.native
 + /home/bap/.opam/4.02.1/bin/ocamlfind ocamlopt -g -I lib/bap_image/ -I lib/bap_disasm -I lib/bap_disasm -linkpkg -package bin_prot.syntax -package bitstring -package bitstring.syntax -package camlp4 -package camlzip -package cohttp.lwt -package comparelib.syntax -package core_kernel -package dynlink -package enumerate.syntax -package ezjsonm -package faillib.syntax -package fieldslib.syntax -package fileutils -package findlib -package herelib.syntax -package lwt -package lwt.log -package lwt.unix -package ocamlgraph -package pa_ounit.syntax -package re -package sexplib.syntax -package uri -package uuidm -package variantslib.syntax -package zarith lib/bap_types/types.cmxa lib/bap/plugins.cmxa lib/bap_image/bap_image.cmxa lib/bap_disasm/disasm.cmxa lib/bap_disasm/llvm.cmxa lib/bap_dwarf/dwarf.cmxa lib/bap_elf/elf.cmxa lib/bap_image/elf_backend.cmxa lib/bap_image/llvm_loader.cmxa lib/bap_sema/sema.cmxa lib/bap/bap.cmxa lwt/core_lwt.cmxa src/server/adt.cmx src/server/list1.cmx src/server/transport.cmx src/server/file_fetcher.cmx src/server/http_service.cmx src/server/manager.cmx src/server/mmap_client.cmx src/server/mmap_server.cmx src/server/rpc.cmx src/server/server.cmx src/server/start_server.cmx -o src/server/start_server.native
 lib/bap_image//libllvm_loader_stubs.a(bap_llvm_binary.o): In function `llvm_binary_fail(llvm::error_code const&)':
 /home/bap/.opam/4.02.1/build/bap.0.9.9/_build/lib/bap_image/bap_llvm_binary.hpp:21: undefined reference to `llvm::error_code::message() const'
 collect2: error: ld returned 1 exit status
 File "caml_startup", line 1:
 Error: Error during linking
 Command exited with code 2.
 Makefile:7: recipe for target 'build' failed
 stderr ###
 make: *** [build] Error 1

=-=- Error report -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
The following actions failed
  ∗  install bap 0.9.9
The following changes have been performed
  ∗  install channel            1.1.0 
  ∗  install cohttp             0.19.3
  ∗  install conduit            0.10.0
  ∗  install io-page            1.6.1 
  ∗  install logs               0.6.1 
  ∗  install mirage-clock-unix  1.0.0 
  ∗  install mirage-console     2.1.3 
  ∗  install mirage-profile     0.7.0 
  ∗  install mirage-types       2.6.0 
  ∗  install mirage-types-lwt   2.6.0 
  ∗  install mirage-unix        2.6.0 
  ∗  install result             1.2   
  ∗  install shared-memory-ring 1.3.0 
  ∗  install tcpip              2.7.0 
  ∗  install topkg              0.7.6 

=-=- bap.0.9.9 troobleshooting =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
=> This package relies on external (system) dependencies that may be missing.
   `opam depext bap.0.9.9' may help you find the correct installation for your
   system.

The former state can be restored with:
    opam switch import "~/.opam/4.02.1/backup/state-20160613074309.export"

**Comment by ivg** [comment]
Currently, we support only LLVM-3.4, a support for the newer  version is coming soon. At the moment try to install an older version, or switch to Ubuntu Trusty

**Comment by kiritoc8** [comment]
thanks for your advice！use "opam install 'conduit=0.10.0' bap.0.9.9" is ok!
