### ISSUE TITLE
Function name

### ISSUE THREAD

**Issue by zl1300012994** [BinaryAnalysisPlatform/bap#527]
I've already got the BIL intermediate language, but how do I know what function I use in BIL? Such as free.
                                                                                                                            Thank you~

**Comment by ivg** [comment]
You should look at the address of a jump statement. In the Intermediate Representation (IR) you can find a `call` term, e.g., `bap /bin/ls -d | grep call`. Resolving call targets is not a trivial task in general, as different compilers use different schemes of dynamic linking. You can use IDA or objdump to help BAP in finding proper names for addresses, e.g.:
```
$ bap /bin/ls --symbolizer=objdump -d | grep call | grep free
00000a7a: call @free with return %00000a7b
00000a80: call @free with return %00000a81
00000a85: call @free with return %00000a86
00000a8a: call @free with return %00000a8b
...
```

**Comment by zl1300012994** [comment]
I just couldn't run  “symbolizer”.Why?
The input is :
bap /bin/ls --symbolizer=objdump -d | grep call | grep free
The output is:
bap: unknown option `--symbolizer', did you mean `-s' ?

**Comment by ivg** [comment]
> I just couldn't run “symbolizer”.Why?

Because you're using bap 0.9.x, and I'm talking about bap 1.0.0-alpha that is currently available only via our opam repository. The  0.9.x can only use ida as a symbolizer, with `--use-ida` option. Of course, this requires you to have IDA installed.

To get the latest bap use
```
opam repository add bap git://github.com/BinaryAnalysisPlatform/bap.git
opam install bap
```

**Comment by zl1300012994** [comment]
How do I use BAP to run the.Frames file？
My output is :Exiting because ("create image" (llvm (path (12594-trace.frames)))).

**Comment by ivg** [comment]
`12594-trace.frames` is not a binary but a file that contains a trace of execution. This trace can be loaded with `--trace-load` option. Alternatively, you can view the tracedump with `--trace-dump` option. See `--trace-help` for more information.
