### ISSUE TITLE
Does BAP taint analysis work on Windows?

### ISSUE THREAD

**Issue by pfsun** [BinaryAnalysisPlatform/bap#533]
I just wonder whether bap taint analysis support executable on Windows? Thanks

**Comment by ivg** [comment]
Yep, if you will manage to install bap for windows. All code is believed to be cross-platform. But I, personally, never tried to install it on Windows.

**Comment by pfsun** [comment]
Thanks. I need to install bap by opam. It looks that opam doesn't have windows version.

**Comment by occia** [comment]
Although we can't install BAP directly on Windows,we can analyze PE file and exes' Pin traces on BAP which installed in an Unix-like system,is my understanding right? @ivg

**Comment by XVilka** [comment]
@pfsun there are certain problems with opam and OCaml in general on Windows platform.

See this bug for more information https://github.com/ocaml/opam/issues/2191

**Comment by ivg** [comment]
@occia, yep we can analyze PE files. I never tried to run pintool on PE binary, but I expect, that it should work.

**Comment by ivg** [comment]
There're opam installers for windows:
* [protz](http://protz.github.io/ocaml-installer/)
* [fdopen](https://fdopen.github.io/opam-repository-mingw/)

It is also possible to have [cross opam](https://github.com/whitequark/opam-cross-windows) installed on linux host, that builds for windows.
