### ISSUE TITLE
Why do we need both BIL & IR

### ISSUE THREAD

**Issue by occia** [BinaryAnalysisPlatform/bap#534]
In this [doc](http://binaryanalysisplatform.github.io/bap/api/master/Bap.Std.html) ,it tells me in **Disassembly Layer** will **lift the binary into BIL** and in **Semantic Analysis Layer** will **transform the binary into IR**.IR is flatter than BIL. 
All the other out-of-date docs (e.g.  [BAP2011](https://users.ece.cmu.edu/~ejschwar/papers/cav11.pdf) [The BAP Handbook](http://www.utdallas.edu/~kXh060100/cs6301fa15/bap.pdf)) only mentions BIL.And IR seems like the BIL in old docs.
So,why we need 2 intermediate language?From the view of dynamic taint analysis & symbolic execution towards binary,I think IR or BIL in old docs is enough.**Why new BIL**? BTW**,is IR exactly equals to BIL in old docs**?
I know maybe it is a stupid question,and any help is highly appreciated,thanks!

**Comment by ivg** [comment]
There is only one language, that is called BIL (that now stands for BAP Instruction Language). A language can be represented in a machine in different form, as a sequence of characters, as AST (Abstract Syntax Tree) or as a CFG (Control Flow Graph), etc. The BIR (BAP Intermediate Representation) is a semigraphical representation of BIL. The representation is richer, than the AST, as it allows to attach an arbitrary attributes, and express inter-procedural relations more precisely. 

Depending on your task, you might find that one representation is better than another. For example, it is easy to perform type inference on AST, but for dataflow you need CFG. 

So there are no new BIL. In comparison with the old releases, the language was slightly changed. It is formally specified [here](https://github.com/BinaryAnalysisPlatform/bil/releases/download/v0.1/bil.pdf).

**Comment by occia** [comment]
Oh.thank you,it really helps.I'm trying to get it work this days.And I think the doc part maybe need some reinforcement.Anyway,thanks a lot!

**Comment by occia** [comment]
Sorry to reopen it.I want to know that if there is some example about using IR?Like [example for BIL ](http://binaryanalysisplatform.github.io/bil-visitor-mappers/) did.
I need to do DTA & SE on the trace file collecting from bap/pintraces,so IR seems a better choice according to your doc.Is there some IR visitors or mappers ,or I have to use BIL visitors first and then do lift and analysis in BIL block or insn iteration?

**Comment by ivg** [comment]
Sorry, didn't notice your followup. Yes, there are [IR visitors and mappers][1], namely `Term.visitor` and `Term.mapper`, that are derived from corresponding `Exp` visitor and mapper, so their usage pattern should be the same.

[1]: https://github.com/BinaryAnalysisPlatform/bap/blob/master/lib/bap/bap.mli#L5470
