### ISSUE TITLE
Issue with load_segments()

### ISSUE THREAD

**Issue by abarbaro** [BinaryAnalysisPlatform/bap#535]
Hi all,
I have installed bap 0.9.7 because with bap 0.9.9 i have troubles. I'm trying to using it against a really simple ELF file but I have this error:

File "/usr/local/lib/python2.7/dist-packages/bap/bap.py", line 128, in load_segments
    self.segments = [Segment(s, self) for s in ss]
TypeError: 'NoneType' object is not iterable

the C of the ELF file is just:

int main() {
	int a = 0;
	if ( a > 5 )
		a  = 3;
	else
		a = 1;
	return a;
}

and as a python code I use:

>>> import bap
>>> img = bap.image("./examples/first")
>>> img.segments

Am i using the wrong python bindings?

Thanks

**Comment by ivg** [comment]
Can you upload the file? 

> Am i using the wrong python bindings?

Nope. 

P.S. Sorry for the late reply, I'm on vacations with scarce access to the Internet.

**Comment by abarbaro** [comment]
Hi,
you can find the file here: http://s000.tinyupload.com/?file_id=00771395349615943872

However i tried bap also against /bin/ls and I have the same problem.

Thanks for your help.

**Comment by abarbaro** [comment]
[easy.zip](https://github.com/BinaryAnalysisPlatform/bap/files/412677/easy.zip)

Hi,
sorry for the late response, this is the file I used.

Thanks

**Comment by ivg** [comment]
Ok, so I'm back from vacations. It looks like that there was some bug at this version. I don't think that it would be rationale to fix it, since 0.9.7 is a beta version. I will try now, to revive python binding for the latest alpha version (see #380).

**Comment by ivg** [comment]
Status update: I was able to revive the bindings, and it works for the latest version of bap. I will pack everything nicely into opam and pip tomorrow.

**Comment by ivg** [comment]
The python bindings are revived and fully working. I will continue the work and try to expose more functionality before the release. Meantime, to get an access to 1.0.0~alpha version of bap, please do the following:

1. add our opam-repository

 ```
   opam repo add bap git://github.com/BinaryAnalysisPlatform/opam-repository.git
```
2. install bap

 ```
opam install bap
```
3. install `bap-server` optional component, required for bap-python bindings

 ```
opam install bap-server
```
4. install the `bap-python` bindings using pip

 ```sh
pip install git+git://github.com/BinaryAnalysisPlatform/bap-python.git # add sudo to taste
```

If you have any problems, please don't hesitate to contact me.

**Comment by ivg** [comment]
I've updated our python bindings and released the to pypi. See [bap-python](https://github.com/BinaryAnalysisPlatform/bap-python) repository for more information. 

Btw, if you're interested in BAP, feel free to attend our [partners conference](https://www.cylab.cmu.edu/news_events/events/2016/partners-conference.html). There will be a workshop dedicated to BAP.
