### ISSUE TITLE
Regression: comments attribute not printed in IR output

### ISSUE THREAD

**Issue by rvantonder** [BinaryAnalysisPlatform/bap#539]
`bap /bin/true --print-bir-attr=comment -dbir` doesn't annotate IR output with comments. `set_attr` and `get_attr` work, but printer seems to ignore it.

Tested with plugin:

```ocaml
open Core_kernel.Std
open Bap.Std
open Format
include Self ()

class map_comments = object(self)
  inherit Term.mapper as super

  method! map_term cls t =
    super#map_term cls t |> fun t ->
    Term.set_attr t comment "foo"
end

class visit_comments = object(self)
  inherit [unit] Term.visitor as super

  method! enter_term cls t _ =
    super#enter_term cls t () |> fun _ ->
    match Term.get_attr t comment with
    | Some c -> printf "Term has comment %s@." c
    | None -> ()
end

let print_comments prog =
  let visitor = new visit_comments in
  visitor#run prog ()

let main proj =
  let mapper = new map_comments in
  let prog = Project.program proj in
  let prog' = mapper#run prog in
  print_comments prog';
  Project.with_program proj prog'

let () = Project.register_pass main
```

**Comment by ivg** [comment]
Didn't you forget to actually run your plugin? As it works for me. I dumped your code into file named `comms.ml` then did the following:

```
$ bapbuild comms.plugin
$ bap /bin/true -lcomms --comms -d --print-bir-attr=comment  | grep -e '^.comment foo$' | wc --lines
7361
```

Moreover, it is impossible for this thing to break, as all attributes are handled equally.

**Comment by rvantonder** [comment]
I didn't forget to run it. I did a fresh reinstall and cleared cache and now it works (even the `filename` attribute works for me before, that didn't work). I suspect some caching issue (that I caused myself?) but can't seem to replicate. Will open another issue if this happens again.

**Comment by ivg** [comment]
Nope, it can't be the caching issue, so please don't blame the cache :) Passes are not cached at all. And printing is not cached. So it can't be affected by the cache. It is something else. Maybe you misspelled something.

**Comment by rvantonder** [comment]
Ok. But I am not crazy :) Then it is something else, I'll see if it comes up again.
