### ISSUE TITLE
quetions about build BAP & BAP Plugin

### ISSUE THREAD

**Issue by occia** [BinaryAnalysisPlatform/bap#555]
**Q1**. According to [build wiki](https://github.com/BinaryAnalysisPlatform/bap/wiki/Build-tips-and-tricks),I use the following instructions to build BAP.
```
git clone https://github.com/BinaryAnalysisPlatform/bap.git
cd bap
./configure
```
And got.
```
File "setup.ml.in", line 153, characters 8-27:
Error: This pattern matches values of type 'a * 'b * 'c * 'd
       but a pattern was expected which matches values of type
         OASISTypes.common_section * OASISTypes.build_section *
         OASISTypes.library
```
I know build it from source isn't the recommended way to use BAP,and I just want to make sure I can modify the source and build it.

**Q2**. In the [build_plugins.sh](https://github.com/BinaryAnalysisPlatform/bap/blob/master/tools/build_plugins.sh),you always create an empty **$plugin.ml** and use it to build plugin,is it just an wrapper to wrap the **bap-plugin-$plugin** lib ?

**Q3**. Actually plugin file format is bundle,and bundle format file's extension suffix is ".plugin",it is Zip packed,stores infos and binaries about the plugin,**bapbundle** is its util tool,and loading a plugin totally means unpacking the bundle file,geting info,dynamic loading binaries,right?

Any help is highly appreciated,thanks!

**Comment by ivg** [comment]
**A1.** You have an outdated version of oasis. You need [oasis.0.4.7][1] to build bap. Also, just running `./configure` will not make big sense. You need to specify which features you would like to enable (by default everything is disabled). You can enable everything with `--enable-everything` argument. See the corresponding [configure][2] clause in the opam file.

**A2.** Yep, this is just a convenient method to automatize plugin's building process.  It is not required. 

**A3**. Yes it is zip, that contains meta information, the shared libraries (in byte and native code), static information, and, optionally, dependencies. `bapbundle` is a wrapper around zip. It is quite similar to `jar`. When we load a plugin, we unpack it, look at the depend load the dependencies in the META, load the unsatisfied dependencies, then finally load the bundle, which is (in the native mode) is a shared library (.so in linux), that has a special symbol, that is called after the plugin is loaded. This symbol will evaluate all top-level expressions in modules, that were linked into the plugin.


[1]: https://github.com/BinaryAnalysisPlatform/bap/blob/master/opam/opam#L150
[2]: https://github.com/BinaryAnalysisPlatform/bap/blob/master/opam/opam#L11

**Comment by occia** [comment]
For A1,I update my opam & oasis , and I can run make successfully.It still has something need to solve but I think I can figure it out if I really need rebuild BAP,so thanks.
For 2&3,thanks again : ).
And there is one more thing, I can use bapbuild xxx.native to build a standalone version exe using bap as a lib.But in this case,I can't use other plugins' utilities,e.g.if I use Disasm.of_mem,I will get the following.
```
$ ./test.native 
Uncaught exception:
  
  "Unknown backend: llvm"

Raised at file "src/error.ml", line 7, characters 20-30
Called from file "test.ml", line 17, characters 15-56
Called from file "test.ml", line 31, characters 17-35
Called from file "test.ml", line 45, characters 9-16
```
Seems that llvm plugin hasn't be loaded.And everything is ok if I use test as a BAP plugin.Does this means,use it as a plugin is the only way to use multiple plugins,no workaround?

**Comment by ivg** [comment]
There is no workaround, but there is a straight way :) Of course, you can write your own standalone application, that uses bap library and loads all plugins. Usually, it is recommended to use `oasis` to build such applications, but you can also use `bapbuild` for simple cases. Every frontend must be linked with `findlib.dynload` (a knowledge that we should definitely document somewhere), e.g.,
```
$ bapbuild -pkg findlib.dynload test.native
```

You will also need to write some support code, to actually load the plugins. The plugin interface is controlled by the `bap.plugins` library. (I forgot to add it to the documentation index, but it can be found by typing `Bap_plugins` in the search entry of [the documentation][1]). Open `Bap_plugins.Std`  before you start using the library.  You can load all plugins using `Plugins.run` or `Plugins.load` function. Or you can load individual plugins using `Plugin.load`. 


[1]: file:///home/ivg/factory/bap/doc/argot_index.html

**Comment by occia** [comment]
Oh,sorry,stupid question. I ignored that Bap.Std is really a lib and the bap exe is some kind of a wrapper to it,it load plugins from [here](https://github.com/BinaryAnalysisPlatform/bap/blob/master/src/bap_main.ml#L256).Thanks very much for your patience.
