### ISSUE TITLE
BAP dependencies may have problems on OSX El Capitan

### ISSUE THREAD

**Issue by dbrumley** [BinaryAnalysisPlatform/bap#563]
When installing BAP 1.0.0-alpha from a clean macport, I ran into a bug where ` i386-mingw32-binutils` would not install due to a compile error. It appears to be this error: https://trac.macports.org/ticket/49386

The remedy was:
```
sudo rm /opt/local/include/ansidecl.h 
sudo port clean i386-mingw32-binutils
sudo port install i386-mingw32-binutils
```
This is clearly not a good/recommended solution, but is a solution.

**Comment by dbrumley** [comment]
The following works:
```
port install i386-mingw32-binutils arm-aout-binutils arm-elf-binutils arm-none-eabi-binutils binutils gmp i386-elf-binutils libzip llvm-3.4 x86_64-elf-binutils
```
Note that the difference is `i386-mingw32-binutils` is *first*.

**Comment by dbrumley** [comment]
I tried it on a fresh macports. I deleted everything under `/opt/local`, installed `opam`, and it failed on depext because of order.  The link in my message explains why it would fail: binutils has a conflicting header file found in the search path compared to mingw, so installing mingw first solves the problem.

**Comment by ivg** [comment]
Fixed by BinaryAnalysisPlatform/opam-repository#11

**Comment by dbrumley** [comment]
Did you verify this fixes the issue, or is it an assumption that removing the package will fix it?

**Comment by ivg** [comment]
Sure I did.

**Comment by ivg** [comment]
> assumption that removing the package will fix it?

I didn't remove any packages.
