### ISSUE TITLE
LLVM plugin cannot be used as a library

### ISSUE THREAD

**Issue by maurer** [BinaryAnalysisPlatform/bap#570]
Linking plugins in ahead of time instead of loading them should register any backends they provide, avoiding the need for configuration files/META when bap is used as a library in another application.

Currently, the LLVM plugin does not register itself when linked this way, because it [delays registration utnil it receives a configuration](https://github.com/BinaryAnalysisPlatform/bap/blob/master/plugins/llvm/llvm_main.ml#L7-L23).

**Comment by ivg** [comment]
yep, this was a temporary workaround before #512 is merged. Probably we should force this PR to be finished and merged.

**Comment by ivg** [comment]
The reported issue is not a bug, but an intended behavior. I doubt, that in the future things will become better, and actually expect the opposite. I will elaborate on the dependent maurer/libbap#4 issue.
