### ISSUE TITLE
Bitvector asr operator issue

### ISSUE THREAD

**Issue by occia** [BinaryAnalysisPlatform/bap#582]
In 1.0.0~alpha BAP,I find that there maybe has an implementation error in asr's functionality.In baptop,I get the strange following results.

    utop # let x1 = Word.of_int ~width:32 (-1) ;;
    val x1 : word = 0xFFFFFFFF:32
    utop # let x2 = Word.of_int ~width:32 0x2;;
    val x2 : word = 0x2:32
    utop # let x = Word.(x1 asr x2);;
    val x : word = 0x3FFFFFFF:32 
    utop # let x = Word.(x1 lsr x2);;
    val x : word = 0x3FFFFFFF:32 

**Asr**has the same result as **lsr**,and things didn't change if I use the following x1 value.

    utop # let x1 = Word.of_int ~width:32 (0xffffffff) ;;
    val x1 : word = 0xFFFFFFFF:32
    utop # let x2 = Word.of_int ~width:32 0x2;;
    val x2 : word = 0x2:32
    utop # let x = Word.(x1 asr x2);;
    val x : word = 0x3FFFFFFF:32 
    utop # let x = Word.(x1 lsr x2);;
    val x : word = 0x3FFFFFFF:32 

As I know, **asr** operator equals to the assembly instrution **sar**,it means **arithmetic bit shift**,so the result should be 0xFFFFFFFF:32.But why it behaves totally the same as logic shift operator **lsr**?Is this my error or BAP's?

Any help is highly appreciated,thanks!

**Comment by ivg** [comment]
You are totally right, `asr` of the minus one should be minus one for any length of the shift. The operation wasn't properly lifted, and  the sign of the operand was ignored (thus it was actually equivalent to the logical shift). Strange, that the error wasn't caught by our test suites, looks like that arithmetic shift right is not a very popular instruction. I will update the testuite and push the fix in few minutes.
