### ISSUE TITLE
the llvm plugin is broken after an update

### ISSUE THREAD

**Issue by Dinatrix** [BinaryAnalysisPlatform/bap#611]
Hi!

I previously tried 'opam install bap.1.0.0' which did not seem to include 'bap-ida'. Typing 'opam install bap-ida.1.0.0' makes opam try to upgrade all other components to 1.1.0. After saying yes and upgrading the suggested components to version 1.1.0, I loaded a binary into IDA and pressed Shift+P but received an error:

" loader.error> Failed to load plugin ""llvm": Failed to load llvm_plugin: error loading shared library: /tmp/llvm_plugin4cfd71.cmxs: undefined symmbol: setupterm
Failed to create a project: no such backend: '<no-loaders-available>' "

I also attempted to press Shift+S, entering '--saluki' and then 'saluki' as well as '--warn-unused --warn-unused-mark' & 'dead', which still produce the above outcome.

Should I reinstall a different version of bap-llvm to solve this issue?

**Comment by ivg** [comment]
First of all, BAP 1.0.0 does include IDA integration however it probably will not ease your situation, as the problem doesn't depend on the IDA integration suite or on even (I hope) on a version of BAP. However, it might depend on a version of llvm. 

The error message indicates, that the llvm plugin has unresolved symbols (from `libcurses`, so I can conclude, that on your system the `llvm-config` binary, for some reason, didn't tell us to link with the curses library. (Alternatively it might be the case, that gcc/clang on your system are tinkered, and ignore link flags for some reason).

So, I need to know the following details:

* Your OS (`uname -a`)
* Your llvm-version (`opam config var conf-bap-llvm:version` or, `opam config var conf-llvm:version`)
* Your gcc/clang++ versions


If you're using a virtual machine with some well known image or just downloadable image (e.g., a vagrant box), then please give me a link to it.

Furthermore, to fasten the investigation, would you mind to provide the output of the `llvm-config` that was used on your system (usually it is `llvm-config-<VER>, where `<VER>` is either `3.8` or `3.4`). Basically, `llvm-config-3.4 --ldflags` and `llvm-config-3.8 --system-libs` should both report `-lcurses`

**Comment by Dinatrix** [comment]
Thanks for getting back to me so quickly!

- Linux (name) 4.2.0-27-generic #32~14.04.1-Ubuntu SMP Fri Jan 22 15:32:26 UTC 2016 x86_64 x86_64 GNU/Linux

- '#undefined' and ' ' (blank)

- 'gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04.3)' and 'Ubuntu clang version 3.4-1ubuntu3 (tags/RELEASE_34/final) (based on LLVM 3.4)'

It is a VM with Ubuntu 14.04 (http://www.osboxes.org/ubuntu-14-04-trusty-images-for-virtualbox-vmware/)

- llvm-config-3.4 --ldflags = -L/usr/lib/llvm-3.4/lib -lpthread -lffi -ltinfo -ldl -lm

- llvm-config-3.8 --system-libs = -lrt -ldl -ltinfo -lpthread -lz -lm

Additionally, I am running IDA Version 6.9.160222

Thanks again!

**Comment by ivg** [comment]
Well, I'm using basically the same setup (same, llvm-config outputs and gcc version, except that the kernel version is older, but I hope that it is irrelevant). The output of the `llvm-config-*` is correct (the `-ltinfo` should provide the missing library).  

The only suspicious place is the `conf-llvm` version. If you were installing from opam, then either `conf-llvm` or `conf-bap-llvm` package should be automatically installed. Please, make sure that you didn't misspelled the commands that I've provided (I just copy-pasted them two mine machines and the showed versions for both cases). 

If your installation is somehow customized, then can you please provide details. 

Alternatively, you can try to reinstall bap from scratch by creating a new compiler switch, e.g.,

```
opam switch fresh -A4.03.0
eval `opam config env`
opam install bap
```

**Comment by Dinatrix** [comment]
After the new compiler switch didn't work on the VM I was working in, I ended up installing bap from scratch on a different VM which worked. I'm not sure why going from 1.0.0~alpha to trying 1.0.0 and then 1.1.0 was failing, but I have a working bap.1.1.0 now :) Thanks for all the help!

**Comment by ivg** [comment]
> I'm not sure why going from 1.0.0~alpha to trying 1.0.0 and then 1.1.0 was failing

This is probably some bug in opam or ubuntu itself. Maybe some caching issues. I've renamed the issue, to make it more searchable, in case if the problem recurs. 

Good luck!
