### ISSUE TITLE
Cannot install bap-llvm

### ISSUE THREAD

**Issue by ted42** [BinaryAnalysisPlatform/bap#614]
I'm having a problem installing bap 1.1.0 on Debian 8.
I tried running `opam depext --install bap` But that wouldn't work because of 
```
opam: unknown command `depext'
```
Then I tried running `opam install bap`, but this failed because it can not compile bap-llvm:
```
plugins/llvm/llvm_binary.hpp:96:17: error: use of undeclared identifier 'load_commands'
plugins/llvm/llvm_binary.hpp:109:27: error: use of undeclared identifier 'getImageBase'
plugins/llvm/llvm_binary.hpp:110:20: error: use of undeclared identifier 'sections'
plugins/llvm/llvm_binary.hpp:137:17: error: use of undeclared identifier 'name_or_default'
plugins/llvm/llvm_binary.hpp:138:17: error: use of undeclared identifier 'addr_or_default'
plugins/llvm/llvm_binary.hpp:139:17: error: use of undeclared identifier 'get_type'
plugins/llvm/llvm_binary.hpp:144:17: error: use of undeclared identifier 'name_or_default'
plugins/llvm/llvm_binary.hpp:145:17: error: use of undeclared identifier 'get_type'
plugins/llvm/llvm_binary.hpp:151:25: error: use of undeclared identifier 'getSymbolSizes'
plugins/llvm/llvm_binary.hpp:159:25: error: use of undeclared identifier 'getSymbolSizes'
plugins/llvm/llvm_binary.hpp:189:17: error: use of undeclared identifier 'getName'; did you mean 'getdate'?
plugins/llvm/llvm_binary.hpp:189:25: error: no viable conversion from 'const llvm::object::SectionRef' to 'const char *'
plugins/llvm/llvm_binary.hpp:190:17: error: use of undeclared identifier 'getAddr'
plugins/llvm/llvm_binary.hpp:191:17: error: use of undeclared identifier 'getSize'
plugins/llvm/llvm_binary.hpp:197:17: error: use of undeclared identifier 'getName'; did you mean 'getdate'?
plugins/llvm/llvm_binary.hpp:197:25: error: no viable conversion from 'const llvm::object::coff_section' to 'const char *'
plugins/llvm/llvm_binary.hpp:198:17: error: use of undeclared identifier 'getAddr'
plugins/llvm/llvm_binary.hpp:199:17: error: use of undeclared identifier 'getSize'
plugins/llvm/llvm_binary.hpp:206:21: error: use of undeclared identifier 'obj_sections'
```

Am I missing some dependencies or is this a bug in bap?

System information:
```
#uname -a
Linux dnb 3.16.0-4-amd64 #1 SMP Debian 3.16.36-1+deb8u2 (2016-10-19) x86_64 x86_64

#opam config var conf-bap-llvm:version
3.5.0
```

**Comment by ivg** [comment]
Looks like you have a very old opam version, that doesn't support installing external dependencies. Try to get something newer, e.g., 1.2+

You will also need to obtain llvm 3.4 or 3.8, these are the versions that we support.

**Comment by ted42** [comment]
Thanks!
I managed to upgrade my opam installation to 1.2.2 but haven't figured out yet how to upgrade my llvm installation without breaking everything.

**Comment by ivg** [comment]
The good news is that in Ubuntu several versions of LLVM library can safely coexist and work with BAP. I believe that the same should be true for Debian. 

We can try to figure out what went wrong in your case, but it would be much easier to just install everything from scratch. For this we will create a new opam switch with a fresh new compiler and an empty set of packages, and then we will let opam to decide everything for us and hope that it will work (if it will not then we have plan B). For plan A to work, we need either `llvm-config-3.4` or `llvm-config-3.8` program available in the PATH. If they are not, then you can tell opam where to search it using an environment variable `LLVM_CONFIG` that should an executable name, e.g., if `llvm-config-3.4` in Debian is named `llvm-config-3.4.120+debian` then just run `export LLVM_CONFIG=llvm-config-3.4.120+debian` before the BAP installation (the variable is not needed for the runtime, just for the configuration).  So here comes the recipe:

```
opam switch fresh-bap -A4.03 # create a new switch named fresh-bap (arbitrary name)
eval `opam config env`
opam depext --install bap # install bap and all external dependencies 
```

It should work, but we didn't test on Debian, so it is possible that some opam package specifications are wrong. Please, provide a feedback on how the installation worked for you so that we can fix it. When opam fails to install a package it outputs a diagnostic message, that references to captured output from the build process (the out, env and err files). These files and the diagnostic message itself will be very helpful.

**Comment by ted42** [comment]
Thank you very much! setting LLVM_CONFIG did the trick.
I had to use the version 4.02.3 because of `[ERROR] "4.03" is not a valid compiler.` but I could install it now.

It's still not really working because it throws errors like:
`Failed to create a project: no such backend: '<no-loaders-available>'` or `Exception: "no such backend: 'llvm'".`
This might be related with my llvm issues.

**Comment by ivg** [comment]
> I had to use the version 4.02.3 because of [ERROR] "4.03" is not a valid compiler.

Yeah, sure, I forgot the minor version, it should be `4.03.0` ( I will update the recipe for the later references).

> It's still not really working because it throws errors like:

These errors are from BAP plugins, basically, the messages are saying, that the LLVM plugin failed to load. There should be some extra information. Try to set variable `BAP_DEBUG=1` and look at the `~/.local/state/bap/log` file. It should give some insights. You can post it here.

**Comment by drvink** [comment]
I'm also unable to build `bap-llvm` (trying with both llvm 3.8 and 3.8.1). I get the same errors.

**Comment by ted42** [comment]
Everything seems to be working now (after a restart).
I assume because of the non existing LLVM_CONFIG after the restart. (But maybe it was something else).
So basically debian users need a current opam, llvm 3.4 and need to set the LLVM_CONFIG environment variable. (We should probably update the installation instructions?)

**Comment by ivg** [comment]
> (We should probably update the installation instructions?)

I think it is better (and easier) to update the installation scripts to accommodate Debian specific options. But for this I need to know to which value did you set LLVM_CONFIG?

> I assume because of the non existing LLVM_CONFIG after the restart. 

It should not interact in any way with BAP, as it is used only inside small configure script in `conf-llvm` opam package, that is responsible for finding the `llvm-config` program, and querying it for variables. The path and the variable values are stored statically in the opam state. 

It's hard to guess, what went wrong on your side. Probably, you forgot to change the switch and was actually running bap from another switch. People usually forget to do `eval $(opam config env)`.

**Comment by ted42** [comment]
I used `export LLVM_CONFIG=llvm-config-3.4` (after manually installing llvm 3.4 because default was 3.5)

**Comment by ivg** [comment]
Well, setting LLVM_CONFIG=llvm-config-3.4 shouldn't make any differences. It already defaults to it. For example, this is how the config is searched by default:
```shell
configs="llvm-config-3.4 llvm-config-mp-3.4 llvm-config-3.8 llvm-config-mp-3.8 llvm-config"
config=${LLVM_CONFIG}


if ! which "$config"; then
    for c in $configs; do
        if which $c; then
            config=$c
            break
        fi
    done
fi
```

Basically, it will search in a list  `[${LLVM_CONFIG},  `llvm-config-3.4`, ...]` until something that is in the path is found. As you may see, adding `llvm-config-3.4` to the list doesn't really change anything. 

So BAP installation on Debian should work out-of-box. We will add a debian box to our testsuite to verify that indeed works out-of-box. I'm closing the issue for now.

**Comment by ivg** [comment]
@drvink, thanks a lot for digging it! I've created #616 to track it.

**Comment by ivg** [comment]
THIMC, the #618 PR adds a Vagrant file, that boots a Debian 8 VM. The Vagrantfile contains [a recipe][1], that installs BAP during the provisioning. I will duplicate the recipe here:

```
sudo apt-get update
sudo apt-get --yes install clang
sudo apt-get --yes install opam
opam init --auto-setup --comp=4.02.3 --yes
eval `opam config env`
opam install depext --yes
opam depext conf-llvm.3.4 --install --yes
opam depext bap --install --yes
sudo apt-get install python-pip --yes
sudo pip install bap
``` 

This is a sequence of instructions that you need for installing bap on jessie. It's not absolutely trivial. We will rectify it a little bit, but in general the only proper way would be to provide a debian package.

[1]: https://github.com/BinaryAnalysisPlatform/bap/blob/master/vagrant/trusty64/Vagrantfile#L10-L18
