### ISSUE TITLE
cmdliner breaking changes 

### ISSUE THREAD

**Issue by ivg** [BinaryAnalysisPlatform/bap#636]
The cmdliner library was updated with quite a few breaking changes. Since our opam specification is unrestricted bap will not be buildable anymore. To anticipate this change we need:

- [ ] restrict travis opam/opam specification
- [ ] restrict currently released versions of bap to compatible versions of cmdliner
- [ ] update the bap upstream to cmdliner 1.0.0 (blocked by ocaml/opam-depext#58)
- [ ] add a cron job to travis, that will rebuild bap every day, to catch such issues in the future

**Comment by dbuenzli** [comment]
`bap-std` was constrainted in https://github.com/ocaml/opam-repository/pull/8585

**Comment by ivg** [comment]
Yeah, @dbuenzli, I saw it, thanks for protecting us :) We also have few other places to propagate the constraint, like our own fork of the opam repository, and a special opam file for the travis CI.

**Comment by XVilka** [comment]
@ivg seems can be easily workaround by adding `--ignore-constraints-on` in opam, see https://github.com/ocaml/opam/issues/2873

**Comment by ivg** [comment]
solved by #684
