### ISSUE TITLE
Offending byte sequences

### ISSUE THREAD

**Issue by KennethAdamMiller** [BinaryAnalysisPlatform/bap#640]
The lifter is being used in some custom disassembler work to identify call targets. This gave some exceptions, which had to be hunted down for the source location and the specific memory that brought it on.

These byte values occurred numerous times each, but I went through and found the unique ones. I'll probably have an expanded set soon too, but for now I'm working on further curating my code first. Before I'm done, however, I will have run the lifter over a large swath of binaries.

00000000004d3d4f: 48 8b 04 25 00 00 00 00
00000000004d3d50: 8b 04 25 00 00 00 00

Example command to reproduce: 

bap-mc --addr=0x4d3d4f 488b042500000000

Uncaught exception:

  "Option.value_exn None"

Raised by primitive operation at file "src/option.ml", line 59, characters 4-21
Called from file "plugins/x86/x86_mov.ml", line 38, characters 12-44
Called from file "src/bap_mc.ml", line 78, characters 10-23
Called from file "src/bap_mc.ml", line 89, characters 14-39
Called from file "src/bap_mc.ml", line 100, characters 4-34
Called from file "src/bap_mc.ml", line 118, characters 16-35
Called from file "lib/bap_disasm/bap_disasm_basic.ml", line 519, characters 2-32
Called from file "lib/bap_disasm/bap_disasm_basic.ml", line 510, characters 2-7
Called from file "src/bap_mc.ml", line 262, characters 22-50

**Comment by KennethAdamMiller** [comment]
Found some more: 
00000000004442df: c7 04 25 00 00 00 00 00 00 00 00
00000000004709bc: 48 c7 04 25 00 00 00 00 00 00 00 00

**Comment by ivg** [comment]
@KennethAdamMiller, are you using gcc-5.x to compiler this binaries?
