### ISSUE TITLE
BAP install error

### ISSUE THREAD

**Issue by disneylucy** [BinaryAnalysisPlatform/bap#641]
Hi all,

Installing BAP 0.9.9 from OPAM on Ubuntu 14.04 fails with the following error:
……
[uuidm.0.9.6] http://erratique.ch/software/uuidm/releases/uuidm-0.9.6.tbz downloaded
[oasis.0.4.7] https://forge.ocamlcore.org/frs/download.php/1635/oasis-0.4.7.tar.gz downloaded

=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[ERROR] The compilation of uuidm failed at "ocaml pkg/pkg.ml build --pinned
        false --with-cmdliner true".
[ERROR] The compilation of uri failed at "ocaml setup.ml -build".
[ERROR] The compilation of lwt failed at "make build".
[ERROR] The compilation of oasis failed at "ocaml setup.ml -build".
Processing  6/37: [oasis: ocaml]
#=== ERROR while installing lwt.2.7.0 =========================================#
 opam-version 1.2.2
 os           linux
 command      make build
 path         /home/sunlu/.opam/4.02.3/build/lwt.2.7.0
 compiler     4.02.3
 exit-code    2
 env-file     /home/sunlu/.opam/4.02.3/build/lwt.2.7.0/lwt-7294-8bc1db.env
 stdout-file  /home/sunlu/.opam/4.02.3/build/lwt.2.7.0/lwt-7294-8bc1db.out
 stderr-file  /home/sunlu/.opam/4.02.3/build/lwt.2.7.0/lwt-7294-8bc1db.err
……
 File "_none_", line 1:
 Error: Cannot find file /home/sunlu/.opam/4.02.3/lib/result/result.cmxa
 Command exited with code 2.
#Makefile:33: recipe for target 'build' failed

**Comment by ivg** [comment]
Hi, 

First of all, the 0.9.9 version is an unstable and a very old version, that we do not support. The latest version is 1.2.0, it is stable and is much more complete. So my first suggestion is to switch to the latest stable version. If you have any code that works with the old version, but doesn't work with the stable version it is better to upgrade it. If this code lives somewhere in the BinaryAnalysisPlatform organization, then please make a pull request/feature request. 

Now to the problem that you're facing. It is not in bap actually it is in one of the upstream libraries, notable in `uuidm`. It looks like that the `uuidm` version is incompatible either with your compiler version, or it misses dependencies. As a workaround, you may try to install a working version of uuidm manually with `opam install uudim.XXX` where `XXX` is some version that is installable.
