### ISSUE TITLE
weakest precondition propagation WP in BAP

### ISSUE THREAD

**Issue by andreaslindner** [BinaryAnalysisPlatform/bap#647]
Hi!

We've used BAPs weakest precondition propagation through BIL code in previous work a while ago in our group. It seems to be gone now? Or are we missing something?

Unfortunately, we cannot find WP anymore. Did you remove this or are we just blind? :)

We are trying the new version because we have problems compiling the old version on a new OS, and we wanted to use the opportunity to update to the latest BAP version.

Best,
  Andreas

**Comment by ivg** [comment]
Hi Andreas!
Unfortunately, we didn't add WP yet. The new BAP is a complete reimplementation, and some things are still missing.

**Comment by andreaslindner** [comment]
Thank you for the quick reply!

Okay, then we'll go with a docker container and the old version. This is sufficient for what we're doing now.

**Comment by houseofwealth** [comment]
Any updates on this? I would find such a module in the current BAP to be very useful
