### ISSUE TITLE
BAP cannot load the LLVM plugin

### ISSUE THREAD

**Issue by fidget324** [BinaryAnalysisPlatform/bap#649]
When I run bap, I get the following error:
```
loader.error> Failed to load plugin "llvm": Failed to load bap_llvm: error loading shared library: /tmp/bap_llvm8af7a5.cmxs: undefined symbol: _ZN4llvm6Triple9normalizeENS_9StringRefE
```
I followed the directions in the README to build bap from source, and I did not encounter any errors during the build process.

**Comment by ivg** [comment]
Can you disclose a little more information? What is the version of LLVM, compiler, distribution. Or if you're on a vagrant box, what is the box name. Also did you try to install bap in the official way, i.e., with opam?

**Comment by fidget324** [comment]
First, thank you for the blazingly quick response. I installed BAP using opam, following exactly the directions listed in the README. I have two distributions of LLVM on my system: 3.7 which I built and installed from source, and 3.8 which was installed using apt-get. I'm on Ubuntu 16.04 LTS, running on top of VirtualBox. Is that enough to help?

**Comment by fidget324** [comment]
UPDATE: I completely uninstalled LLVM 3.7, then reinstalled BAP, and it now appears to be working just fine. But shouldn't BAP automatically detect the right version of LLVM when it's installed? Isn't this a bug?

**Comment by ivg** [comment]
>  But shouldn't BAP automatically detect the right version of LLVM when it's installed? Isn't this a bug?

It should, although there are lots of ad hoc heuristic involved in a process, so it is likely that it may confused, especially, if a system has some sort of non-standard configuration. It is probable, that the manual installation broke some invariants on which we are relying. I don't really know what in particular happened on your system, but it looks like that bap managed to catch the llvm-3.7 (we didn't ever try to compile BAP with this version, but it looks like that it works, we will double check), and the llvm-3.7 wasn't built correctly, as it missed few dependencies. So, there is a bug on BAP side (we accidentally took 3.7) and an issue with your llvm-3.7 (a missing dependency).

**Comment by ivg** [comment]
@gitoleg, can you take a look at this issue? I do remember that you had something similar when you compiled llvm from source. Did you?

**Comment by gitoleg** [comment]
So, tested with vagrant box  `ubuntu/xenial64`: installed `llvm-3.7` from sources,

**Comment by ivg** [comment]
For those of you who will stumble on this problem, the solution is to use a newer version of the clang compiler. We can confirm that certain version of LLVM compiler are unable to link with the LLVM libraries, due to ABI changes. In particular, versions clang 3.7, 3.6, 3.5 (and probably all earlier versions) are unable to compile llvm-3.8 (and probably newer versions). So, if you see this problem make sure that you're using a not very old `clang++` compiler. By default, bap will be compiled with `clang++` found in the path.
