### ISSUE TITLE
bap-server doesn't clean after itself

### ISSUE THREAD

**Issue by ivg** [BinaryAnalysisPlatform/bap#65]
it creates lots of files in `/tmp` folder, that should be cleaned with some policy.

**Comment by alpire** [comment]
:+1:

**Comment by ivg** [comment]
yep, the only problem, is to define a policy. The rest is trivial. 
The easiest to implement would be to clean all `at_exit`, and (in case if we hadn't a chance to do this), clean at_startup.

**Comment by alpire** [comment]
I don't really understand the purpose of the mmap_server, so I can't really be of help defining a policy. But what you mentioned (cleanup at exit and at startup) sounds reasonable. Also, if those files are used like a cache, limiting the numbers of files might be necessary for long running servers.

**Comment by ivg** [comment]
It is used to send bytes from client (qira) to server (bap) and vice verse. Since, sending memory chunks through http (that is also possible) is too expensive. As name suggests, there is no copying involved, we just share memory between client and server. The file entry is used as a symbolic address, nothing more. The reason, why we do not delete them, is because memory chunks can be reused later and by different instances. If we're going to delete this files in the runtime (we can't just limit, this will result on DoS), the we also need to implement eviction policy in resource manager, so that it can refetch memory if it is later required. Since, qira doesn't allow this (it gives memory chunk only once, and assumes that we will store it infinitly), we need to implement some non-trivial eviction policy, like storing this memory chunk on a file system or in a database. The former approach will not help us if we are hitting maximum file entries bound (it will make things even worser). The latter approach is non-trivial and requires extra dependencies. That's basically the reason, why I did choose current policy - do nothing, as OOM-killer will kill qira before bap.

**Comment by ivg** [comment]
this issue must be moved to a bap-server repository
