### ISSUE TITLE
llvm loader crashes on ELF object files

### ISSUE THREAD

**Issue by maurer** [BinaryAnalysisPlatform/bap#656]
```
0x00007fffa0d65327 in operator- (this=<optimized out>, this=<optimized out>, Other=...)
at /usr/lib/llvm-3.4/include/llvm/Object/ELF.h:111
111           return (Current - Other.Current) / EntitySize;
(gdb)
```

[Sample file](https://data.maurer.codes/python.o)

It's fine if it doesn't load it, but I need it to not take down the process.

**Comment by ivg** [comment]
Sample fine link raises `Not_found` :)

Also, what version of BAP are you using? Cause the same bug (at least the similar place) was worked around in the 1.1 version. Also, the bug is actually in the LLVM, so the fix for the another (or maybe the same) manifestation was just to make sure, that this code is not reachable. 

Also, the 3.8 version shouldn't have this so you can just switch to it, if it suits you.

**Comment by ivg** [comment]
Ok, I'm able to reproduce it with any object file, e.g.,

```
$ bap _build/tools/bapbundle.o
Floating point exception (core dumped)
```

Moreover, on llvm-3.8 it even segfaults:
```
[276932.244308] bap[13860]: segfault at 20 ip 00007f9419e5df63 sp 00007fff86f2a570 error 4 in bap_llvm03d78d.cmxs (deleted)[7f9419bed000+aea000]
```

So it fails somewhere deep in the LLVM library, we will think how to workaround this, but don't expect the fix soon. My current suggestion, is not to run bap on the `.o` files.

**Comment by maurer** [comment]
Re: Version, I was using BAP 1.2 .deb release, as noted in the previous title.

**Comment by ivg** [comment]
Oh, sure it will be fixed. We already know what is the problem, and have the fix. It will just take some time, before it will hit the released version. I will ask Oleg to submit a PR, so that you can grab a patch from it, and add to the nix spec, if you would like to get it right now.

**Comment by ivg** [comment]
Also, while the fix will protect from the crash, bap still will terminate with an error, as the released version don't know what to do with the object files, as they don't contain segmentation information (basically no segments, only sections). In the future, (I hope it will be finished in 1.3) we will have a much more flexible loader interface, that allows us to derive necessary information without being too strict to the backend. You may be noticed the primus PR, that contained the new loader (OGRE). You may check it, if you're interested.
