### ISSUE TITLE
external symbol names resolution in Mach-O binaries

### ISSUE THREAD

**Issue by ivg** [BinaryAnalysisPlatform/bap#667]
In the current master version

    bap --no-ida `which ls` -dsymbols | grep -v sub

returns zero symbols, that means that bap itself, without a help from IDA, can't get any names. 

We should investigate:
1. Whether it is a regression from 1.2 because of OGRE.
2. Why we can't provide symbol names, is it that hard, what are the complications, etc.
3. Figure out what MacOS specific tools may help us, if we can't do it ourselves under a reasonable cost.

**Comment by gitoleg** [comment]
don't think we have a regression here. 
Let's look at 
```
macmini:coreutils oleg$ gobjdump -t /bin/ls
/bin/ls:     file format mach-o-x86-64

SYMBOL TABLE:
0000000005614542      d  3c OPT    00 0000 radr://5614542
0000000100000000 g       0f SECT   01 0010 [.text] __mh_execute_header
0000000000000000 g       01 UND    00 0300 __DefaultRuneLocale
0000000000000000 g       01 UND    00 0300 ___assert_rtn
0000000000000000 g       01 UND    00 0300 ___bzero
0000000000000000 g       01 UND    00 0300 ___error
.....
```
We may infer that there are not any `FUN` symbol. Most of them has `UND` - undefined type, i.e. it external symbols

Now one more example. I built few binaries previously for some needs, so:
```
macmini:coreutils oleg$ file gcc_coreutils_32_O0_cat
gcc_coreutils_32_O0_cat: Mach-O executable i386

macmini:coreutils oleg$ bap gcc_coreutils_32_O0_cat -dsymbols | grep -v sub_
___fpending 
__getopt_initialize 
__getopt_internal_r 
__getopt_long_only_r 
__getopt_long_r 
__mh_execute_header 
_base_len 
_c_isalnum 
_c_isalpha
.....
```
As you see we have some symbols with names other then `sub_*`

**Comment by ivg** [comment]
ok, then a false alarm :)
