### ISSUE TITLE
Bapbuild/commandline tools not recognized in bap.1.2.0?

### ISSUE THREAD

**Issue by Dinatrix** [BinaryAnalysisPlatform/bap#671]
Hello,

I was attempting to add some custom capabilities to saluki so I downloaded the current source code from github and attempted to recreate the plugin myself before making changes. 

Having installed bap.1.2.0 in a Ubuntu VM, I ran 'make' in the saluki folder and received the following error:
bapbuild -tag 'ppx(ppx-bap)' -package cmdliner saluki.plugin
make: bapbuild: Command not found
make: *** [saluki] Error 127

A few weeks ago in this same VM, I had been able to create the sample plugin shown online for calculating jump ratios of a binary, but received the same result when I retried the command in a new folder with a copy of the jmp.ml:

$ bapbuild jmp.plugin
bapbuild: command not found

$ bap ---list-plugins 
No command 'bap' found, but there are 18 similar ones.

I then switched to a VM with bap.1.1.0~alpha still installed, and bapbuild worked. (Though there was a saluki error when I ran make; 
bapbuild -tag 'ppx(ppx-bap)' -package cmdliner saluki.plugin
+ ocamlfind ocamlc -c -g -short-paths -thread -package cmdliner -package ppx_jane -package core_kernel -package bap -ppx ppx-bap -o v.cmi v.mli
File "v.mli", line 8, characters 8-17:
Error: Unbound module type Regular.S
Command exited with code 2.
Compilation unsuccessful after building 6 targets (0 cached) in 00:00:01.
make: *** [saluki] Error 10
)

Reverting back to 1.1.0 in the first VM (using 'opam depext --install bap.1.1.0'), bapbuild and bap commands are still not recognized. 

Would it be better for me to try and make the new version of saluki work with the older version of bap? Or try and get the new version of bap's command line tools to work again?

Thanks for the help!

**Comment by ivg** [comment]
Did you enable opam with?

```
eval `opam config env`
```

**Comment by Dinatrix** [comment]
Ah I had when first setting up the VM but not when rebooting it. That would explain why it stopped working. Was able to compile plugins again, thanks!
