### ISSUE TITLE
Newcomer/Documentation Clarification

### ISSUE THREAD

**Issue by RabidCicada** [BinaryAnalysisPlatform/bap#679]
I'm a newcomer so this is perhaps incorrect...
I think the documentation needs to be updated to tell people how to help themselves better.  I'm using master branch due to the presence of more plugins compared to 1.2.0.

1. I see that bap --PASS-help is a method but also notice that --PASS form is being deprecated in favor of '--pass=PASS or --passes=PASS,PASS,...' .  In the new form (--pass=PASS)...how is one supposed to pass arguments or invoke help on the plugin?  Is the PASS-arg form remaining for passing arguments?

2.In addition, how is one supposed to be able to discern between plugins that are passes and plugins that are used by the core/builtin?  This may be my misunderstanding, but I believe the fault could be in the documentation, because as a newcomer I'm finding it very difficult to tell what plugins are passes vs different beasts altogether.  Currently the README.md's look like the best answer..but many don't answer the question.

For example I see cache in bap/plugins and it appears to not register a pass and I guess instead be used by other plugins/thecore?  Then I see propagate taint which clearly registers a pass.

3.The immediate follow-on question is how to discern dependencies between plugins?  Is there a formal dependency statement somewhere in there man/doc page?  Or do you simply find out by running the pass and seeing a failure when it tries to load/use a needed resource due to ocaml?

I've tried asking some questions in IRC and it's a barren wasteland with no response whatsoever.

I'm reading through https://binaryanalysisplatform.github.io/, and https://binaryanalysisplatform.github.io/bap/api/v1.2.0/argot_index.html, and https://github.com/dbrumley/bap-plugin-book/blob/master/bap-plugin-book.org.  As well as https://github.com/BinaryAnalysisPlatform/bap-plugins.

I understand people may not have all the answers (and I am new to ocaml) any help is appreciated.

**Comment by RabidCicada** [comment]
--callsites-help returns nothing even though I see manpage info in the config for the plugin.  I've googled around for how other people use --callsites. but I see nothing.  Does callsites need other information? Am I missing a dependency?

**Comment by RabidCicada** [comment]
I also see callsites in https://github.com/BinaryAnalysisPlatform/bap/tree/master/plugins/callsites,  andhttps://github.com/BinaryAnalysisPlatform/bap-plugins/tree/master/callsites.  I'm referring to the one that comes with BAP itself and not the bap-plugins repo

**Comment by ivg** [comment]
Good points! We will definitely update the documentation, but before that I will provide some clarifications here, to see if they make sense to a you. 

1. Sometimes documentation mentions `PASS` where a plugin is actually meant, this comes from old times when the only type of plugin was a pass, so we named all plugins passes. The `--PLUGIN-help` as well as `--PLUGIN-<arg>` form is not deprecated, this is a correct way of passing arguments, or querying plugins. The new form only refers to the way how one should specify which program transformations should be applied and in which order. So, instead of saying `bap /bin/ls --pass1 --pass2 --pass3` we now try to say `bap /bin/ls --passes=pass1,pass2,pass3`  

2. This was fixed in #663, now each plugin has a set of tags, associated with it. And the `--list-plugin` option now takes a list of tag names. The tag names itself are not documented yet, and will actually change in the next few releases, but at least `pass` should be stable, e.g., 
```
   bap --list-plugins=pass
```

3. We rely on a package manager to track dependencies. If opam installed a pass that fails with a missing requirement then it is a bug, that we should fix.  Though, I agree, that it would be a good idea to specify in the man page the dependencies, just for the better understanding of what is happening underneath the hood. 

>  I'm using master branch due to the presence of more plugins compared to 1.2.0.

This sounds a little bit suspicious. Maybe you just didn't install all the plugins? Each plugin is a separate opam package. The `bap` package is a meta package that installs bap essentials, though there are other bap related packages. But first of all make sure that you have `bap` installed.

> --callsites-help returns nothing even though I see manpage info in the config for the plugin

 `--callsites-help` works for me and prints a man-page (you can even read this page in the online docs, lookup under the Plugins sections).
 I can imagine only one reason why it doesn't work for you, is that it is not installed. And that signals that your installation is broken. What does `bap --list-plugins` output? Also, what is your setup and how did you install bap?

For example, this is how it looks in my machine:

```
bap --list-plugins
  [+] objdump                    use objdump to provide a symbolizer
  [+] primus-x86                 x86 support package
  [+] emit-ida-script            extract a IDA python script from bap
  [+] abi                        apply abi information to a project
  [+] api                        add parameters to subroutines based on known API
  [+] run                        a pass that will run a program
  [+] propagate-taint            propagate taints through a program
  [+] dump-symbols               dump symbol information as a list of blocks
  [+] cxxfilt                    provide c++filt based demangler
  [+] arm                        provide ARM lifter
  [+] callsites                  annotate callsites with subroutine's arguments
  [+] primus-exploring           implements the exploring scheduling strategy
  [+] piqi-printers              provides piqi serialization for main data types (BIL, IR)
  [+] primus-greedy              implements the greedy scheduling strategy
  [+] primus-print               prints Primus states and observations
  [+] primus-wandering           implements the wandering scheduling strategy
  [+] phoenix                    output project information in a phoenix format
  [+] primus-lisp                install and load Primus lisp libraries
  [+] demangle                   demangle subroutine names
  [+] beagle                     microx powered obfuscated string solver
  [+] primus-promiscuous         enables the promiscuous mode of execution
  [+] strings                    BAP Core Library
  [+] print                      print project in various formats
  [+] cache                      provide caching services
  [+] byteweight                 find function starts using Byteweight algorithm
  [+] map-terms                  map terms using BML DSL
  [+] primus-round-robin         implements the round-robin scheduling strategy
  [+] x86                        provide x86 lifter
  [+] llvm                       provide loader and disassembler using LLVM library
  [+] warn-unused                warn about unused results of certain functions
  [+] ida                        use ida to provide rooter, symbolizer and reconstructor
  [+] primus-propagate-taint     a taint propagation engine
  [+] read-symbols               read symbol information from file
  [+] taint                      taint specified terms
  [+] frontc-parser              parse c files with FrontC
  [+] primus-loader              generic program loader for Primus
  [+] elf-loader                 read ELF and DWARF formats in a pure OCaml
  [+] trace                      manage execution traces
```
and

```
 bap --list-plugins=pass
  [+] objdump                    use objdump to provide a symbolizer
  [+] abi                        apply abi information to a project
  [+] api                        add parameters to subroutines based on known API
  [+] propagate-taint            propagate taints through a program
  [+] dump-symbols               dump symbol information as a list of blocks
  [+] cxxfilt                    provide c++filt based demangler
  [+] callsites                  annotate callsites with subroutine's arguments
  [+] piqi-printers              provides piqi serialization for main data types (BIL, IR)
  [+] phoenix                    output project information in a phoenix format
  [+] demangle                   demangle subroutine names
  [+] beagle                     microx powered obfuscated string solver
  [+] byteweight                 find function starts using Byteweight algorithm
  [+] map-terms                  map terms using BML DSL
  [+] warn-unused                warn about unused results of certain functions
  [+] read-symbols               read symbol information from file
  [+] taint                      taint specified terms
  [+] frontc-parser              parse c files with FrontC
  [+] trace                      manage execution traces
```

**Comment by ivg** [comment]
> I've tried asking some questions in IRC and it's a barren wasteland with no response whatsoever.

IRC? Does BAP have a channel? ;) If yes, I'm unaware of it. 

We have an active [gitter][1] where you can always find an answer. But if you prefer IRC I can join it and catch bap questions there too. Where did you ask it?

[1]: https://gitter.im/BinaryAnalysisPlatform/bap

**Comment by RabidCicada** [comment]
Very serious thankyou for the quick response.  I was on freenode#bap because I googled I saw there was one.  And I saw no documentation of the gitter:).  Thanks for the info.  I'll happily jump on gitter.  I didn't see it referenced anywhere (perhaps intentionally :) ).  I know getting spammed all day is likely not your goal or anyone else working on BAP.

1.Ahh...Thanks for the clarification.  I incorrectly assumed all similar forms to --PASS were deprecated based on the output of bap --help.

2.Ok.  So I can begin filtering based on tags.

3.I think this problem still stems from me running in a non-standard configuration.  I'm still running off of a pinned local repo cloned from https://github.com/BinaryAnalysisPlatform/bap.  Am I safe if I run `opam pin add bap --dev-repo` from the `build tips and tricks` wiki [page](https://github.com/BinaryAnalysisPlatform/bap/wiki/Build-tips-and-tricks)?

> This sounds a little bit suspicious. Maybe you just didn't install all the plugins? 
There are a ton of primus plugins in the [master](https://github.com/BinaryAnalysisPlatform/bap/tree/master/plugins) that are not in the [v1.2.0](https://github.com/BinaryAnalysisPlatform/bap/tree/v1.2.0/plugins) tag.  That might be the extent of it..but I'm not sure.

> --callsites-help works for me and prints a man-page (you can even read this page in the online docs, lookup under the Plugins sections).

WRT the callsites problem...I have debugged as much as I can think.  Lots of output below showing my configuration. Note that it shows up in list-plugins but not list-plugins=pass

```
bap --list-plugins
  [+] read-symbols               read symbol information from file
  [+] taint                      taint specified terms
  [+] run                        a pass that will run a program
  [+] primus-print               prints Primus states and observations
  [+] beagle                     microx powered obfuscated string solver
  [+] primus-greedy              implements the greedy scheduling strategy
  [+] abi                        apply abi information to a project
  [+] primus-promiscuous         enables the promiscuous mode of execution
  [+] cxxfilt                    provide c++filt based demangler
  [+] primus-x86                 x86 support package
  [+] phoenix                    output project information in a phoenix format
  [+] cache                      provide caching services
  [+] primus-exploring           implements the exploring scheduling strategy
  [+] demangle                   demangle subroutine names
  [+] piqi-printers              provides piqi serialization for main data types (BIL, IR)
  [+] map-terms                  map terms using BML DSL
  [+] emit-ida-script            extract a IDA python script from bap
  [+] print                      print project in various formats
  [+] api                        add parameters to subroutines based on known API
  [+] dump-symbols               dump symbol information as a list of blocks
  [+] frontc-parser              parse c files with FrontC
  [+] primus-loader              generic program loader for Primus
  [+] trace                      manage execution traces
  [+] propagate-taint            propagate taints through a program
  [+] primus-round-robin         implements the round-robin scheduling strategy
  [+] callsites                  description not provided
  [+] primus-propagate-taint     a taint propagation engine
  [+] warn-unused                warn about unused results of certain functions
  [+] strings                    BAP Core Library
  [+] primus-lisp                install and load Primus lisp libraries
  [+] x86                        provide x86 lifter
  [+] byteweight                 find function starts using Byteweight algorithm
  [+] primus-wandering           implements the wandering scheduling strategy
  [+] llvm                       provide loader and disassembler using LLVM library
  [+] elf-loader                 read ELF and DWARF formats in a pure OCaml
  [+] arm                        provide ARM lifter
```

```
bap --list-plugins=pass
  [+] read-symbols               read symbol information from file
  [+] taint                      taint specified terms
  [+] beagle                     microx powered obfuscated string solver
  [+] abi                        apply abi information to a project
  [+] cxxfilt                    provide c++filt based demangler
  [+] phoenix                    output project information in a phoenix format
  [+] demangle                   demangle subroutine names
  [+] piqi-printers              provides piqi serialization for main data types (BIL, IR)
  [+] map-terms                  map terms using BML DSL
  [+] api                        add parameters to subroutines based on known API
  [+] dump-symbols               dump symbol information as a list of blocks
  [+] frontc-parser              parse c files with FrontC
  [+] trace                      manage execution traces
  [+] propagate-taint            propagate taints through a program
  [+] warn-unused                warn about unused results of certain functions
  [+] byteweight                 find function starts using Byteweight algorithm

```
```
ls -al ~/.opam/4.02.3/lib/bap-plugin-callsites/
total 276
drwxrwxr-x   2 dev dev  4096 Jul 24 13:14 .
drwxr-xr-x 178 dev dev  4096 Jul 24 13:14 ..
-rw-rw-r--   1 dev dev 69111 Jul 24 13:06 callsites_main.annot
-rw-rw-r--   1 dev dev  9564 Jul 24 13:06 callsites_main.cmi
-rw-rw-r--   1 dev dev 76086 Jul 24 13:06 callsites_main.cmt
-rw-rw-r--   1 dev dev  3521 Jul 24 13:06 callsites_main.cmx
-rw-rw-r--   1 dev dev  3091 Jul 24 13:02 callsites_main.ml
-rw-rw-r--   1 dev dev 23720 Jul 24 13:06 callsites_plugin.a
-rw-rw-r--   1 dev dev 29061 Jul 24 13:06 callsites_plugin.cma
-rw-rw-r--   1 dev dev  1739 Jul 24 13:06 callsites_plugin.cmxa
-rwxrwxr-x   1 dev dev 37168 Jul 24 13:06 callsites_plugin.cmxs
-rw-rw-r--   1 dev dev   429 Jul 24 13:02 META
```
```
opam switch list
--     -- 3.07    Official 3.07 release
--     -- 3.08.0  Official 3.08.0 release
--     -- 3.08.1  Official 3.08.1 release
--     -- 3.08.2  Official 3.08.2 release
--     -- 3.08.3  Official 3.08.3 release
--     -- 3.08.4  Official 3.08.4 release
--     -- 3.09.0  Official 3.09.0 release
--     -- 3.09.1  Official 3.09.1 release
--     -- 3.09.2  Official 3.09.2 release
--     -- 3.09.3  Official 3.09.3 release
--     -- 3.10.0  Official 3.10.0 release
--     -- 3.10.1  Official 3.10.1 release
--     -- 3.10.2  Official 3.10.2 release
--     -- 3.11.0  Official 3.11.0 release
--     -- 3.11.1  Official 3.11.1 release
--     -- 3.11.2  Official 3.11.2 release
--     -- 3.12.0  Official 3.12.0 release
--     -- 3.12.1  Official 3.12.1 release
--     -- 4.00.0  Official 4.00.0 release
--     -- 4.00.1  Official 4.00.1 release
--     -- 4.01.0  Official 4.01.0 release
--     -- 4.02.0  Official 4.02.0 release
--     -- 4.02.1  Official 4.02.1 release
--     -- 4.02.2  Official 4.02.2 release
4.02.3  C 4.02.3  Official 4.02.3 release
--     -- 4.03.0  Official 4.03.0 release
--     -- 4.04.0  Official 4.04.0 release
--     -- 4.04.1  Official 4.04.1 release
--     -- 4.04.2  Official 4.04.2 release
--     -- 4.05.0  Official 4.05.0 release
```
```
opam config env
CAML_LD_LIBRARY_PATH="/home/dev/.opam/4.02.3/lib/stublibs"; export CAML_LD_LIBRARY_PATH;
MANPATH=":/home/dev/.opam/4.02.3/man"; export MANPATH;
PERL5LIB="/home/dev/.opam/4.02.3/lib/perl5:"; export PERL5LIB;
OCAML_TOPLEVEL_PATH="/home/dev/.opam/4.02.3/lib/toplevel"; export OCAML_TOPLEVEL_PATH;
PATH="/home/dev/.opam/4.02.3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin"; export PATH;
```

```
dev@dev-virtual-machine:~/bapstuff/testing$ bap --callsites-help
dev@dev-virtual-machine:~/bapstuff/testing$ bap --pass=callsites --callsites-help
dev@dev-virtual-machine:~/bapstuff/testing$
```
```
opam pin list
bap.master    path  /home/dev/bapstuff/bap
```

**Comment by RabidCicada** [comment]
And just to have it documented in a searchable place how does one successfully use callsites?  Invoking `bap ./exe -dbir --pass=callsites`  gives me nothing different than `bap ./exe -dbir`

**Comment by ivg** [comment]
Aha, I see, it looks like that you somehow manually also installed a callsites plugin from the bap-plugins sandbox repository, that coincidentally has the same name as the callsites plugin from the main repo. 

To double check that my guess is right you can open the plugin file (that is just a zip file underneath the hood). Inside you will find a MANIFEST.scm file that describes the plugin, e.g., on mine machine the true `callsites` look like this:

```lisp
((name callsites)
 (version 1.0.0)
 (desc "annotate callsites with subroutine's arguments")
 (main callsites)
 (author ivg)
 (date 1501080488)
 (requires (callsites_plugin))
 (provides (callsites))
 (tags (pass)))
```

while the impostor looks like this:

```lisp
((name callsites)
 (version 0.1)
 (desc "description not provided")
 (main callsites)
 (author ivg)
 (date 1471954435)
 (provides (callsites)))
``` 

Notice the differences in versions and descriptions.

**Comment by RabidCicada** [comment]
Ahh...You know...I did run make in the callsites plugin probably.  I was very messy as I was still learning.  I already blew away the 4.02.3 switch and am reinstalling and going to use the `opam pin add bap --dev-repo` method this time around.  I cloned the bap-plugins repo so I could explore those plugins too.  I now notice in gitter that you said:

> yeah, bap-plugins is a sandbox so it's more or less ok if it is outdated, but bap/plugins shoudln't contain any crap.

which makes me think [bap-plugins](https://github.com/BinaryAnalysisPlatform/bap-plugins) is a risky proposition if I'm looking for something that works "out of the box" :).

I'm fairly certain you are correct about the callsites collision.  I probably ran `make` in quite a few of the bap-plugins plugins while trying to get familiar.

In that case will it overwrite the other or are they both present?  If both present: Is there an explicit ordering for which is loaded first and which is 'shadowed'?

**Comment by ivg** [comment]
> And just to have it documented in a searchable place how does one successfully use callsites? Invoking bap ./exe -dbir --pass=callsites gives me nothing different than bap ./exe -dbir

Well, it depend which of them you're actually looking for. (Yes, it is a bug, and we will definitely rename one of them). The impostor is doing the following:

> For each sink, specified in the command line \
       print a backtrace bound with the specified length.\
       Sinks can be specified using POSIX regular expressions

You can specify multiple sinks (aka interesting functions) by name using a regular expression, e.g., `bap exe --callsites-sink='.alloc' --callsites=free`. Since you have the impostor installed, and didn't specified any interesting function, nothing was found. 

For the original [plugin][1], that annotates the call sites with data definitions, there is a difference. And usually, it is not invoked directly, but is used in other passes, namely in taint propagation. 

[1]: http://binaryanalysisplatform.github.io/bap/api/v1.2.0/man1/bap-plugin-callsites.1.html

**Comment by ivg** [comment]
> which makes me think bap-plugins is a risky proposition if I'm looking for something that works "out of the box" :).

Yeah, its our kindergarten with lots of dead stuff actually. The mature plugins eventually move to the bap/plugins, while immature dies in oblivion.  This callsites was a teaching project, that I used to show simple things to students. 

> In that case will it overwrite the other or are they both present? If both present: Is there an explicit ordering for which is loaded first and which is 'shadowed'?

Unfortunately, they are just files, so once on overwrite another ... the the other is gone. Given that you're installing from the dev-repo, I think the only way is to install everything from scratch. Btw, the `opam --dev-repo` is ok, except it is for testing and CI, so it will install more than needed, and is not that versatile. The right way to get your hand on the latest version is to add a repository to which bap is automatically released every time we merge a PR, e.g., 


```
opam repo add bap git://github.com/BinaryAnalysisPlatform/opam-repository#testing
opam install bap
```

Notice: it is better to remove manually installed bap before doing this.

In that case you will have a normal opam installation where each plugin is wrapped in its own opam package.

**Comment by ivg** [comment]
>  I didn't see it referenced anywhere (perhaps intentionally :) ). I know getting spammed all day is likely not your goal or anyone else working on BAP.

No, it is actually on the README.md in a form of a nice and shiny badge. So far the gitter is not that infected with spam, so we are not hiding :)

**Comment by RabidCicada** [comment]
Ahh...I scrolled right past it because I'm used to seeing those "build" badges and a secondary search for gitter on the webpage version of README.md doesn't find anything because it's an image >.<.

Thanks for all the help.  You can close this issue.  I assume improving documentation is a standard and on going effort.  

Again thanks for your time.
