### ISSUE TITLE
How to generate a control flow graph using BAP?

### ISSUE THREAD

**Issue by abarbaro** [BinaryAnalysisPlatform/bap#698]
Hi,
is it possible to generate the CFG using BAP? If so, can I have an example please?

Thanks

**Comment by ivg** [comment]
Well, BAP always generates the CFG even if you don't ask. So probably you're asking how to get it.

1. If you want just a dot representation of a control flow graph, then:
```
    bap ./exe -dcfg
```
2. If you want your own format then you may write a plugin, that implements dumping a cfg in some other format. 
3. You can access it from a BAP plugin, there are several representations, e.g., `Program`, `Graphs.cfg`, and `Disasm.cfg` depending on a level of representation.
4. You can use bap-python bindings and get the cfg
5. You can use bap-bindings and get it from C.

So make your choice :)

**Comment by abarbaro** [comment]
@ivg : that was quick :) At the moment I would like to start with bap-python, any useful link that can help me to save time?

Thanks

**Comment by ivg** [comment]
Sure, look at [bap-python][1] bindings. They are in pip, so just doing `pip install bap` should be enough. Then you can run it like this:

```
>>> import bap
>>> proj = bap.run('/bin/true')
>>> main = proj.program.subs.find('main')
>>> entry = main.blks[0]
>>> next = main.blks.find(entry.jmps[0].target.arg)
````

At first, I would suggest to use `ipython` for trial and error exploration. But a comprehensive documentation is also available [online][2].

Also, I would recommend you to use visitors for the graph exploration, it may save you quite a few time :) 




[1]: https://github.com/BinaryAnalysisPlatform/bap-python
[2]: http://pythonhosted.org/bap/

**Comment by abarbaro** [comment]
So I think my edit "Probably my question was not clear, generating the CFG for /bin/ls I had only one "simple" graph so I think using BAP it is not possible to have the complete CFG because it does not symbolically execute it. is it correct?" was incorrect because through the visitor I can navigate the CFG and visit all the states. Correct?

**Comment by ivg** [comment]
Nope, `visitor` is a programming mechanism for visiting every node of a graph like structure. I'm not sure about what do you mean by a simple graph. Of course, we have an approximation of CFG, as reconstructing the true CFG of a program is in general undecidable. BAP uses recursive descent algorithm with a feedback, so if you a new edge is discovered by an analysis it may be added to the graph, and the whole pipeline of analysis will be started again. Currently we do not have VSA and mostly ignore indirect jumps, but you can plugin IDA and use its switch reconstruction for reconstructing a better CFG.

**Comment by abarbaro** [comment]
Thanks for the clarification, I think I'll try using IDA for a better CFG. I'll have a look into the documentation now and try to understand how to do it.

Thanks again

**Comment by ivg** [comment]
Well, out of box, BAP's CFG is comparable if not better than IDA's, unless you have something that really ... abnormal. So you can rely on our CFG's so far. With time we will make it better of course, but it comes with cost. The better precision the time you need to spend to obtain it.

**Comment by abarbaro** [comment]
@ivg , thanks so I'll have a look on it as you recommended. I'm just worries about indirect jumps that might not be properly followed.. Anyway, I think I should try first...

Thanks
