### ISSUE TITLE
 NameError: global name 'Tid' is not defined

### ISSUE THREAD

**Issue by frapik99** [BinaryAnalysisPlatform/bap#699]
Hi @ivg,
I'm doing few experiments with BAP but I had this weird error:

**Code**
```
In [1]: import bap
In [2]: proj = bap.run("malloc")
In [3]: main = proj.program.subs.find('main')
In [4]: entry = main.blks[0]
In [5]: next = main.blks.find(entry.jmps[0].target.arg)
```

**malloc**
```include<stdlib.h>

int sum(int a, int b) {
	return a + b;
}

int main() {
	int a = 3;
	
	if ( a > 2 )
		malloc(sum(1,2));
	else
		exit(1);
}
```

**Error**

```---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-5-6b244e5712d4> in <module>()
----> 1 next = main.blks.find(entry.jmps[0].target.arg)

/usr/local/lib/python2.7/dist-packages/bap/adt.pyc in find(self, key, d)
    491         if isinstance(key,str):
    492             test = by_name
--> 493         elif isinstance(key,Tid):
    494             test = by_id
    495         elif isinstance(key,Int):

NameError: global name 'Tid' is not defined
```

Am I doing something wrong?

**Comment by ivg** [comment]
You're doing everything right, it a bug, we introduced it when we moved stuff around the modules. Will fix it today and release the update.

**Comment by frapik99** [comment]
Thanks, please let me know when done so I can verify it if useful.

Thanks

**Comment by frapik99** [comment]
@ivg , just checking, have you had time to fix it?

Thanks

**Comment by ivg** [comment]
Yeah, I've fixed that day, and pushed to GitHub, but apparently I forgot about the main part - to push tarballs to pip. Currently, you can just install directly from the GitHub repo, see the instructions in README, for the specific command. I'll push the release, as soon as I get my hands on a computer.
