### ISSUE TITLE
BAP + IDA 7.0 compatibility issue

### ISSUE THREAD

**Issue by Dinatrix** [BinaryAnalysisPlatform/bap#707]
Hello!
I've gotten bap.1.3.0 and bap-ida-python.1.2.0 installed with IDA 7.0.

Whenever I go to run a plugin from within IDA, here I ran the --warn-unused --warn-unused-mark with the dead attribute, an error occurs with the following output:

![image](https://user-images.githubusercontent.com/10760263/30595452-449b09c6-9d1f-11e7-88f8-d0a4cef5adf8.png)

Additionally, is there a way to install 'bapbuild' in this version to compile custom plugins?

Thanks for taking a look at it!

**Comment by ivg** [comment]
> Additionally, is there a way to install 'bapbuild' in this version to compile custom plugins?

The `bapbuild` tool is installed automatically as a part of bap installation (in fact it is used in bap to compile its own plugins, so you can't have bap without the `bapbuild` unless you are installing from binaries, where `bapbuild` is removed). Did you run `eval $(opam config env)` ?

Concerning the error message, you need to install the `bap-ida` package, not the `bap-ida-python`.

**Comment by Dinatrix** [comment]
Ah I see. I am now able to access plugins via IDA.

I attempted to add saluki (source downloaded from github and plugin created/installed with the provided makefile, still hoping to later modify it as a previous issue described) but running the plugin as is has shown the following error:
![image](https://user-images.githubusercontent.com/10760263/30603734-6a7be91e-9d36-11e7-9d8e-218bd9eb1297.png)

bap --list-plugins shows that saluki was installed, so I'm curious why the plugin was an 'unknown' option..

**Comment by ivg** [comment]
The option is unknown because Saluki failed to load. Make sure that you are installing the latest Saluki, as this issue was fixed [a month ago](https://github.com/BinaryAnalysisPlatform/bap-plugins/pull/20).

**Comment by XVilka** [comment]
@ivg were there any updates with this issue?

**Comment by ivg** [comment]
Nay still didn't get an access to this version. And it is hard to add support to something that you don't have)

**Comment by XVilka** [comment]
@ivg I think it was fixed already, can be closed, right?

**Comment by ivg** [comment]
indeed!
