### ISSUE TITLE
Following command line input to certain sinks (saluki)

### ISSUE THREAD

**Issue by Dinatrix** [BinaryAnalysisPlatform/bap#712]
Hello,
We were continuing our efforts to write a saluki rule that could see if command line arguments could be used to open and write to a file (in this case for 'ls.coreutils'). Not having luck with our previous method of reusing the existing TAINT/"^src^"_may_leak_into_"^sink definition, we were wondering if there would be a way to combine the cmdline_can_control_stack check with perhaps the untrusted_input or magic_door/source definitions seen below:
```
define cmdline_can_control_stack ::=
  var {x,s,y,p,z} s.t. {s=SP, in_main(s), r/s, p/x}
  rule when_SP_depends_on_main_arg ::=
    s := y, x := *r |- *p := z

let untrusted_input src sink =
  define ("TAINT/"^src^"_may_leak_into_"^sink) [
    rule ("if_there_is_data_dependency")
      [sub src[p]; sub sink[q]]
      [never]
  ] vars [reg *p; reg *q] such that [q/p;]

let magic source is_magic =
  define ("MAGIC/magic_door_via_"^source^"_may_exist") [
    rule ("when_magic_meets_"^source) [
      p := use v;
      sub source[_';x;_'];
      case c jmp _'
    ][never]
  ] vars [reg *x; reg c; reg p; reg v] such
    that [
    forall v such that is_magic;
    c / x;
    c / p;
  ]

let magic_may_leak_into n is_magic sink args =
  define ("MAGIC/magic_may_leak_into_"^sink^"_"^n) [
    rule "when_there_is_data_dependency"
      [p := use v; sub sink args]
      [never]
  ] vars [reg p; reg x; reg v] such
    that [forall v such that is_magic; x/p]
```
Some of the source/sink combinations we were trying are listed below. The only combination that was found was an 'fileno' to 'fclose'. (Could this be due to a lack of ability for saluki to test these rules across methods?) Interestingly it only found the fileno closest to the fclose though there was another fileno two blocks above which presumably would also flow to this sink. (Will saluki only register the 'closest' source to a particular sink? Can it find and mark multiple?)

    untrusted_input "start" "fopen64";
    untrusted_input "main" "fopen64";
    untrusted_input "strrchr" "fopen64";
    untrusted_input "sub_9FE4" "fopen64";
    untrusted_input "__libc_start_main" "fopen64";
    untrusted_input "fopen" "fclose";
    untrusted_input "fopen64" "fclose";
    untrusted_input "__freading" "fclose";
    untrusted_input "freading" "fclose";
    untrusted_input "fopen" "lseek";
    untrusted_input "fopen64" "lseek64";
    untrusted_input "lseek" "fclose";
    untrusted_input "lseek64" "fclose";
    untrusted_input "fileno" "fclose";

One confounding factor that may be preventing saluki from being able to correctly evaluate these taint rules could be a jump table that occurs between the command line argument processing and the actual fopen occurring. Is there a way to write a rule that can follow the taint through the jump table or even write a rule that can walk backwards from the fopen to see what leads to it?

Thank you for the help!
Christina and Pragyan

**Comment by ivg** [comment]
Hi Christina and Pragyan!

I'm sorry for keeping silent on this issue and I understand that it probably is too late to react on this. But nevertheless, we were actually working the whole year on this in the scope of our new microexecution framework called Primus, that you might know about. The good news is that we are no totally able to track those dependencies, moreover in an automatic way. We now have the sensitivity analysis that will track exactly those problems and even will identify program inputs without a need to specify them. It is currently used in the [oo7 framework][1], and soon, I hope with 1.5, we will release it to the public. Please, feel free to contact us, if you need it before, or have any questions. 

[1]: https://arxiv.org/abs/1807.05843
