### ISSUE TITLE
ARM floating-point instructions unsupported?

### ISSUE THREAD

**Issue by gergo-** [BinaryAnalysisPlatform/bap#713]
I tried to analyze a small binary at http://www.complang.tuwien.ac.at/gergo/krempel/test_arm.o with BAP. For reference, this is the (ARMv7, with VFPv3 floating-point) code in it:

```
$ arm-linux-gnueabihf-objdump -d test_arm.o

test_arm.o:     file format elf32-littlearm


Disassembly of section .text:

00000000 <f1>:
   0:	e3000001 	movw	r0, #1
   4:	e3000002 	movw	r0, #2
   8:	e3000003 	movw	r0, #3
   c:	e12fff1e 	bx	lr

00000010 <fn3>:
  10:	eebd1bc0 	vcvt.s32.f64	s2, d0
  14:	ee110a10 	vmov	r0, s2
  18:	e12fff1e 	bx	lr
```

That second function essentially corresponds to the C code `int fn3(double d) { return (int) d; }`.

BAP is happy to show me the intermediate code for the first function, but it says the second one is empty:

```
$ bap test_arm.o -d --no-dead-code-elimination
0000000b: program
00000007: sub f1()
00000002: 
00000003: R0 := 1
00000004: R0 := 2
00000005: R0 := 3
00000006: return LR


0000000a: sub fn3()
00000008: 
00000009: return LR
```

Are some of these floating-point instructions unsupported? If yes, is there a way to run BAP in a mode that complains about unknown instructions? I might be willing to provide patches covering the instructions that interest me.

**Comment by ivg** [comment]
Yes, the floating point instructions are not supported yet. The lifter should make some noise about unsupported instructions in the log file (usually, `~/.local/state/bap/log`). 

Patches are always welcome!

**Comment by gergo-** [comment]
Thanks for the pointer to the log, I didn't know about that. I don't see any lifter messages in there, though. I'll see if I can figure out why, while trying to add those floating-point instructions.

**Comment by ivg** [comment]
Are you using bap 1.3? Also, feeding offending bytes to bap-mc may give
more insights.

**Comment by dbrumley** [comment]
Is this a place where we could use `special` `stmt`'s?

**Comment by ivg** [comment]
Yeah, we can't represent the full semantic of a floating point instruction (like floating point operations, trigonometry, etc, that would be represented with a bunch of `unknown` values and `special` statements), but we can represent the data-flow semantics, i.e., which registers are read, and which are updated (as we do in x86). 

But at some point of time, we will add the full semantics of floating points.

**Comment by gergo-** [comment]
> Are you using bap 1.3?

Yes, 1.3.0 from OPAM. Also, I should note that when I try to do the same thing with an x86 binary, I do get messages about unsupported instructions in the log. But not for ARM.

> but we can represent the data-flow semantics, i.e., which registers are read, and which are updated

That would suffice for my purposes.
