### ISSUE TITLE
bap-ida.1.0 is not compatible with bap.1.2 and bap.1.3

### ISSUE THREAD

**Issue by ivg** [BinaryAnalysisPlatform/bap#719]
The interface has been changed since that time, so when bap-ida.1.0.0 is installed with the latest bap it will fail at runtime (with python import errors). The same is true for the `bap-ida-python` package (in fact the failures are in this package, so they should be constrained to be always of the same version - it should be possible to install bap-ida.X with bap-ida-python.Y when X <> Y).

**Comment by XVilka** [comment]
So I think this can be closed, no?

**Comment by ivg** [comment]
yep
