### ISSUE TITLE
How to add a new architecture?

### ISSUE THREAD

**Issue by jishoon** [BinaryAnalysisPlatform/bap#729]
Hi, I'm a BAP newbie and trying to use BAP to analysis PowerPC instructions. 
As far as I understand, BAP does not support PowerPC lifting. So I just want to work on it. 
But I don't know what is the right way of implementing new lifter. I've looked around 
How X86 and ARM lifter located and works. I found that most of x86 lifter implemented as a BAP plugin
but ARM is implemented as Library(And small plugin that uses ARM lifting library). 
If I am implementing new lifter, should I implement it as a plugin? or library?
Thank you.

**Comment by XVilka** [comment]
Hi! You can check my work-in-progress draft for RISC-V as a rough example https://github.com/BinaryAnalysisPlatform/bap/pull/673

**Comment by ivg** [comment]
What a coincidence, we just started to work on PowerPC! Like two days ago. We are also planning to write a series of blog posts about writing the PPC lifter and lifters in general. I will write the first post today. And @gitoleg will soon create a `ppc` branch so if you want to join us you're absolutely welcome. And everyone are welcome to join the discussion. 

I will elaborate in the blog post, but as a teaser, we are quite unhappy with the lifters that we have so far, so we are planning to find a brave new way to write lifters, that are (a) easy extensible, (b) understandable and supportable. Neither of our existing lifters meet these criteria or even getting close. The rough idea (that we sort of tested on the last few PR's to the x86 lifter), is that we should use as less OCamlisms as possible, the lifter code should be stupidly simple and rely on a very small subset of OCaml, in fact we will define a small sublanguage that should be used for describing instructions semantics as a pseudocode. Basically, the idea is that someone without a working knowledge of OCaml should be able to read, understand, fix, and extend the lifter. 

Concerning the existing lifters, the only reason why one should look at them is to understand how a lifter should not be written. (Though it might be the case that the ppc lifter will have the same fate, we are still searching the right way). Speaking of the @XVilka's work, Anton task is much harder, as he is not only writing a lifter, but implementing a disassembler. Fortunately, we have ppc in LLVM, so we don't need to mess with bits. I also hope, that the riscv lifter will at some point of time benefit from our ppc work, and will follow the same approach. So @XVilka, keep an eye on the ppc lifter.

**Comment by jishoon** [comment]
Thank you @XVilka for point to the nice work! And It is great to hear that BAP has already begun to work on PowerPC with many improvements in the general lifter. I will keep following the PPC branch. Thank you @ivg for your kind explanation and efforts!
