### ISSUE TITLE
how to open the out put of bap-pintrace

### ISSUE THREAD

**Issue by yuruifei** [BinaryAnalysisPlatform/bap#736]
I got a 'exec.frames' via bap-pintrace and tried to use bap to load it  . but failed 

does a '.frames' file be analyzed by bap?　how ?

where can I get more document about the BinaryAnalysisPlatform project?

**Comment by ivg** [comment]
A searchable and cross-referenced [documentation][1] is available online. You can load a trace using the `bap` tool with the [trace][2] plugin. You can view the trace contents directly using the `--trace-dump` command, e.g.,
```
bap --trace-dump=example.frames
```

where `example.frames` is your trace file.  If it fails with the "no provider" error, please install the [bap-frames][4] plugin, that provides a parser for the frames format.

Or, you can load the trace and analyze it programmatically with the [bap-traces][3] library.

```
bap ./example.exe --trace-load=example.frames
```

where `example.exe` is the binary that you were tracing. 

You can also use `bap` built in man pages to get a quick help, e.g., 

```
bap --help
bap --trace-help
```

[1]: http://binaryanalysisplatform.github.io/bap/api/master/argot_index.html
[2]: http://binaryanalysisplatform.github.io/bap/api/master/man1/bap-plugin-trace.1.html
[3]: http://binaryanalysisplatform.github.io/bap/api/master/Bap_traces.Std.html
[4]: http://opam.ocaml.org/packages/bap-frames/

**Comment by yuruifei** [comment]
Thank you for the rapid reply！
