### ISSUE TITLE
bitstring < 3.0.0

### ISSUE THREAD

**Issue by percontation** [BinaryAnalysisPlatform/bap#747]
bitstring seems to have removed their camlp4 preprocessor in version 3.0.0, causing parts of bap's opam install to fail (e.g. bap-elf).

**Comment by ivg** [comment]
I see, we should constrain the version of bitstrings. As a workaround, you can specify constraints on the command line:

```
opam install bap "bitstring<3.0.0"
```

**Comment by ethan42** [comment]
I think you can probably close this now :)

**Comment by ivg** [comment]
not yet... apparently you're not the only one who doesn't know how our build system is working :) I missed the fact, that the `bap-elf` library is disabled by default. So, if it is enabled, and #748 patch is applied, the build fails. @gitoleg  is currently investigating the issue.

**Comment by ivg** [comment]
marking this issue as partially solved. The issue is now tracked in #756
