### ISSUE TITLE
installing bap-std 1.2.0 failed

### ISSUE THREAD

**Issue by yuroc5390** [BinaryAnalysisPlatform/bap#749]
Good day!

I ran into installation problem when issuing "opam depext --install bap", the error is as follows:

# Detecting depexts using flags: x86_64 linux ubuntu
# The following system packages are needed:
#  - binutils-multiarch
#  - camlp4-extra
#  - clang
#  - debianutils
#  - libgmp-dev
#  - libzip-dev
#  - llvm-3.8-dev
#  - llvm-dev
#  - m4
#  - ncurses-dev
#  - perl
#  - pkg-config
#  - zlib1g-dev
# All required OS packages found.
# Now letting OPAM install the packages
The following actions will be performed:
  ∗  install bap-std              1.2.0       [required by bap]
  ∗  install bap-warn-unused      1.2.0       [required by bap]
  ∗  install bap-traces           1.2.0       [required by bap]
  ∗  install bap-term-mapper      1.2.0       [required by bap]
  ∗  install bap-taint            1.2.0       [required by bap]
  ∗  install bap-symbol-reader    1.2.0       [required by bap]
  ∗  install bap-objdump          1.2.0       [required by bap]
  ∗  install bap-microx           1.2.0       [required by bap]
  ∗  install bap-mc               1.2.0       [required by bap]
  ∗  install bap-llvm             1.2.0       [required by bap]
  ∗  install bap-frontend         1.2.0       [required by bap]
  ∗  install bap-dump-symbols     1.2.0       [required by bap]
  ∗  install bap-demangle         1.2.0       [required by bap]
  ∗  install bap-callsites        1.2.0       [required by bap]
  ∗  install bap-cache            1.2.0       [required by bap]
  ∗  install bap-byteweight       1.2.0       [required by bap]
  ∗  install bap-api              1.2.0       [required by bap]
  ∗  install bap-abi              1.2.0       [required by bap]
  ∗  install bap-trace            1.2.0       [required by bap]
  ∗  install bap-taint-propagator 1.2.0       [required by bap]
  ∗  install bap-beagle           1.2.0       [required by bap]
  ∗  install bap-print            1.2.0       [required by bap]
  ∗  install bap-c                1.2.0       [required by bap]
  ∗  install bap-x86              1.2.0       [required by bap]
  ∗  install bap-frontc           1.2.0       [required by bap]
  ∗  install bap-arm              1.2.0       [required by bap]
  ∗  install bap                  1.2.0
===== ∗  27 =====
Do you want to continue ? [Y/n] y

=-=- Gathering sources =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

[bap-abi] Archive in cache
[bap-api] Archive in cache
[bap-arm] Archive in cache
[bap-beagle] Archive in cache
[bap-byteweight] Archive in cache
[bap-c] Archive in cache
[bap-cache] Archive in cache
[bap-callsites] Archive in cache
[bap-demangle] Archive in cache
[bap-dump-symbols] Archive in cache
[bap-frontc] Archive in cache
[bap-frontend] Archive in cache
[bap-mc] Archive in cache
[bap-microx] Archive in cache
[bap-objdump] Archive in cache
[bap-print] Archive in cache
[bap-std] Archive in cache
[bap-symbol-reader] Archive in cache
[bap-taint] Archive in cache
[bap-taint-propagator] Archive in cache
[bap-term-mapper] Archive in cache
[bap-trace] Archive in cache
[bap-traces] Archive in cache
[bap-warn-unused] Archive in cache
[bap-x86] Archive in cache
[default] https://opam.ocaml.org/archives/bap-llvm.1.2.0+opam.tar.gz downloaded
[default] https://opam.ocaml.org/archives/bap.1.2.0+opam.tar.gz downloaded
=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Processing  1/27: [bap-std: make]

The following actions failed
  ∗  install bap-std 1.2.0
No changes have been performed

=-=- bap-std.1.2.0 troobleshooting =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
**=> This package relies on external (system) dependencies that may be missing. `opam depext
   bap-std.1.2.0' may help you find the correct installation for your system.**

However when I run 'opam depext  bap-std.1.2.0', the result says all required OS packages found:
# Detecting depexts using flags: x86_64 linux ubuntu
# The following system packages are needed:
#  - camlp4-extra
#  - clang
#  - libgmp-dev
#  - libzip-dev
#  - m4
#  - ncurses-dev
#  - perl
#  - pkg-config
#  - zlib1g-dev
# All required OS packages found.

I'm using ubuntu 14.04 64 bit, llvm-3.4 and clang-3.4. I have no idea what could be possibly wrong. It would be great if somebody can help me.

**Comment by ivg** [comment]
There is some compilation error, that you didn't copy to the issue report. Can you please provide it. What I see from the log it's that bap installation has failed.

Besides, bap.1.2 is an old version. I would suggest to use the latest bap.1.3

**Comment by yuroc5390** [comment]
Thanks for the quick reply! You are right, I missed the compilation error. Here it is:
# /home/yuroc/.opam/system/bin/ocamlfind ocamlc -g -ccopt -O2 -c lib/bap_disasm/disasm_stubs.c
# + `which clang++` -O2 -std=c++11 -fPIC -I/usr/lib/ocaml -I/home/yuroc/.opam/system/lib/bap -Ilib/bap_disasm -c lib/bap_disasm/disasm.cpp -o lib/bap_disasm/disasm.o
# /bin/sh: 1: -O2: not found
# Command exited with code 127.
### stderr ###
# make: *** [Makefile:4: build] Error 1

And could you please tell me how to get bap 1.3? I just clone the bap from github directly. Thank you again.

**Comment by ivg** [comment]
I see, for some reason `clang++` wasn't installed. Theoretically depext should handle it. As a workaround, try to install it manually. The clang++ binary should be available in the PATH.

**Comment by yuroc5390** [comment]
Perfect! clang++-3.4 is there but clang++ is missing. I created a link then problem solved. Thank so much!
