### ISSUE TITLE
Enable bap-elf

### ISSUE THREAD

**Issue by gitoleg** [BinaryAnalysisPlatform/bap#756]
`bap-elf` library is currently disabled by default. The reason is a weird error that we have with `ppx_driver` and `bitstring.ppx` :
```
Error: Extension `bitstring' was not translated
```
According to https://github.com/janestreet/ppx_driver/issues/14 this issue was solved, so we need to wait for a new version of `ppx_driver`.
Also, we will have to update `bap` code to meet the interface changes in core v.0.10 in order to use a new version of `ppx_driver`

**Comment by ivg** [comment]
so far bap-elf was upper bounded in the upstream, see https://github.com/ocaml/opam-repository/pull/11328
