### ISSUE TITLE
opam

### ISSUE THREAD

**Issue by BrunoDutertre** [BinaryAnalysisPlatform/bap#76]
The opam file that comes with bap is unreliable. It would be nice to
give 'opam install bap' an option to specify where to find llvm-config.
I don't know how to do this.

Another issue, is that 'opam remove' tries to run ./configure, which
can fail miserably and leave the .opam directory in a messy state.
This is annoying because opam will automatically attempt to remove
bap (and then recompile it) when you install something else (like utop).

It would be more robust to change the opam file as follows:

remove: [
  ["ocamlfind" "remove" "bap"]
  ["ocamlfind" "remove" "core_lwt"]
  ["rm" "-f" "%{bin}%/bap-mc" "%{bin}%/bap-server" "%{bin}%/baptop"
             "%{bin}%/bapbuild" "%{bin}%/train" "%{bin}%/readbin"
            "%{bin}%/fbi" "%{bin}%/byteweight"]
]

Bruno

**Comment by ivg** [comment]
The second issue is known, and will be fixed in a few days. I hope that it will be tomorrow. What concerning giving an option for `opam install bap`, it is not under my control. Unfortunately, `opam` doesn't provide any facilities to pass configuration options from install command.  The only solution that I see, is to pass it using environment. If you have any ideas, I will be grateful to hear for them. And thanks for the feedback!

**Comment by ivg** [comment]
By the way, `configure` script in bap is trying its best to find `llvm-config` on different setups. It works on debians, ubuntus and macports. If for your system it fails, can you, please, provide details, so that I can tailor it properly.

**Comment by BrunoDutertre** [comment]
Thanks for the feedback. Unfortunately,  I have different versions of LLVM installed in different 
places. There's no hope for an automatic configure to find the right one. Setting an environment
variable would be just fine for me.

**Comment by ivg** [comment]
ok, will be done.

**Comment by ivg** [comment]
actually, after some investigation I've figured out that it is already done!

you can specify any variable that is configurable via `configure` script with environment variables, like
```
llvm_config=llvm-config-3.4 opam install bap
```

Currently there're two options of interest:
- `llvm_version`  accepts version number and tries to find `llvm-config` executable with a correct number. Example, `llvm_version=3.4`

- `llvm_config` is a path to `llvm-config` executable.

Please note, that currently BAP is tested only with `3.4`. `3.3` should also work. `3.5` from ubuntu repository will also work, but a real `3.5` from the upstream won't.

Hope, that this helps!

**Comment by ivg** [comment]
Also, you can actually provide any command line arguments to configure using environment variable `BAPCONFIGUREGLAGS`. 
```
export BAPCONFIGUREFLAGS="--prefix=`opam config var prefix` --enable-tests --enable-serialization"
```
There also, `BAPINSTALLFLAGS`, `BAPREINSTALLFLAGS`, `BAPBUILDFLAGS` and [so on](https://github.com/BinaryAnalysisPlatform/bap/blob/master/Makefile).

Some tips can be also found [here](https://github.com/BinaryAnalysisPlatform/bap/wiki/Build-tips-and-tricks).

**Comment by BrunoDutertre** [comment]
Thanks for the info
