### ISSUE TITLE
Cannot run bap pass

### ISSUE THREAD

**Issue by haojie0429** [BinaryAnalysisPlatform/bap#814]
Hi, I already installed bap and tried to run the example pass and built-in pass, but I got the following errors:

Failed to create a project: ("Unknown image loader <no-loaders-available>"
  "Raised at file \"src/import0.ml\" (inlined), line 234, characters 22-32\
 \nCalled from file \"src/error.ml\" (inlined), line 9, characters 14-30\
 \nCalled from file \"src/or_error.ml\", line 70, characters 17-32\
 \nCalled from file \"lib/bap/bap_project.ml\", line 242, characters 47-54\
 \nCalled from file \"src/or_error.ml\", line 62, characters 9-15\
 \n")

I have tried both ocaml and python writing the example pass.

Does someone have any idea what's going wrong? Thanks so much.

**Comment by ivg** [comment]
Can you provide the commands that you're using to compile, install, and run the example pass?

**Comment by haojie0429** [comment]
Sure. I was using the following commands.

opam init --comp=4.05.0              # install the compiler
eval `opam config env`               # activate opam environment
opam depext --install bap            # install bap

pip3 install bap    

[whj@wukong bap]$ bapbuild jmp.plugin
Finished, 8 targets (8 cached) in 00:00:00.
[whj@wukong bap]$ bapbundle install jmp.plugin
[whj@wukong bap]$ bap /bin/true --pass=jmp
Failed to create a project: ("Unknown image loader <no-loaders-available>"
  "Raised at file \"src/import0.ml\" (inlined), line 234, characters 22-32\
 \nCalled from file \"src/error.ml\" (inlined), line 9, characters 14-30\
 \nCalled from file \"src/or_error.ml\", line 70, characters 17-32\
 \nCalled from file \"lib/bap/bap_project.ml\", line 242, characters 47-54\
 \nCalled from file \"src/or_error.ml\", line 62, characters 9-15\
 \n")


[whj@wukong bap]$ python3 jmp.py
Traceback (most recent call last):
  File "jmp.py", line 15, in <module>
    proj = bap.run('/bin/true')
  File "/usr/local/lib/python3.5/site-packages/bap/bap.py", line 132, in run
    raise Failed(bap.returncode, opts, out, err)
bap.bap.Failed: exited with return code 1

        Standard output:
b''

        Standard error: 
b'Failed to create a project: ("Unknown image loader <no-loaders-available>"\n  "Raised at file \\"src/import0.ml\\" (inlined), line 234, characters 22-32\\\n \\nCalled from file \\"src/error.ml\\" (inlined), line 9, characters 14-30\\\n \\nCalled from file \\"src/or_error.ml\\", line 70, characters 17-32\\\n \\nCalled from file \\"lib/bap/bap_project.ml\\", line 242, characters 47-54\\\n \\nCalled from file \\"src/or_error.ml\\", line 62, characters 9-15\\\n \\n")\n'

        Invoked as: bap /bin/true -dadt


The pass is written exactly the same as the example.

**Comment by ivg** [comment]
Interesting, just wondering what OS are you using? And what the `file /bin/true` is telling? In fact, can you, please, provide the ~/. local/state/bap/log file and the /bin/true file? Just zip them and upload to the issue.

**Comment by ivg** [comment]
OK, I see, so the problem is that you don't have the llvm plugin installed, neither any other plugin, that is capable of parsing ELF files, so bap fails to parse the file and ends up with a (very confusing) error message. 

Since you were installing bap from file, I would expect that there were errors during the installation, that you've ignored, did you? 

Besides, what does `opam info bap` show?

P.S. According to the log, you basically installed 5% of bap, you don't have file parser, disassemblers, lifters, basically the whole bap is not installed.

**Comment by haojie0429** [comment]
[whj@wukong bap]$ opam info bap
             package: bap
             version: 1.4.0
          repository: default
        upstream-url: https://github.com/BinaryAnalysisPlatform/bap/archive/v1.4.0.tar.gz
    upstream-mirrors: { https://mirrors.aegis.cylab.cmu.edu/bap/1.4.0/v1.4.0.tar.gz }
       upstream-kind: http
   upstream-checksum: b7785715c24645e8e69a8091427d090e
            homepage: https://github.com/BinaryAnalysisPlatform/bap/
         bug-reports: https://github.com/BinaryAnalysisPlatform/bap/issues
            dev-repo: git://github.com/BinaryAnalysisPlatform/bap/
              author: BAP Team
             license: MIT
             depends: bap-abi = 1.4.0 & bap-api = 1.4.0 & bap-arm = 1.4.0 & bap-beagle = 1.4.0 & bap-byteweight = 1.4.0 & bap-c = 1.4.0 & bap-cache = 1.4.0 & bap-cxxfilt = 1.4.0 & bap-callsites = 1.4.0 & bap-demangle = 1.4.0 & bap-dead-code-elimination = 1.4.0 & bap-dump-symbols = 1.4.0 & bap-frontend = 1.4.0 & bap-frontc = 1.4.0 & bap-llvm = 1.4.0 & bap-mc = 1.4.0 & bap-microx = 1.4.0 & bap-mips = 1.4.0 & bap-objdump = 1.4.0 & bap-powerpc = 1.4.0 & bap-primus = 1.4.0 & bap-primus-dictionary = 1.4.0 & bap-primus-lisp = 1.4.0 & bap-primus-region = 1.4.0 & bap-primus-support = 1.4.0 & bap-primus-test = 1.4.0 & bap-primus-x86 = 1.4.0 & bap-print = 1.4.0 & bap-relocatable = 1.4.0 & bap-report = 1.4.0 & bap-run = 1.4.0 & bap-ssa = 1.4.0 & bap-std = 1.4.0 & bap-strings = 1.4.0 & bap-symbol-reader = 1.4.0 & bap-taint = 1.4.0 & bap-taint-propagator = 1.4.0 & bap-term-mapper = 1.4.0 & bap-trace = 1.4.0 & bap-traces = 1.4.0 & bap-trivial-condition-form = 1.4.0 & bap-warn-unused = 1.4.0 & bap-x86 = 1.4.0
   installed-version: 
  available-versions: 0.9.1, 0.9.2, 0.9.3, 0.9.4, 0.9.5, 0.9.6, 0.9.7, 0.9.8, 0.9.9, 1.0.0, 1.1.0, 1.2.0, 1.3.0, 1.4.0
         description: Binary Analysis Platform.


The Carnegie Mellon University Binary Analysis Platform (CMU BAP) is a
reverse engineering and program analysis platform that works with
binary code and doesn't require the source code. BAP supports multiple
architectures: ARM, x86, x86-64, PowerPC, and MIPS. BAP disassembles
and lifts binary code into the RISC-like BAP Instruction Language
(BIL). Program analysis is performed using the BIL representation and
is architecture independent in a sense that it will work equally well
for all supported architectures. The main purpose of BAP is to provide
a toolkit for implementing automated program analysis. BAP is written
in OCaml and it is the preferred language to write analysis, but we
have bindings to C, Python and Rust. The Primus Framework also provide
a Lisp-like DSL for writing program analysis tools.

This is a meta package that installs essential parts of BAP.

OK, thanks for your help. I'll try to re-install bap to see if it will work.

**Comment by ivg** [comment]
Yep, as you may see the `bap` meta package is not installed:

```
installed-version:
available-versions: 0.9.1, 0.9.2, 0.9.3, 0.9.4, 0.9.5, 0.9.6, 0.9.7, 0.9.8, 0.9.9, 1.0.0, 1.1.0, 1.2.0, 1.3.0, 1.4.0
```

We can debug your installation. If you wish so, then please tell me what does `llvm-config --version` tell you?

Besides, if you want to get your bap up and running as fast as possible, then you can use a [vagrant][1] file of your taste. For example, for jessie, if you have vagrant installed on you system just do:

```
mkdir bap-jessie; cd bap-jessie
wget  https://raw.githubusercontent.com/BinaryAnalysisPlatform/bap/master/vagrant/jessie64/Vagrantfile
vagrant up
vagrant ssh
```

Also, you may opt to take both paths, debug the installation and enjoy bap in a VM in parallel :)

[1]: https://github.com/BinaryAnalysisPlatform/bap/tree/master/vagrant

**Comment by haojie0429** [comment]
It would be great if you can help with my installation. 

[whj@wukong bap]$ llvm-config --version
7.0.0svn

**Comment by haojie0429** [comment]
I'm trying to figure out how to use vagrant.

**Comment by ivg** [comment]
```
llvm-config --version
7.0.0svn
```

Well you're a little bit ahead of time :) We added support for LLVM 6.0 only recently, and bap 1.4 supports only up to LLVM 5.0. So, the first thing that you need, is to install LLVM 5.0 on you system (or 3.4, 3.8, 4.0, if you have any objections against 5.0). There is no need to disturb you `7.0.0svn` version (that you might be using for your own purposes) as you can tell the bap-llvm package which `llvm-config` it should use during the installation, using the following command (substitute 5.0 with the version of your choice) :

```
LLVM_CONFIG=llvm-config-5.0 opam reinstall conf-bap-llvm --yes
```

Then double check that `opam` got your request correct, by asking the following question:
```
opam config var conf-bap-llvm:package-version
```
The reply should contain the version that you've specified (possibly with the minor version number). If that is not true, then make sure, that you indeed have the specified llvm-config-xx binary (our build script is a little bit to permissive, as it simply ignores the variable if it specifies a non-existent version).

Finally, we can install opam and be happy:

```
opam install bap
```

Once everything installed, you may optionally install the IDA support and integration package (in case if you have IDA Pro >= 6.6 && < 7.0 installed), with `opam install bap-ida`

**Comment by haojie0429** [comment]
OK, I'll try with llvm 5.0. Thanks again for your help. I'll post it here if I have any further problems.

**Comment by haojie0429** [comment]
Thank you so much for your help. I've already successfully installed and run bap. @ivg
