### ISSUE TITLE
Build error on ARM

### ISSUE THREAD

**Issue by toshipiazza** [BinaryAnalysisPlatform/bap#825]
When building the Primus framework on a 32-bit ARM machine, I get the following error around [here](https://github.com/BinaryAnalysisPlatform/bap/blob/master/lib/bap_primus/bap_primus_random.ml#L16):

```
Error: Integer literal exceeds the range of representable integers of type int
```

**Comment by ivg** [comment]
Sure, we will fix it, thanks for the report. 

But with that said, I would highly advise not to use BAP on a 32 bit platform. This will have severe impact on performance.
