### ISSUE TITLE
Installation fails due to obsolete package using Mac port

### ISSUE THREAD

**Issue by ivolz** [BinaryAnalysisPlatform/bap#828]
I am using OSX High Sierra and following the instructions, the installation fails:

opam init --comp=4.05.0
eval `opam config env`
opam depext --install bap

This causes Mac ports to trigger an installation:

.# Detecting depexts using flags: x86_64 osx macports
.# The following system packages are needed:
.#  - arm-aout-binutils
.#  - arm-elf-binutils
.#  - arm-none-eabi-binutils
.#  - gmp
.#  - i386-elf-binutils
.#  - i386-mingw32-binutils
.#  - libzip
.#  - llvm-3.8
.#  - x86_64-elf-binutils
The following command needs to be run through "sudo":
    port install arm-aout-binutils arm-elf-binutils arm-none-eabi-binutils gmp i386-elf-binutils i386-mingw32-binutils libzip llvm-3.8 x86_64-elf-binutils
Allow ? [Y/n] Y
Password:

The build fails with following error message:

--->  Fetching distfiles for i386-mingw32-binutils
--->  Verifying checksums for i386-mingw32-binutils
--->  Extracting i386-mingw32-binutils
--->  Configuring i386-mingw32-binutils
Error: i386-mingw32-binutils has been replaced by i686-w64-mingw32-binutils; please install that instead.
Error: Failed to configure i386-mingw32-binutils: obsolete port
Error: See /opt/local/var/macports/logs/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_cross_i386-mingw32/i386-mingw32-binutils/main.log for details.
Error: Follow https://guide.macports.org/#project.tickets to report a bug.
Error: Processing of port i386-mingw32-binutils failed
OS package installation failed

I can install manually the replacement package but the opam command still fails to execute since the obsolete package is a requirement.

**Comment by ivg** [comment]
The `opam depext` command is an optional step, that will rely on some heuristic to perform the set up of your system packages. Quite often it doesn't work. It also doesn't provide lots of options for the packagers to specify their requirements. So if it doesn't work, it shouldn't be a surprise, you should take the reins and install all the system dependencies manually. It looks like that this is what you did. Now you can proceed normally without relying on the `depext` command, and using the normal install command, e.g., 

```
opam install bap
```

Make sure, that you indeed have installed all required system packages, though.
