### ISSUE TITLE
Expose division-by-zero error occurring during Primus interpretation

### ISSUE THREAD

**Issue by mjambon** [BinaryAnalysisPlatform/bap#839]
Would it be possible to get a dedicated `Primus.Interpreter.Division_by_zero` just like there is a `Primus.Interpreter.Halt` (https://github.com/BinaryAnalysisPlatform/bap/blob/master/lib/bap_primus/bap_primus_interpreter.ml#L233)? (or perhaps something in-between like exposing the existing `Primus.Interpreter.Runtime_error "Division by zero"` with that string being documented?)

Right now we're pattern-matching against the string `"Bap_primus runtime error: Division by zero"` that we produce with `Primus.Exn.to_string`, which is brittle.

**Comment by ivg** [comment]
Sounds reasonable, will do.

**Comment by mjambon** [comment]
Cool, thank you!

**Comment by ethan42** [comment]
if you do that, please expose Segmentation faults as well (this may already be in dev, I'm just not aware of it)

**Comment by ivg** [comment]
OK, though I'm started to ask myself whether we should represent division-by-zero and segmentation faults as CPU exceptions. It sounds right, except that the numbering is abi specific

**Comment by ivg** [comment]
The problem that I face, is that we can't stop Interpreter from diverging, in case of the division by zero error. So, there's no problem in exposing it, but it has a very limited use, at least in my whole program execution case.

**Comment by ivg** [comment]
I think that I will thread errors via observations, and implement ABI specific handlers, that will raise corresponding exceptions.

**Comment by ivg** [comment]
fixed in #840
