### ISSUE TITLE
ADT hex values not prefixed with "0x"

### ISSUE THREAD

**Issue by drevilt** [BinaryAnalysisPlatform/bap#842]
when outputting into ADT format I receive values like this:

```
Section(".text", 3c60,...
```

or

```
Region(3c60,1644e)
```

those values are supposed to be hex values but are not prefixed with a "0x" hence
I get syntax errors when trying to "eval()" them.

In Python for example I get:

```
  File "<string>", line 1
    Region(3c60,1644e))
              ^
SyntaxError: invalid syntax
```

I get this for `Sections` and `Regions` but it could be broken for others as well.

I think the problem lies somewhere in here:

https://github.com/BinaryAnalysisPlatform/bap/blob/d5816c187d16a2e60882130b41f417d9d4aa1fc9/plugins/print/print_main.ml#L205-L208

**Comment by ivg** [comment]
This is a known issue, that was fixed in the latest released version of bap-python bindings. Somehow, it managed to miss the master version of the github repository (perhaps, I made the release from my dev branch). I will push the fix to the upstream master soon, meantime, you can just use the pip version, e.g., `pip install bap`

**Comment by drevilt** [comment]
I dont think this is a bap-python issue. The ADT-output came from a command like `bap -d adt /some/exe` therefore the bap executable itself is already producing un-eval-able output. None of the bap-python classes have been instantiated at that point of time.

**Comment by ivg** [comment]
Well, it could be fixed on both sides - on the printer side, and on the parser side. I decided the latter as it was more general, and versions of bap that prints sections and regions in such format already exist in the wild life, so it is better to be able to parse them.

**Comment by ivg** [comment]
here is the link to the fix, that I've just backported from the released version https://github.com/BinaryAnalysisPlatform/bap-python/pull/9

I will also eventually fix the printing part, so I will keep this issue open.

**Comment by drevilt** [comment]
I was just wondering how I could even get to a point where it even tries to do something with the bap-python
classes. For example if you have this python code:
```
>>> eval("int(12)")
12
>>> eval("int(1a)")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<string>", line 1
    int(1a)
         ^
SyntaxError: invalid syntax
>>>
```

As you can see even though the int class is valid, because I did not prefix the lower value with a "0x" I get this SyntaxError. My intention was to use something like this:
```
>>> from bap.bir import *
>>> content = open("/path/to/some/file.adt").read()
>>> project = eval(content)
```

Is this wrong ? Because this way I cannot see how I can get past that SyntaxError. Maybe do i need to use another eval/parser function?

**Comment by ivg** [comment]
If you will try to eval them directly, then the fix won't work. However, we're using for a long time the no_eval parser, that is much faster. You can use it directly, or via `bap.run` function. 

The main problem with the python's eval parser, is that it unable to handle large files, due to a very limited stack of the parser.

**Comment by drevilt** [comment]
Oh I see, your PR references the noeval parser. I was intending to use the builtin eval of python.

**Comment by ivg** [comment]
Also, the following code will do what you want:
```python
>>> import bap
>>> content = open("/path/to/some/file.adt").read()
>>> project = bir.loads(content)
```

Do you have any special reasons to use the eval parser?

**Comment by drevilt** [comment]
thanks for the hint. No I dont have any special reason for the builtin eval. I was just using it because it seemed simple enough for the job.
