### ISSUE TITLE
BIL Store Typechecker too lenient

### ISSUE THREAD

**Issue by DIJamner** [BinaryAnalysisPlatform/bap#843]
The call to `infer` in this example returns `Ok`, but `eval` fails with a type error:
```
Open Bap.Std;;
let m = Bil.store ~mem:(Bil.unknown "mem" (Type.mem `r64 `r8))
          ~addr:(Bil.int (Word.one 8)) (Bil.int (Word.one 8)) 
          LittleEndian `r8;;
Type.infer m;;
Exp.eval m;;
```

**Comment by DIJamner** [comment]
The infer function at [`bap_helpers.ml#L226`](https://github.com/BinaryAnalysisPlatform/bap/blob/a691e22626e1541e9ad07e4f49baf9c1f982145d/lib/bap_types/bap_helpers.ml#L226) only checks that the memory's address width is at least the width of the input address. Is there a case where BAP should allow it to be greater than or should it always be equal?

**Comment by ivg** [comment]
gosh, what a typo! it should be `<>` of course, not `<`

**Comment by gitoleg** [comment]
fixed in https://github.com/BinaryAnalysisPlatform/bap/pull/847
