### ISSUE TITLE
Bil Store Eval doesn't infer types properly

### ISSUE THREAD

**Issue by DIJamner** [BinaryAnalysisPlatform/bap#846]
The call to `infer` in this example returns `Ok`, but `eval` fails with a type error:
```
open Bap.Std;;
open Bil;;
let addr = int (Word.zero 64);;
let m = (unknown "mem" (Type.mem `r64 `r8));;
let m' = store ~mem:m ~addr (int (Word.zero 8)) LittleEndian `r8;;
Type.infer m';;
Exp.eval m';;
```

This is likely due to one of the type inference functions used in `Exp.eval`, probably [bap_helpers.ml#679](https://github.com/BinaryAnalysisPlatform/bap/blob/b4ecb65eafb318e885541be0c3602e73f1e6519e/lib/bap_types/bap_helpers.ml#L679)

**Comment by gitoleg** [comment]
fixed in https://github.com/BinaryAnalysisPlatform/bap/pull/847
