### ISSUE TITLE
Is there a python API to output the start address of all funcions?

### ISSUE THREAD

**Issue by yasong** [BinaryAnalysisPlatform/bap#849]
Is there a python API to output the start address of all funcions? I cannot find it in the API docs. Thank you.

**Comment by ivg** [comment]
You can get a list of functions and look for their `'address'` attribute, e.g.,
```python
[s.attrs['address'] for s in proj.program.subs]
```

If you need function starts and only function starts, then you can write your own project loader, that will ask bap only for symbols and nothing more, e.g.,

```python
import bap

extra = [
'--print-symbol-format=name',
'--print-symbol-format=addr'
]


def parse_symbols(data):
    addrs = {}
    for s in data.splitlines():
        name, addr = s.strip().split(' ')
        addrs[name] = int(addr,16)
    return addrs


s = bap.run('/bin/true', args=extra, parser={'format': 'symbols', 'load': parse_symbols})
```

the returned value would be a mapping from names to addresses.

**Comment by yasong** [comment]
Thank you, I will have a try.
