### ISSUE TITLE
implement IDA brancher

### ISSUE THREAD

**Issue by ivg** [BinaryAnalysisPlatform/bap#861]
The IDA part of the brancher has been implemented a long time ago in #550 and since then [was added][1] to the master branch of the bap-ida-python integration package. 

The BAP part though is still not there. What is left, is to implement a parser that will parse the brancher's service output and implement a brancher interface. And debug it. 

[1]: https://github.com/BinaryAnalysisPlatform/bap-ida-python/blob/master/plugins/bap/utils/ida.py#L86-L92

**Comment by XVilka** [comment]
@ivg so this can be closed, right?

**Comment by ivg** [comment]
Indeed! Finally :)
