### ISSUE TITLE
installation bap-std 1.4.0 fails

### ISSUE THREAD

**Issue by 251** [BinaryAnalysisPlatform/bap#877]
Compilation fails with the follwing error message: [bap-std.err.txt](https://github.com/BinaryAnalysisPlatform/bap/files/2407083/bap-std.err.txt) The installation for the other dependencies succeeded.

**Comment by ivg** [comment]
It looks like that on your system you have a version of clang that is incapable of compiling C++ standard library. Can you provide some information about your system, and versions of clang++ and c++ std library? Meantime, I would suggest you to upgrade/downgrade clang, or make sure that you are using a version provided by the vendor of your OS.

**Comment by 251** [comment]
You're right, it might have picked up the wrong clang version. Unfortunately, [configure](https://github.com/ocaml/opam-repository/blob/7228225648a38479a0ed8d971426844f6ef3eab1/packages/bap-std/bap-std.1.4.0/opam#L13) seems to be hard-coded to clang++. On my system clang++ is v3.6.2, clang++-6.0 is the current one and libstdc++ is v8.2.1. I worked around that but than it fails in `bap-llvm` as it looks for a header file in the wrong place:
```
# lib/bap_llvm/llvm_disasm.cpp:10:10: fatal error: 'llvm/Target/TargetInstrInfo.h' file not found
# #include <llvm/Target/TargetInstrInfo.h>
#          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
It is already fixed. Is there an easy way to install the release candidates (v1.5.0)? Sorry for that. I'm not used to opam and stopped programming Ocaml many years ago.

**Comment by ivg** [comment]
Yes, there is an easy way to install it, just add our testing repository with

```
opam repo add bap-testing https://github.com/BinaryAnalysisPlatform/opam-repository
```
and then you can install the latest master version.

The root of the problem, however, is that you have LLVM 6.0 installed, while BAP 1.4 supports only 1.5 (as it was released before LLVM 6.0). The support for LLVM 6.0 was added only 6 months ago. 

So, you can either switch to the bap 1.5 release candidate (we expected to land it soon to the upstream repo), or install an older version of LLVM on your system.

**Comment by 251** [comment]
```
$ opam repo add bap-testing https://github.com/BinaryAnalysisPlatform/opam-repository
[ERROR] Could not update repository "bap-testing": OpamDownload.Download_fail(_, "curl: code 404 while
        downloading https://github.com/BinaryAnalysisPlatform/opam-repository/index.tar.gz")
[ERROR] Initial repository fetch failed
```
Is this Opam 2.0 related? Maybe I just wait for the release... Thanks again Ivan.

**Comment by 251** [comment]
I had some time to compile LLVM 5.0 and the build process went through without errors. It would be nice if you could add `ctypes-foreign` to the dependency section for `bap-bindings`.
