### ISSUE TITLE
Use bap to analysis ARM binaries

### ISSUE THREAD

**Issue by valour01** [BinaryAnalysisPlatform/bap#878]
Hi, I am new to bap and would like to use it to do binary analysis on ARM architecture.
I have the following requirements.  I hope to get the instruction boundary, function boundary, function signature, control flow graph, and call graph of a binary. I am not sure whether bap support all the features I list above. 

If so, any reference I could follow? Do I need to write some plugins? Thank you so much for your help

**Comment by ivg** [comment]
Yep, everything is supported. For starters, you can just do `--dump=cfg` and `--dump=callgraph`. Feel free to drop gitter if you have any questions.

**Comment by valour01** [comment]
I would like to write a pass to extract the control flow graph based on the machine code level. I write a part of the code. However, I lost in what to do next

I reviewed the bap.mli and I think the `Disasm.cfg (Project.disasm p) ` should be the right way to extract the machine code level cfg.

Then I would like to print out the node and the edge. I created two functions `print_bb` and `print_bb_edge`. However, It seems the module edge is based on IR level? I don't know how to iterate the edge to get the information I need. It would be great if you can give me some hints? Actually, I would like also to print out the instruction address inside every basic block. Thank you so much. I am also very sorry that the question might be a little bit... stupid since I am really new to Ocaml. Thanks again.

```
open Core_kernel.Std
open Bap.Std
open Graphlib.Std
open Format

let print_bb block = 
    printf block.addr

let print_bb_edge edge = 
    

let main p = 
  let cfg = Disasm.cfg (Project.disasm p) in
  match cfg with 
  |node -> print_bb node
  |edge -> print_bb_edge edge
    

let () = Project.register_pass' main

```

**Comment by ivg** [comment]
Hey, no problems and don't be afraid to ask, you may also consider dropping by gitter or discord for a quick chat. 

Your idea is close to be right, however `Project.disasm` returns the full program control flow graph, before it got sliced into functions. I believe that you want a function CFG, so my suggestion is to use the symtab, which is basically a collection of control flow graphs for each identified function. It is very easy to print a graph using the [Graphlib.to_do][3] function, which is a swiss-army knife for graph printing. Here is the code for a plugin, that will register a printer, that will print a control flow graph for each function, denoting each block with its virtual address

```ocaml
open Regular.Std
open Graphlib.Std
open Bap.Std
open Format
include Self()

let pp_fn ppf (name,_,g) =
  Graphlib.to_dot (module Graphs.Cfg)
    ~formatter:ppf
    ~graph_attrs:(fun _ -> [`Label name])
    ~string_of_node:(fun n ->
        sprintf "%S" @@ Addr.string_of_value (Block.addr n))
    g

let pp_cfg ppf proj =
  Project.symbols proj |>
  Symtab.to_sequence |>
  Seq.iter ~f:(fprintf ppf "%a@\n" pp_fn)

let () = Config.when_ready (fun _ ->
    Project.add_writer ~ver:"1.0.0"
      ~desc:"print a simple CFG"
      "rcfg"
      (Data.Write.create ~pp:pp_cfg ()))
```

To compile and install put this in a file in a separate empty folder, e.g.,

```
mkdir rawcfg
cd rawcfg
# put the code above into the rawcfg.ml file
bapbuild rawcfg.plugin
bapbundle install rawcfg.plugin
```

Now, you can do 

```
bap ./exe -drcfg
```
to get all control flow graphs of a program. You can play with the plugin by changing the way how the nodes and edges are printed, or which functions to print. You can use the [tutorial][4] for the inspiration. 

[1]: https://gitter.im/BinaryAnalysisPlatform/bap
[2]: https://discord.gg/bwJ3p7q
[3]: http://binaryanalysisplatform.github.io/bap/api/master/Graphlib.Std.Graphlib.html#VALto_dot
[4]: https://github.com/BinaryAnalysisPlatform/bap-tutorial
