### ISSUE TITLE
Nicer handling of non-executables

### ISSUE THREAD

**Issue by dbrumley** [BinaryAnalysisPlatform/bap#895]
Would be nice if BAP did some basic sanity checking with an error for unhandled file types.

Example:
```
$ touch /tmp/foo.txt
$ bap /tmp/foo.txt 
Failed to create a project: ("File corrupted"
  "Raised at file \"src/import0.ml\" (inlined), line 234, characters 22-32\
 \nCalled from file \"src/error.ml\" (inlined), line 9, characters 14-30\
 \nCalled from file \"src/or_error.ml\", line 70, characters 17-32\
 \nCalled from file \"lib/bap/bap_project.ml\", line 264, characters 47-54\
 \nCalled from file \"src/or_error.ml\", line 62, characters 9-15\
 \n")
$ bap --version
1.5.0
```

I'm not sure what's possible here, but I'd expect a message like "not an executable".

Side note: the `\n` in the output is a bit funky.

**Comment by ivg** [comment]
I would expect `"Unsupported file format"`<sup>1</sup>, possibly with additional information about supported formats and options to specify them. 

------
<sup>1</sup>)We support libraries, kernel modules, and raw bits of code, which probably are not executables.
