### ISSUE TITLE
Provide a good way to add the plugin-defined things to the BAP Project

### ISSUE THREAD

**Issue by XVilka** [BinaryAnalysisPlatform/bap#898]
It might be my ignorance or misunderstanding, but I wasn't able to find a way to extend Project in some way sharing the results of BAP plugin work. Most of the plugins I checked provide their own means of the output. What will be the way to access some random plugin results with BAP API?

**Comment by ivg** [comment]
We use universal [values][1] for that. You can use either predefined tags or declare your own. Plugin developers decide whether they are going to make their tags public or not. 

[1]: http://binaryanalysisplatform.github.io/bap/api/master/Bap.Std.Value.html

**Comment by XVilka** [comment]
Thanks for the answer, so probably can be closed then.
