### ISSUE TITLE
`addr32 callq` instruction is dropped

### ISSUE THREAD

**Issue by tobast** [BinaryAnalysisPlatform/bap#901]
It seems that BAP does not handle [address size overrides](https://wiki.osdev.org/X86-64_Instruction_Encoding#Operand-size_and_address-size_override_prefix), eg. `67 e8 fd 4b 00 00` (which, according to `objdump`, translates to `addr32 callq 14c00`, `0x67` being the `addr32` prefix). Upon encountering such an instruction, the instruction is simply dropped, resulting in a disconnected control flow graph.

A program containing such an instruction can be found [here](https://tobast.fr/files/bap_addr32_test.bin), its source code being [this](https://paste.tobast.fr/?c5b9073ab0116a58#cfKv9VmbHz2/kDkPR4JtAj5sweJIEmfS3h7scslVQCw=).

**Comment by ivg** [comment]
Note, this code occurs in C-runtime generated by modern compilers, e.g., this compiler is known to generate it:
```
$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-linux-gnu/8.2.1/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: /build/gcc/src/gcc/configure --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://bugs.archlinux.org/ --enable-languages=c,c++,ada,fortran,go,lto,objc,obj-c++ --enable-shared --enable-threads=posix --enable-libmpx --with-system-zlib --with-isl --enable-__cxa_atexit --disable-libunwind-exceptions --enable-clocale=gnu --disable-libstdcxx-pch --disable-libssp --enable-gnu-unique-object --enable-linker-build-id --enable-lto --enable-plugin --enable-install-libiberty --with-linker-hash-style=gnu --T --enable-multilib --disable-werror --enable-checking=release --enable-default-pie --enable-default-ssp --enable-cet=auto
Thread model: posix
gcc version 8.2.1 20180831 (GCC)
```
