### ISSUE TITLE
Problem with optimizations

### ISSUE THREAD

**Issue by kozera2137** [BinaryAnalysisPlatform/bap#905]
So as requested in #904. It seems to doesn't work correctly, although I'm not sure is it unwanted behavior. It's optimizng some othere instructions like 000000da but cannot get rid of obvious double assignment like 00000116.

```
ubuntu@DESKTOP-UG9LBOD:/mnt/c/Users/root/Desktop$ bap file.out -d > file.bap_dump
ubuntu@DESKTOP-UG9LBOD:/mnt/c/Users/root/Desktop$ bap file.out --optimization-level=3 -d > file.bap_dump_opt
```
[files.zip](https://github.com/BinaryAnalysisPlatform/bap/files/2667656/files.zip)

**Comment by ivg** [comment]
Can produce, bug confirmed.
