### ISSUE TITLE
Make Primus components more flexible

### ISSUE THREAD

**Issue by XVilka** [BinaryAnalysisPlatform/bap#910]
In `Plugins.run` function you just basically call `Plugins.load` and it is impossible to run plugin with a different arguments. It would be awesome to implement the ability to rerun plugin with a different arguments. https://github.com/BinaryAnalysisPlatform/bap/blob/master/lib/bap_plugins/bap_plugins.ml#L311

**Comment by ivg** [comment]
The plugin couldn't be unloaded. The plugin system is a mechanism for delivering libraries, which are linked once into a binary. The mechanism also provides an ability for one-time parametrization. Anything beyond this is is not in the design, so a direct library loading and initialization procedures should be used in a way specific to a particular library/plugin combination. In addition, the mechanism of streams from the bap-future library enables more dynamic configuration with options changing in time. 

To keep conversation less abstract, could you please provide your use case, so that I can advice for the proper solution?

**Comment by cxh852456** [comment]
i want to call a pass from another pass, but i can not change the options of the first one like you said(one-time parametrization), how shall i do if i want to call a pass from another pass and change the options of the first one?

**Comment by ivg** [comment]
It is not possible, passes are for calling from command line. From the source code, you shall use the library interface whenever possible. Which pass we're talking about? Is it a pass from bap?

**Comment by cxh852456** [comment]
yes, the passes from bap register by `register_pass` or `register_pass' `

**Comment by ivg** [comment]
I meant is that the pass provided by bap, i.e., one that is developed by us, or your own pass. And the main question was: "which pass we're talking about?", i.e., what's its name?

**Comment by cxh852456** [comment]
I write a plugin and register a pass such that it called `mypass`, i want to call `primus-limit` plugin with 
param max-length with different value by library interfaces, i found that i can't change the `max-length` 's value after `primus-limit` load.

**Comment by ivg** [comment]
That's true, the `primus-limit` plugin is designed in a such way that you can't change the limit during runtime. The expected use case is that you run it once with `--run` plugin. In general, you can write arbitrary schedulers and limiters for Primus and parametrize them to your taste. So `primus-limiter` implements some trade-off between usability and flexibility. 

We will think about, how we can make it more flexible, thanks for the user story. We will soon release Primus 2.0 which we hope would be much easier to use and which will try to make it more flexible and less dependent on the command line interface. To be honest, you're not the first one who is trying to do this. 

Meantime, the solutions for you would be to (a) run bap several times with different options or (b) write your own limited which will change the limit dynamically. And, as always, suggestions, are always welcome.

**Comment by XVilka** [comment]
By the way, I guess this one now can be closed? Because, BAP 2.0 was merged already.

**Comment by ivg** [comment]
This will be fixed only when Primus 2.0 will be ready, that is somewhere between 2.2 and 2.3, i.e., in half a year or year from today.

**Comment by ivg** [comment]
This was finally resolved in 2.1 release. We now have [systems and components][1] and it is possible to run as many different runs of Primus as desired with various configurations. 

[1]: https://binaryanalysisplatform.github.io/bap/api/master/bap-primus/Bap_primus/Std/index.html#components-and-systems
