### ISSUE TITLE
Unexpected end of basic block

### ISSUE THREAD

**Issue by Enkelmann** [BinaryAnalysisPlatform/bap#912]
While fiddling around with C++ exceptions, I encountered a case where bap unexpectedly ends a basic block and starts a new function instead. 

The first two blocks of the main function are

```
000002c9: sub main(main_argc, main_argv, main_result)
00000319: main_argc :: in u32 = RDI
0000031a: main_argv :: in out u64 = RSI
0000031b: main_result :: out u32 = RAX
000002ac: 
000002ad: v281 := RBP
000002ae: RSP := RSP - 8
000002af: mem := mem with [RSP, el]:u64 <- v281
000002b0: RBP := RSP
000002b2: RSP := RSP - 0x10
000002b9: RAX := mem[FS_BASE + 0x28, el]:u64
000002ba: mem := mem with [RBP + 0xFFFFFFFFFFFFFFF8, el]:u64 <- RAX
000002bb: RAX := 0
000002c2: RSI := 0xFB0
000002c3: RDI := 0x202020
000002c4: RSP := RSP - 8
000002c5: mem := mem with [RSP, el]:u64 <- 0xE3B
000002c6: call @_ZStlsISt11char_traitsIcEERSt13basic_ostreamIcT_ES5_PKc with return %000002c7

000002c7: 
000002c8: RDX := RAX
```
The next block in the disassembly is not part of the main function and instead starts a new function:
```
00000317: sub sub_e3e()
000002e7: 
000002e8: RAX := mem[0x201FD0, el]:u64
000002e9: RSI := RAX
000002ea: RDI := RDX
000002eb: RSP := RSP - 8
000002ec: mem := mem with [RSP, el]:u64 <- 0xE50
000002ed: call @_ZNSolsEPFRSoS_E with return %000002ee
```
There is also no edge in the call graph between the two functions, bap seems to think that the main function ends after two basic blocks. I have no idea why the basic block is ended prematurely and the issue vanishes when I change the source code at unrelated places.

I have attached the source file, which, when compiled with gcc, generated the binary above.
[source.zip](https://github.com/BinaryAnalysisPlatform/bap/files/2779084/source.zip)

**Comment by ivg** [comment]
That's interesting, do you have byteweight enabled? Usually it's the common suspect when an abrupt start of function occurs.

**Comment by Enkelmann** [comment]
Yes, byteweight seems to be the culprit. At least the bug vanished when adding the `--rooter=internal`-flag.

**Comment by ivg** [comment]
I believe that even with byteweight enabled this issue won't happen in BAP 2.x. We've rewritten the CFG partitioning algorithm so it is now much more robust. If you can try it again on the same binary but with BAP 2.x I would be grateful :)

**Comment by Enkelmann** [comment]
Running BAP 2.0 on the original binary generated the correct control flow graph, so I also assume that the issue is fixed now. Thanks!

**Comment by ivg** [comment]
thanks a lot!
