### ISSUE TITLE
Problems installing on 18.10

### ISSUE THREAD

**Issue by aaronjeline** [BinaryAnalysisPlatform/bap#924]
llvm 3.8 doesn't seem available on Ubuntu 18.10. 
Running `opam depext --install bap` fails when trying to install the required system packages.

**Comment by gitoleg** [comment]
`bap` supports lot's of LLVM versions, up to the 7th. So what you need to do is just to install a dev version of any that is available on your machine, e.g.:
```

**Comment by aaronjeline** [comment]
After installing llvm 6, `opam install bap` gives me
`Sorry, no solution found: there seems to be a problem with your request.

No solution found, exiting`

**Comment by gitoleg** [comment]
ok, so you installed `llvm-6.0-dev` package, did you?
What the version of `opam` do you use?

**Comment by aaronjeline** [comment]
I did install llvm
I am using version 1.2.2

**Comment by gitoleg** [comment]
well, it makes sense.
First of all, you are using an old version of `opam`. And authors of `opam` discourage users from using it.  In practice, it means that you can't install new packages from your `opam`.

Also, we were never happy about how `depext` works in the old `opam`. 
And the last version of bap that available for `1.2` version supports `llvm` up to 5th version.

If I were you I would upgrade `opam` to version `2.*` - the old one is sort of abandoned.
If you have some reasons to continue with the old one, there is still an option for you:
you can add our own repository:
```
opam repository add bap git://github.com/BinaryAnalysisPlatform/opam-repository#testing-legacy
```
and install bap from there.

**Comment by aaronjeline** [comment]
Alright so I updated the OPAM to 2.0.2. I'm not getting dependency error based on the ocaml version. I'm running 4.07. Is that a problem?

**Comment by gitoleg** [comment]
well, it depends on what are you doing. 
ocaml version for `bap.1.5.0` is constrained:
```
$ opam show bap.1.5.0
....
depends:      "ocaml" {>= "4.03" & < "4.06"}
```
so if you didn't do anything else except upgrading your opam, I bet you won't able to install bap on ocaml 4.07.  
Will take a look how it works for me a little bit later

**Comment by aaronjeline** [comment]
`<><> bap: information on all versions <><><><><><><><><><><><><><><><><><><><><>
name                   bap
all-installed-versions 1.5.0 [system]
all-versions           0.9.1  0.9.2  0.9.3  0.9.4  0.9.5  0.9.6  0.9.7  0.9.8
                       0.9.9  1.0.0  1.1.0  1.2.0  1.3.0  1.4.0  1.5.0

<><> Version-specific details <><><><><><><><><><><><><><><><><><><><><><><><><>
version       1.5.0
repository    default
url.src:      "https://github.com/BinaryAnalysisPlatform/bap/archive/v1.5.0.tar.gz"
url.checksum: "md5=9eed04fda6610dd4a8aa83948abfffc3"
homepage:     "https://github.com/BinaryAnalysisPlatform/bap/"
bug-reports:  "https://github.com/BinaryAnalysisPlatform/bap/issues"
dev-repo:     "git://github.com/BinaryAnalysisPlatform/bap/"
authors:      "BAP Team"
maintainer:   "Ivan Gotovchits <ivg@ieee.org>"
license:      "MIT"
depends:      "ocaml" {>= "4.03" & < "4.06"}
              "bap-abi" {= "1.5.0"}
              "bap-api" {= "1.5.0"}
              "bap-arm" {= "1.5.0"}
              "bap-beagle" {= "1.5.0"}
              "bap-bil" {= "1.5.0"}
              "bap-byteweight" {= "1.5.0"}
              "bap-c" {= "1.5.0"}
              "bap-cache" {= "1.5.0"}
              "bap-cxxfilt" {= "1.5.0"}
              "bap-callsites" {= "1.5.0"}
              "bap-constant-tracker" {= "1.5.0"}
              "bap-demangle" {= "1.5.0"}
              "bap-dump-symbols" {= "1.5.0"}
              "bap-frontend" {= "1.5.0"}
              "bap-frontc" {= "1.5.0"}
              "bap-llvm" {= "1.5.0"}
              "bap-mc" {= "1.5.0"}
              "bap-microx" {= "1.5.0"}
              "bap-mips" {= "1.5.0"}
              "bap-objdump" {= "1.5.0"}
              "bap-optimization" {= "1.5.0"}
              "bap-powerpc" {= "1.5.0"}
              "bap-primus" {= "1.5.0"}
              "bap-primus-dictionary" {= "1.5.0"}
              "bap-primus-lisp" {= "1.5.0"}
              "bap-primus-region" {= "1.5.0"}
              "bap-primus-support" {= "1.5.0"}
              "bap-primus-test" {= "1.5.0"}
              "bap-primus-x86" {= "1.5.0"}
              "bap-print" {= "1.5.0"}
              "bap-relocatable" {= "1.5.0"}
              "bap-report" {= "1.5.0"}
              "bap-run" {= "1.5.0"}
              "bap-ssa" {= "1.5.0"}
              "bap-std" {= "1.5.0"}
              "bap-strings" {= "1.5.0"}
              "bap-symbol-reader" {= "1.5.0"}
              "bap-taint" {= "1.5.0"}
              "bap-taint-propagator" {= "1.5.0"}
              "bap-term-mapper" {= "1.5.0"}
              "bap-trace" {= "1.5.0"}
              "bap-traces" {= "1.5.0"}
              "bap-trivial-condition-form" {= "1.5.0"}
              "bap-warn-unused" {= "1.5.0"}
              "bap-x86" {= "1.5.0"}
              "bap-emacs-goodies"
synopsis      Binary Analysis Platform
description
          The Carnegie Mellon University Binary Analysis Platform (CMU BAP) is
          a
          reverse engineering and program analysis platform that works with
          binary code and doesn't require the source code. BAP supports
          multiple
          architectures: ARM, x86, x86-64, PowerPC, and MIPS. BAP disassembles
          and lifts binary code into the RISC-like BAP Instruction Language
          (BIL). Program analysis is performed using the BIL representation and
          is architecture independent in a sense that it will work equally well
          for all supported architectures. The main purpose of BAP is to
          provide
          a toolkit for implementing automated program analysis. BAP is written
          in OCaml and it is the preferred language to write analysis, but we
          have bindings to C, Python and Rust. The Primus Framework also
          provide
          a Lisp-like DSL for writing program analysis tools.
          This is a meta package that installs essential parts of BAP.
`

Switched to language version 4.05, right now ocaml can't seem to find the modules

**Comment by aaronjeline** [comment]
Hey, I just got this to work. Thank you so much for your help. I wans't running `merlin-use` in emacs. Thanks again.
