### ISSUE TITLE
Installation instructions Macos with Brew

### ISSUE THREAD

**Issue by JoranHonig** [BinaryAnalysisPlatform/bap#925]
Hi,

I wanted to start playing around with bap for a bit, but unfortunately a fresh install of bap and ocaml on my machine didn't go so smoothly.

There seem to be two problems during the installation (`opam depext --install bap`):
```
#=== ERROR while compiling conf-bap-llvm.1.3 ==================================#
# context     2.0.3 | macos/x86_64 | ocaml-base-compiler.4.05.0 | https://opam.ocaml.org#9c708876
# path        ~/.opam/4.05.0/.opam-switch/build/conf-bap-llvm.1.3
# command     ~/.opam/opam-init/hooks/sandbox.sh build ocaml find-llvm.ml
# exit-code   1
# env-file    ~/.opam/log/conf-bap-llvm-11562-264e0c.env
# output-file ~/.opam/log/conf-bap-llvm-11562-264e0c.out
### output ###
# [...]
# command which llvm-config failed: exit status 1
# command ls /usr/local/Cellar | grep 3.8 failed: exit status 1
# command which llvm-config-mp-3.8 failed: exit status 1
# command which llvm-config-3.8 failed: exit status 1
# command which llvm-config-38 failed: exit status 1
# command which llvm-config failed: exit status 1
# command ls /usr/local/Cellar | grep 3.4 failed: exit status 1
# command which llvm-config-mp-3.4 failed: exit status 1
# command which llvm-config-3.4 failed: exit status 1
# command which llvm-config-34 failed: exit status 1
# command which llvm-config failed: exit status 1
# LLVM not found


#=== ERROR while compiling bap-objdump.1.5.0 ==================================#
# context     2.0.3 | macos/x86_64 | ocaml-base-compiler.4.05.0 | https://opam.ocaml.org#9c708876
# path        ~/.opam/4.05.0/.opam-switch/build/bap-objdump.1.5.0
# command     ~/.opam/opam-init/hooks/sandbox.sh build ./configure --prefix=/Users/walker/.opam/4.05.0 --enable-objdump --objdump-targets=[] --objdump-path=
# exit-code   1
# env-file    ~/.opam/log/bap-objdump-11562-cb921b.env
# output-file ~/.opam/log/bap-objdump-11562-cb921b.out
### output ###
# configure options:
# [...]
#   --sharedstatedir dir       Modifiable architecture-independent data [$prefix/com]
#   --sysconfdir dir           Read-only single-machine data [$prefix/etc]
#   --libexecdir dir           Program executables [$exec_prefix/libexec]
#   --sbindir dir              System admin executables [$exec_prefix/sbin]
#   --bindir dir               User executables [$exec_prefix/bin]
#   --exec-prefix dir          Install architecture-dependent files in dir [$prefix]
#   --prefix dir               Install architecture-independent files dir [/usr/local]
#   --print-hidden Print       even non-printable variable. (debug)  [false]
#   -help                      Display this list of options
#   --help                     Display this list of options
# 
```

Some prior issue (https://github.com/ocaml/opam-repository/issues/7575) indicates that the first problem is caused by brew not properly settingup the path variable.
Adding `/usr/local/Cellar/llvm@6/6.0.1_1` to my path variable makes compilation of `conf-bap-llvm` succeed but gives a new error:

```
#=== ERROR while compiling bap-llvm.1.5.0 =====================================#
# context     2.0.3 | macos/x86_64 | ocaml-base-compiler.4.05.0 | https://opam.ocaml.org#9c708876
# path        ~/.opam/4.05.0/.opam-switch/build/bap-llvm.1.5.0
# command     ~/.opam/opam-init/hooks/sandbox.sh build make
# exit-code   2
# env-file    ~/.opam/log/bap-llvm-74651-6aa130.env
# output-file ~/.opam/log/bap-llvm-74651-6aa130.out
### output ###
# [...]
# In file included from /usr/local/Cellar/llvm@6/6.0.1_1/include/llvm/ADT/StringRef.h:13:
# In file included from /usr/local/Cellar/llvm@6/6.0.1_1/include/llvm/ADT/STLExtras.h:20:
# In file included from /usr/local/Cellar/llvm@6/6.0.1_1/include/llvm/ADT/Optional.h:22:
# In file included from /usr/local/Cellar/llvm@6/6.0.1_1/include/llvm/Support/type_traits.h:19:
# In file included from /usr/local/Cellar/llvm@6/6.0.1_1/include/c++/v1/utility:202:
# In file included from /usr/local/Cellar/llvm@6/6.0.1_1/include/c++/v1/cstring:61:
# /usr/local/Cellar/llvm@6/6.0.1_1/include/c++/v1/string.h:61:15: fatal error: 'string.h' file not found
# #include_next <string.h>
#               ^~~~~~~~~~
# 1 error generated.
# Command exited with code 1.
# make: *** [build] Error 1

```

It's unclear on which version of llvm bap actually depends:
```
The packages you requested declare the following system dependencies. Please
make sure they are installed before retrying:
    llvm@6
```
Is reported when trying to execute `opam depext --install conf-bap-llvm`
While the troubleshooting page indicates support for version 3.4 and 3.8 of llvm.
Could this second issue in bap-llvm be caused by a version mismatch?

The second issue (relating to objdump) has also recently been reported in #921, the reporter describes using a development version, which is not entirely clear to me. Is anyone able to elaborate on the action required to solve this problem?

Once I've been able to do an install of bap I'm happy to write a piece of documentation for the readme / wiki, with install instructions for how to install bap w/ brew, if that's appreciated

**Comment by ivg** [comment]
First off thanks for a nice bug report :)

The problem with the LLVM actually indicates that you XCode is either broken, out of date, or just missing (especially the command line tools). We, in house, usually rely in on macports, which require XCode to be properly set up, so we usually don't get that far. 

This [link][1]  might give you some insights, on how to set things up.

[1]: https://discourse.brew.sh/t/solved-scan-build-from-llvm-7-0-seems-broken-on-macos-mojave/3151

**Comment by ivg** [comment]
Also, if you're on Mojave, then [this][1] could be also relevant.

[1]: https://github.com/neovim/neovim/issues/9050

**Comment by JoranHonig** [comment]
Thanks for the quick response!

Fixing my xcode installation has indeed solved the first problem (installing `conf-bap-llvm` and `bap-llvm`)

However the second problem (installing `bap-objdump`) remains. I've included the output file mentioned in the error output:
```
none: option '--objdump-path' needs an argument.
configure options:
  --override var+val         Override any configuration variable.
  --enable-tests             Compile tests executable and library and run them [default: disabled]
  --disable-tests            Compile tests executable and library and run them [default: disabled]
  --enable-docs              Create documentations [default: enabled]
  --disable-docs             Create documentations [default: enabled]
  --enable-objdump           Build objdump plugin [default: disabled]
  --disable-objdump          Build objdump plugin [default: disabled]
  --enable-everything        Build every feature by default [default: disabled]
  --disable-everything       Build every feature by default [default: disabled]
  --with-cc-optimization str C compiler optimization level [-O2]
  --with-cxxlibs str         c++ library [-lc++]
  --with-cxx str             c++ compiler [/usr/bin/c++]
  --objdump-path str         A path to [g]objdump binary
  --objdump-targets str      A list (OCaml syntax) of supported targets
  --plugindir str            A default folder for plugins
  --enable-profile           Turn ocaml profile flag on [default: disabled]
  --disable-profile          Turn ocaml profile flag on [default: disabled]
  --enable-debug             Turn ocaml debug flag on [default: enabled]
  --disable-debug            Turn ocaml debug flag on [default: enabled]
  --destdir dir              Prepend a path when installing package
  --psdir dir                PS documentation [$docdir]
  --pdfdir dir               PDF documentation [$docdir]
  --dvidir dir               DVI documentation [$docdir]
  --htmldir dir              HTML documentation [$docdir]
  --docdir dir               Documentation root [$datarootdir/doc/$pkg_name]
  --mandir dir               Man documentation [$datarootdir/man]
  --localedir dir            Locale-dependent data [$datarootdir/locale]
  --infodir dir              Info documentation [$datarootdir/info]
  --datadir dir              Read-only architecture-independent data [$datarootdir]
  --datarootdir dir          Read-only arch-independent data root [$prefix/share]
  --libdir dir               Object code libraries [$exec_prefix/lib]
  --localstatedir dir        Modifiable single-machine data [$prefix/var]
  --sharedstatedir dir       Modifiable architecture-independent data [$prefix/com]
  --sysconfdir dir           Read-only single-machine data [$prefix/etc]
  --libexecdir dir           Program executables [$exec_prefix/libexec]
  --sbindir dir              System admin executables [$exec_prefix/sbin]
  --bindir dir               User executables [$exec_prefix/bin]
  --exec-prefix dir          Install architecture-dependent files in dir [$prefix]
  --prefix dir               Install architecture-independent files dir [/usr/local]
  --print-hidden Print       even non-printable variable. (debug)  [false]
  -help                      Display this list of options
  --help                     Display this list of options
```
I'm sure that objdump is installed
`which objdump`
returns
`/usr/bin/objdump`

**Comment by ivg** [comment]
Nice. So first of all, the bap-objdump package is not very important, especially on a Mac OS X, so you can start playing with BAP right now. 

Concerning the problem, our conf-binutils script is expecting the `gobdump` tool on Darwin, not `objdump` which is an overhauled `llvm-objdump`, which is not an objdump at all. Well, at least in my installation, in your system it could be overridden by a true objdump. If it is true that homebrew provides `objdump` under the `objdump` name, then we can update our `conf-binutils` script to reflect that fact.

And in any case, it looks like that the `conf-binutils` package is not failing gracefully, as it should actually stop with an error, instead of delaying the failure to the compilation. @gitoleg, can you please take a look into it?

**Comment by JoranHonig** [comment]
> Nice. So first of all, the bap-objdump package is not very important, especially on a Mac OS X, so you can start playing with BAP right now.

Great news 👍 

For what it's worth, it doesn't seem like brew provided the objdump on my machine, looking at the output of `objdump` it seems like it indeed could be llvms' objdump:
```
>$ objdump
OVERVIEW: llvm object file dumper
```

**Comment by ivg** [comment]
looks like it worked finally :)

**Comment by loganleland** [comment]
Hello, ivg and JoranHonig,

  I've found myself in the same situation, although my compilation is stopping on the conf-binutils.0.2 section. I do have the llvm objdump on my system but can't seem to find a quick alternative. Here's my build error report:

# Detecting depexts using vars: arch=x86_64, os=macos, os-distribution=homebrew, os-family=homebrew
# The following system packages are needed:
binutils
gmp
llvm@6
# All required OS packages found.
# Now letting OPAM install the packages
The following actions will be performed:
  ↗ upgrade conf-binutils 0.1 to 0.2 [required by bap-cxxfilt, bap-objdump]
  ∗ install bap-objdump   1.6.0      [required by bap]
  ∗ install bap-cxxfilt   1.6.0      [required by bap]
  ∗ install bap           1.6.0
===== ∗ 3   ↗ 1 =====
Do you want to continue? [Y/n] Y

<><> Gathering sources ><><><><><><><><><><><><><><><><><><><><><><><><><><>  🐫 
[bap.1.6.0] found in cache
[bap-cxxfilt.1.6.0] found in cache
[bap-objdump.1.6.0] found in cache

<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><>  🐫 
[ERROR] The compilation of conf-binutils failed at
        "/Users/loganleland/.opam/opam-init/hooks/sandbox.sh build ocaml
        find-binutils.ml".

#=== ERROR while compiling conf-binutils.0.2 ==================================#
# context     2.0.4 | macos/x86_64 | ocaml-base-compiler.4.05.0 | https://opam.ocaml.org#45b0aff7
# path        ~/.opam/4.05.0/.opam-switch/build/conf-binutils.0.2
# command     ~/.opam/opam-init/hooks/sandbox.sh build ocaml find-binutils.ml
# exit-code   1
# env-file    ~/.opam/log/conf-binutils-21171-d0f245.env
# output-file ~/.opam/log/conf-binutils-21171-d0f245.out
### output ###
# command which gobjdump failed: exit status 1
# objdump not found



<><> Error report <><><><><><><><><><><><><><><><><><><><><><><><><><><><><>  🐫 
┌─ The following actions failed
│ λ build conf-binutils 0.2
└─ 
╶─ No changes have been performed

The packages you requested declare the following system dependencies. Please make sure
they are installed before retrying:
    binutils

**Comment by ivg** [comment]
For those who stumble with the same problem, like that binutils do not work on Mac OS X, the suggestion is to just ignore that issue. This is a non-essential package and bap will work fine without it. Just continue using bap. 

---------
P.S. Logan Leland, I've got a notification from you on my email, but I can't reply there, as there is no return address of yours :) Also, if you have any problems it is better to create a new issue, or reopen existing, or just visit our gitter chat. It is hard in github to follow changes in closed issues.

**Comment by loganleland** [comment]
Thanks so much for the email,

  I've successfully ignored the error message and have started writing my own plugins. So happy I've discovered BAP!
________________________________________
