### ISSUE TITLE
Bap.Value.find too slow

### ISSUE THREAD

**Issue by cxh852456** [BinaryAnalysisPlatform/bap#930]
i create a Hashtbl object by Tid.Table.create and insert about 70k elem, then i found the bap run very very slow.
then i use perf to check what's the problem and i found the follow infomation:

![image](https://user-images.githubusercontent.com/1539666/54029407-3ee3aa00-41e3-11e9-9714-da9ff9fa086a.png)

 and another question is the key point of the issue in the ida seems not my code.
![image](https://user-images.githubusercontent.com/1539666/54029497-8cf8ad80-41e3-11e9-8115-dbc2052fd211.png)

**Comment by ivg** [comment]
If you have created the table with `Tid.Table.create`, then this table has nothing to do with the `value` type and in fact it should be fast. As fast, as a table of OCaml integers. So either you misspelled the type of the table or this is not that table that is the bottleneck, or the table itself is not a bottleneck. Also, there is no such function as `Bap.Value.find`, nor `Value.find`, but read ahead :) 

The `value` type is known to be slow, that's true. It will be much faster in BAP 2.x, and we're planning to backport optimizations (as much as possible). Basically, right now, the compare function, as well as the representation is extremely unoptimized. And putting values as keys in any container is a bad idea, e.g., `Value.Map.t`, `Value.Table.t`, `Value.Set.t`, etc will all behave very slowly. 

With all that said, I'm not sure that in your case this is actually the problem. I can't guarantee with 100% that my demangling is right, but the only `find` function in the `Bap_value` module, actually uses the `Base.Type_equal.uid` type as key (which is an OCaml `int`, nothing more). Moreover, it is not a hashtbale, but a map (Int.Map.t basically) so it is as fast as OCaml maps can work. The maps are implemented as binary trees, so a search in a map with 70k elements will take only 16 steps, should be actually the bottleneck. My suggestion, is to look up in the stack of calls and see if you actually call this function in a tight loop and if it is true, try to optimize the algorithm.

> the key point of the issue in the ida seems not my code

Mmm... not sure I understood.

**Comment by ivg** [comment]
Closing, as there is no input from the OP. Feel free to reopen, if you have opened questions.
