### ISSUE TITLE
Revive bap linear sweep output from old readbin into bap-objdump

### ISSUE THREAD

**Issue by dbrumley** [BinaryAnalysisPlatform/bap#94]
There should be an option to output the linear sweep disassembly of a section/segment, as done with objdump -D <file>.  This would be useful towards making bap a complete replacement for objdump.

**Comment by ivg** [comment]
Why should we strive to replace objdump? If we can provide more sane behavior, what is the reason to downshift? Also, adding linear sweeping, will make 99% of bap-objdump options unsane, that will frustrate users.

**Comment by dbrumley** [comment]
One reason is the name: bap-objdump. 
Second reason: looking at a linear sweep is the least amount of analysis that could go wrong for a base functionality test of parsing an executable and outputting disassembly.
Third reason: transition path for existing users. Convincing someone to use bap is easier if you can show it is indeed better. If we have orthogonal behavior, it's hard to show it better. I would argue that a simple linear sweep from start to end is so ingrained in objdump, gdb, and other tools that not having it is suspicious.
Fourth reason: debugging. With -d you could compare with objdump to find where there are differences, e.g., to find llvm bugs or to find objdump bugs.  
Fifth reason: simplicity. Currently bap-objdump does not appear to print out anything when a symbol table is not available. Function boundary inference may help, but does not seem smart to make FBI a hard dependency on basic functionality.

I don't see how 99% of options become unsane. To be clear, the suggestion is to structure the program so you can print out linear sweep as an option. You can still build the CFG based on specified roots, either inferred or specified.  

Can you please elaborate what options would not make sense by adding an option to do a linear sweep from entry to section end or section start to section end?  -d, --demangle, -ddests, --help, --labels-with-asm, --labels-with-bil, --labels-with-name -p -s don't seem to depend on whether you are using linear sweep or not.

**Comment by ivg** [comment]
all options will actually stop to work. This is how program is structured. The least effort would be write new objdump from scratch. And rename what we now calling `bap-objdump` to `bap-disasm` or something else.  And current (starting from friday evening, when I've merged @ddcc's PR) behavior of bap-objdump is to print something even when no symbols are available, or provided.

If you think, that we need objdump clone, we will make it. But, it will take some time, and I'm not sure that this task has high priority.

**Comment by ivg** [comment]
done in #344 

use `-dasm` format to print a program, the output is quite similar to the objdump, e.g., 
```
Disassembly of section .text

00018d6c: <__adddf3>
00018d6c:
00018d6c: 30 40 2d e9                             push {r4, r5, lr}
00018d70: 81 40 a0 e1                             lsl r4, r1, #1
00018d74: 83 50 a0 e1                             lsl r5, r3, #1
00018d78: 05 00 34 e1                             teq r4, r5
00018d7c: 02 00 30 01                             teqeq r0, r2
00018d80: 00 c0 94 11                             orrsne r12, r4, r0
00018d84: 02 c0 95 11                             orrsne r12, r5, r2
00018d88: c4 ca f0 11                             mvnsne r12, r4, asr #21
00018d8c: c5 ca f0 11                             mvnsne r12, r5, asr #21
00018d90: 79 00 00 0a                             beq #0x1e4
00018f7c:
00018f7c: c4 ca f0 e1                             mvns r12, r4, asr #21
00018f80: c5 ca f0 11                             mvnsne r12, r5, asr #21
00018f84: 18 00 00 0a                             beq #0x60
```
