### ISSUE TITLE
CFG missing Jump edge

### ISSUE THREAD

**Issue by iamdeeban** [BinaryAnalysisPlatform/bap#963]
Hi. I have some queries related to CFG generated using BAP and explicit-edge analysis results. (If I need to move the explicit-edge related questions to draperlab thread please ignore them. I will ask it in their tracker.)  

1. I used this small switch [binary](https://drive.google.com/open?id=1BaY0NRM74isaGN3uzuvSHGut-L3-svWP) to see jumps. After manually extracting and visualizing as xdot .. we could see that there is no edge for jump as shown below . Should it not have an edge for jump?

![image](https://user-images.githubusercontent.com/45299442/62465531-67220580-b78f-11e9-8db0-8c9ef798a5f1.png)

2. we are able to obtain disassembly in terminal using the command `bap ./switch -dasm`, but is there a way to get outputs in normal assembly instead of BIL in the **CFG**? Like the one below for example from angr..same goes for ida i guess.

![image](https://user-images.githubusercontent.com/45299442/62465569-7dc85c80-b78f-11e9-812b-a0f128e117ed.png)

3. There are some values shown along with function after vsa / explicit-edge analysis? Are they addresses of the function or offset values? (Highlighted in picture below)

![image](https://user-images.githubusercontent.com/45299442/62465591-8b7de200-b78f-11e9-90c7-59720e83264a.png)

4. For a small [binary](https://drive.google.com/open?id=1BaY0NRM74isaGN3uzuvSHGut-L3-svWP) explicit -edge fails/crash for main function where jumptable is . Any pointers to debug?

![image](https://user-images.githubusercontent.com/45299442/62465645-b1a38200-b78f-11e9-9b55-1be954d4c8df.png)

5. Also for explicit-edge analysis to specify for a particular function I use the command `bap ./switch -p explicit-edge --explicit-edge-sub main`  but it still performs and print to terminal all outputs for all functions with crashing before main function. Is there some error in my command specification? (sample output listed below)

![image](https://user-images.githubusercontent.com/45299442/62465653-b831f980-b78f-11e9-90cb-3ecb64fc651c.png)

**Comment by ivg** [comment]
Well, all those questions should be redirected to [Draperslab's issue tracker][1] because they all relate to their analysis. I can comment only on this one

> we are able to obtain disassembly in terminal using the command bap ./switch -dasm, but is there a way to get outputs in normal assembly instead of BIL in the CFG? Like the one below for example from angr..same goes for ida i guess.

Nope, the print plugin is only able to print CFG annotated with IR. But it is easy to write a plugin that will print in whatever format you would like. You can use the following code as an inspirational example, 

```ocaml
open Core_kernel
open Regular.Std
open Graphlib.Std
open Bap.Std
open Format
include Self()

let pp_sep ppf () = Format.fprintf ppf "\\l"
let pp_insn ppf (mem,insn) =
  Format.fprintf ppf "%s: %a"
    (Addr.string_of_value (Memory.min_addr mem))
    Insn.pp insn

let pp_fn ppf (name,_,g) =
  Graphlib.to_dot (module Graphs.Cfg)
    ~formatter:ppf
    ~graph_attrs:(fun _ -> [`Label name])
    ~node_attrs:(fun _ -> [`Shape `Box])
    ~string_of_node:(fun n ->
        asprintf "\"%s:\\l%a\\l\""
          (Addr.string_of_value (Block.addr n))
          (pp_print_list ~pp_sep pp_insn)
          (Block.insns n))
    g

let pp_cfg ppf proj =
  Project.symbols proj |>
  Symtab.to_sequence |>
  Seq.iter ~f:(fprintf ppf "%a@\n" pp_fn)

let () = Config.when_ready (fun _ ->
    Project.add_writer ~ver:"1.0.0"
      ~desc:"print a simple CFG"
      "acfg"
      (Data.Write.create ~pp:pp_cfg ()))
```

To build and install, create a new folder and put this code in a file named `acfg.ml`, then do
```
bapbuild acfg.plugin
bapbundle install acfg.plugin
```
now you can select the `acfg` format,

```
bap ./exe -dacfg > out.dot
```

The output will contain all subroutines, which could be easily rendered with 

```
dot -Tps out.dot -o out.ps
```
which will create postscript document with each subroutine on a separate page, which could be viewed with
```
evince out.ps
```



[1]: https://github.com/draperlaboratory/cbat_tools/issues

**Comment by iamdeeban** [comment]
Thank you very much for your inputs @ivg . I will go ahead with draperlab issue tracker.

**Comment by ivg** [comment]
follow up: https://github.com/draperlaboratory/cbat_tools/issues/54
