### ISSUE TITLE
update Travis CI infrastructure

### ISSUE THREAD

**Issue by ivg** [BinaryAnalysisPlatform/bap#965]
Our Travis infrastructure is outdated and still uses opam 1.x, therefore we're checking installability in a non-existent universe. Additionally, we can't move forward, because new packages are not available in the old opam repository. For example, this stops us (from testing) on 4.07, see #957

**Comment by XVilka** [comment]
Also related: https://github.com/BinaryAnalysisPlatform/bap/issues/956

**Comment by ivg** [comment]
update: we're not actually using opam 1.x, while it is indeed installed. But anyway our travis files are outdated, so we need to sync with the upstream.

Also in #957 the problem is not in the version of opam, as I stated originally, but rather because the new piqi library wasn't yet released.

**Comment by XVilka** [comment]
Please also see the problem https://github.com/BinaryAnalysisPlatform/bap/pull/957#issuecomment-521899053 - it seems that Travis doesn't get the sources for pull requests properly.

**Comment by XVilka** [comment]
I think it might be closed, since these points were addressed.
