### ISSUE TITLE
[Question] Get all instructions in IR, like a list

### ISSUE THREAD

**Issue by wonderluster** [BinaryAnalysisPlatform/bap#994]
How to simply disassemble a binary to IR, and get all the instruction opcode in a sequence, like a Python list?
For loops, we can expand it 10 times.
It's better to use Python...

**Comment by ivg** [comment]
Write a visitor that will append it to the list, e.g.,
```python
class Collector(Visitor) :
    def __init__(self):
        self.terms = []

    def enter_Term(self,term):
        self.terms += term
```

**Comment by ivg** [comment]
Feel free to reopen if you still have questions, also don't hesitate to drop by our [gitter channel][1].


[1]: https://gitter.im/BinaryAnalysisPlatform/bap
